// =============================================================================
// Originally from ASSET (AlabamaASRL/asset_asrl)
// Copyright 2020-present The University of Alabama-Astrodynamics and Space
//   Research Lab. Licensed under the Apache License, Version 2.0
// License: notices/asset-apache2.txt.
// Source: https://github.com/AlabamaASRL/asset_asrl
// Original Developer: James B. Pezent
//
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_mee_dynamics.py — do not edit manually.
// =============================================================================
#pragma once

#include <limits>
#include <stdexcept>

#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct MEEDynamics : VectorFunction<MEEDynamics, 9, 6, DenseDerivativeMode::Analytic,
                                    DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<MEEDynamics, 9, 6, DenseDerivativeMode::Analytic,
                                DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu_ = std::numeric_limits<double>::quiet_NaN(); // Gravitational Parameter
    static constexpr bool is_vectorizable = true;

    // Precomputed from constructor parameters
    double pc0_ = std::numeric_limits<double>::quiet_NaN();
    double pc1_ = std::numeric_limits<double>::quiet_NaN();

    MEEDynamics() : MEEDynamics(1.0) {}

    MEEDynamics(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument("MEEDynamics: mu must satisfy mu > 0.0");
        this->set_io_rows(9, 6);
        mu_ = mu;
        pc0_ = std::sqrt(mu_);
        pc1_ = 1.0 / pc0_;
    }

    void set_mu(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument("MEEDynamics: mu must satisfy mu > 0.0");
        mu_ = mu;
        pc0_ = std::sqrt(mu_);
        pc1_ = 1.0 / pc0_;
    }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_, CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = x1 * cos(x5) + x2 * sin(x5) + 1;
        Scalar x9 = 1.0 / _hp0_;
        Scalar x10 = x7 * x9;
        Scalar x11 = sin(x5);
        Scalar x12 = cos(x5);
        Scalar x13 = x11 * x3 - x12 * x4;
        Scalar x14 = x8 * x9;
        Scalar x15 = x1 * x12 + x11 * x2 + 2;
        Scalar x16 = Scalar(pc1_ * sqrt(x0));
        Scalar x17 = x13 * x14;
        Scalar x18 = x14 * x16 * ((1.0 / 2.0) * (x3 * x3) + (1.0 / 2.0) * (x4 * x4) + 1.0 / 2.0);

        _fx_[0] = Scalar(2 * pc1_ * (sqrt(x0) * x0) * x10);
        _fx_[1] = x16 * (x10 * (x1 + x12 * x15) + x11 * x6 - x13 * x14 * x2);
        _fx_[2] = x16 * (x1 * x17 + x10 * (x11 * x15 + x2) - x12 * x6);
        _fx_[3] = x12 * x18;
        _fx_[4] = x11 * x18;
        _fx_[5] = Scalar(x16 * ((_hp0_ * _hp0_) * mu_ / (x0 * x0) + x17));
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_, CVecRef<OutType> fx_,
                                      CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = x1 * cos(x5) + x2 * sin(x5) + 1;
        Scalar _hp1_ = cos(x5);
        Scalar _hp2_ = sin(x5);
        Scalar x9 = 1.0 / _hp0_;
        Scalar x10 = x7 * x9;
        Scalar x11 = Scalar(2 * pc1_ * (sqrt(x0) * x0));
        Scalar x12 = _hp2_ * x6;
        Scalar x13 = _hp1_ * x4;
        Scalar x14 = _hp2_ * x3;
        Scalar x15 = x13 - x14;
        Scalar x16 = x8 * x9;
        Scalar x17 = x15 * x16;
        Scalar x18 = _hp1_ * x1;
        Scalar x19 = _hp2_ * x2;
        Scalar x20 = x18 + x19 + 2;
        Scalar x21 = _hp1_ * x20;
        Scalar x22 = x1 + x21;
        Scalar x23 = x10 * x22 + x12 + x17 * x2;
        Scalar x24 = sqrt(x0);
        Scalar x25 = Scalar(pc1_ * x24);
        Scalar x26 = _hp1_ * x6;
        Scalar x27 = -x15;
        Scalar x28 = x16 * x27;
        Scalar x29 = _hp2_ * x20;
        Scalar x30 = x2 + x29;
        Scalar x31 = x1 * x28 + x10 * x30 - x26;
        Scalar x32 = (x3 * x3);
        Scalar x33 = (x4 * x4);
        Scalar x34 = (1.0 / 2.0) * x32 + (1.0 / 2.0) * x33 + 1.0 / 2.0;
        Scalar x35 = _hp1_ * x25;
        Scalar x36 = x16 * x35;
        Scalar x37 = x34 * x36;
        Scalar x38 = _hp2_ * x25;
        Scalar x39 = x16 * x38;
        Scalar x40 = x34 * x39;
        Scalar x41 = (_hp0_ * _hp0_);
        Scalar x42 = Scalar(mu_ / (x0 * x0));
        Scalar x43 = x28 + x41 * x42;
        Scalar x44 = 1.0 / x41;
        Scalar x45 = x44 * x7;
        Scalar x46 = x11 * x45;
        Scalar x47 = _hp1_ * x2;
        Scalar x48 = -_hp2_ * x1 + x47;
        Scalar x49 = -x48;
        Scalar x50 = 1.0 / x24;
        Scalar x51 = Scalar(pc1_ * x50);
        Scalar x52 = (1.0 / 2.0) * x51;
        Scalar x53 = (_hp1_ * _hp1_);
        Scalar x54 = x44 * x8;
        Scalar x55 = x15 * x54;
        Scalar x56 = x22 * x45;
        Scalar x57 = _hp1_ * _hp2_ * x10;
        Scalar x58 = x16 * x25;
        Scalar x59 = _hp1_ * x3;
        Scalar x60 = _hp2_ * x4;
        Scalar x61 = x59 + x60;
        Scalar x62 = x25 * x9;
        Scalar x63 = x27 * x54;
        Scalar x64 = x30 * x45;
        Scalar x65 = (_hp2_ * _hp2_);
        Scalar x66 = _hp2_ * x1;
        Scalar x67 = x16 * x61;
        Scalar x68 = x49 * x63;
        Scalar x69 = x27 * x62;
        Scalar x70 = x16 * x51 * ((1.0 / 4.0) * x32 + (1.0 / 4.0) * x33 + 1.0 / 4.0);
        Scalar x71 = x34 * x54;
        Scalar x72 = x25 * x71;
        Scalar x73 = x38 * x71;
        Scalar x74 = -_hp1_ * x73;
        Scalar x75 = x34 * x9;
        Scalar x76 = _hp0_ * x42;
        Scalar x77 = 2 * x76;

        _fx_[0] = x10 * x11;
        _fx_[1] = x23 * x25;
        _fx_[2] = x25 * x31;
        _fx_[3] = x37;
        _fx_[4] = x40;
        _fx_[5] = x25 * x43;

        _jx_(0, 0) = 3 * x10 * x25;
        _jx_(1, 0) = x23 * x52;
        _jx_(2, 0) = x31 * x52;
        _jx_(3, 0) = _hp1_ * x70;
        _jx_(4, 0) = _hp2_ * x70;
        _jx_(5, 0) =
            Scalar(-2 * pc0_ * x41 / (sqrt(x0) * x0 * x0) + (1.0 / 2.0) * pc1_ * x43 * x50);
        _jx_(0, 1) = -_hp1_ * x46;
        _jx_(1, 1) = x25 * (-_hp1_ * x56 - x47 * x55 + x7 * x9 * (x53 + 1));
        _jx_(2, 1) = x25 * (-_hp1_ * x64 - x18 * x63 + x28 + x57);
        _jx_(3, 1) = -x53 * x72;
        _jx_(4, 1) = x74;
        _jx_(5, 1) = x25 * (-_hp1_ * x63 + _hp1_ * x77);
        _jx_(0, 2) = -_hp2_ * x46;
        _jx_(1, 2) = x25 * (-_hp2_ * x56 + x17 - x19 * x55 + x57);
        _jx_(2, 2) = x25 * (-_hp2_ * x64 - x63 * x66 + x7 * x9 * (x65 + 1));
        _jx_(3, 2) = x74;
        _jx_(4, 2) = -x65 * x72;
        _jx_(5, 2) = x25 * (-_hp2_ * x63 + _hp2_ * x77);
        _jx_(0, 3) = 0;
        _jx_(1, 3) = -x19 * x58;
        _jx_(2, 3) = x58 * x66;
        _jx_(3, 3) = x58 * x59;
        _jx_(4, 3) = x14 * x58;
        _jx_(5, 3) = x39;
        _jx_(0, 4) = 0;
        _jx_(1, 4) = x47 * x58;
        _jx_(2, 4) = -x18 * x58;
        _jx_(3, 4) = x13 * x58;
        _jx_(4, 4) = x58 * x60;
        _jx_(5, 4) = -x36;
        _jx_(0, 5) = x46 * x49;
        _jx_(1, 5) =
            x25 * (x10 * (_hp1_ * x48 - x29) - x16 * x2 * x61 + x2 * x49 * x55 + x26 + x49 * x56);
        _jx_(2, 5) = x25 * (x1 * x67 + x1 * x68 + x10 * (_hp2_ * x48 + x21) + x12 + x49 * x64);
        _jx_(3, 5) = Scalar(_hp1_ * pc1_ * x24 * x34 * x44 * x49 * x8 - x40);
        _jx_(4, 5) = x37 + x49 * x73;
        _jx_(5, 5) = x25 * (x67 + x68 + x76 * (2 * x47 - 2 * x66));
        _jx_(0, 6) = 0;
        _jx_(1, 6) = x38;
        _jx_(2, 6) = -x35;
        _jx_(3, 6) = 0;
        _jx_(4, 6) = 0;
        _jx_(5, 6) = 0;
        _jx_(0, 7) = x11 * x9;
        _jx_(1, 7) = x22 * x62;
        _jx_(2, 7) = x30 * x62;
        _jx_(3, 7) = 0;
        _jx_(4, 7) = 0;
        _jx_(5, 7) = 0;
        _jx_(0, 8) = 0;
        _jx_(1, 8) = x15 * x2 * x62;
        _jx_(2, 8) = x1 * x69;
        _jx_(3, 8) = x35 * x75;
        _jx_(4, 8) = x38 * x75;
        _jx_(5, 8) = x69;
    }

    template <class InType, class OutType, class JacType, class AdjGradType, class AdjHessType,
              class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_, CVecRef<OutType> fx_, CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_, CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar _hp0_ = x1 * cos(x5) + x2 * sin(x5) + 1;
        Scalar _hp1_ = cos(x5);
        Scalar _hp2_ = sin(x5);
        Scalar x9 = 1.0 / _hp0_;
        Scalar x10 = x7 * x9;
        Scalar x11 = (sqrt(x0) * x0);
        Scalar x12 = 2 * x11;
        Scalar x13 = Scalar(pc1_ * x12);
        Scalar x14 = _hp2_ * x6;
        Scalar x15 = _hp1_ * x4;
        Scalar x16 = _hp2_ * x3;
        Scalar x17 = x15 - x16;
        Scalar x18 = x17 * x9;
        Scalar x19 = x18 * x8;
        Scalar x20 = _hp1_ * x1;
        Scalar x21 = _hp2_ * x2;
        Scalar x22 = x20 + x21;
        Scalar x23 = x22 + 2;
        Scalar x24 = _hp1_ * x23;
        Scalar x25 = x1 + x24;
        Scalar x26 = x10 * x25 + x14 + x19 * x2;
        Scalar x27 = sqrt(x0);
        Scalar x28 = Scalar(pc1_ * x27);
        Scalar x29 = _hp1_ * x6;
        Scalar x30 = -x17;
        Scalar x31 = x30 * x9;
        Scalar x32 = x31 * x8;
        Scalar x33 = _hp2_ * x23;
        Scalar x34 = x2 + x33;
        Scalar x35 = x1 * x32 + x10 * x34 - x29;
        Scalar x36 = (x3 * x3);
        Scalar x37 = (x4 * x4);
        Scalar x38 = (1.0 / 2.0) * x36 + (1.0 / 2.0) * x37 + 1.0 / 2.0;
        Scalar x39 = _hp1_ * x28;
        Scalar x40 = x8 * x9;
        Scalar x41 = x39 * x40;
        Scalar x42 = x38 * x41;
        Scalar x43 = _hp2_ * x28;
        Scalar x44 = x40 * x43;
        Scalar x45 = x38 * x44;
        Scalar x46 = (_hp0_ * _hp0_);
        Scalar x47 = (Scalar(1.0) / (x0 * x0));
        Scalar x48 = Scalar(mu_ * x47);
        Scalar x49 = x32 + x46 * x48;
        Scalar x50 = 3 * x28;
        Scalar x51 = x10 * x50;
        Scalar x52 = 1.0 / x46;
        Scalar x53 = _hp1_ * x52;
        Scalar x54 = x53 * x7;
        Scalar x55 = x13 * x54;
        Scalar x56 = _hp2_ * x52;
        Scalar x57 = x56 * x7;
        Scalar x58 = x13 * x57;
        Scalar x59 = _hp1_ * x2;
        Scalar x60 = -_hp2_ * x1 + x59;
        Scalar x61 = -x60;
        Scalar x62 = x52 * x61;
        Scalar x63 = x62 * x7;
        Scalar x64 = x13 * x63;
        Scalar x65 = Scalar(pc1_ * x9);
        Scalar x66 = x12 * x65;
        Scalar x67 = Scalar(pc1_ * x26);
        Scalar x68 = 1.0 / x27;
        Scalar x69 = (1.0 / 2.0) * x68;
        Scalar x70 = x67 * x69;
        Scalar x71 = (_hp1_ * _hp1_);
        Scalar x72 = x71 + 1;
        Scalar x73 = x25 * x53;
        Scalar x74 = x52 * x8;
        Scalar x75 = x59 * x74;
        Scalar x76 = x17 * x75 + x7 * x73;
        Scalar x77 = x7 * x72 * x9 - x76;
        Scalar x78 = _hp1_ * _hp2_;
        Scalar x79 = x10 * x78;
        Scalar x80 = x25 * x56;
        Scalar x81 = x17 * x21;
        Scalar x82 = -x7 * x80 - x74 * x81;
        Scalar x83 = x19 + x79 + x82;
        Scalar x84 = x21 * x40;
        Scalar x85 = x40 * x59;
        Scalar x86 = _hp1_ * x3;
        Scalar x87 = _hp2_ * x4;
        Scalar x88 = x86 + x87;
        Scalar x89 = -x88;
        Scalar x90 = x17 * x62;
        Scalar x91 = x25 * x62;
        Scalar x92 = _hp1_ * x60;
        Scalar x93 = -x33;
        Scalar x94 = x92 + x93;
        Scalar x95 = x9 * x94;
        Scalar x96 = x2 * x40 * x89 + x2 * x8 * x90 + x29 + x7 * x91 + x7 * x95;
        Scalar x97 = x28 * x96;
        Scalar x98 = x28 * x9;
        Scalar x99 = x25 * x98;
        Scalar x100 = x18 * x2;
        Scalar x101 = Scalar(pc1_ * x69);
        Scalar x102 = x101 * x35;
        Scalar x103 = x30 * x8;
        Scalar x104 = x20 * x52;
        Scalar x105 = x103 * x104;
        Scalar x106 = x34 * x53;
        Scalar x107 = x106 * x7;
        Scalar x108 = -x105 - x107 + x32 + x79;
        Scalar x109 = (_hp2_ * _hp2_);
        Scalar x110 = x109 + 1;
        Scalar x111 = x34 * x56;
        Scalar x112 = _hp2_ * x1;
        Scalar x113 = x103 * x112;
        Scalar x114 = x111 * x7 + x113 * x52;
        Scalar x115 = x110 * x7 * x9 - x114;
        Scalar x116 = x112 * x40;
        Scalar x117 = x20 * x40;
        Scalar x118 = x88 * x9;
        Scalar x119 = x118 * x8;
        Scalar x120 = x30 * x62;
        Scalar x121 = x120 * x8;
        Scalar x122 = x34 * x62;
        Scalar x123 = _hp2_ * x60;
        Scalar x124 = x123 + x24;
        Scalar x125 = x124 * x9;
        Scalar x126 = x1 * x119 + x1 * x121 + x122 * x7 + x125 * x7 + x14;
        Scalar x127 = x126 * x28;
        Scalar x128 = x34 * x98;
        Scalar x129 = x28 * x31;
        Scalar x130 = x1 * x129;
        Scalar x131 = _hp1_ * x40;
        Scalar x132 = (1.0 / 4.0) * x36 + (1.0 / 4.0) * x37 + 1.0 / 4.0;
        Scalar x133 = Scalar(pc1_ * x132 * x68);
        Scalar x134 = x131 * x133;
        Scalar x135 = x71 * x74;
        Scalar x136 = x28 * x38;
        Scalar x137 = x135 * x136;
        Scalar x138 = x53 * x8;
        Scalar x139 = x38 * x43;
        Scalar x140 = x138 * x139;
        Scalar x141 = -x140;
        Scalar x142 = x28 * x40;
        Scalar x143 = x142 * x86;
        Scalar x144 = x142 * x15;
        Scalar x145 = Scalar(_hp1_ * pc1_ * x27 * x38 * x52 * x61 * x8 - x45);
        Scalar x146 = x38 * x9;
        Scalar x147 = x146 * x39;
        Scalar x148 = _hp2_ * x40;
        Scalar x149 = x133 * x148;
        Scalar x150 = x109 * x74;
        Scalar x151 = x136 * x150;
        Scalar x152 = -x151;
        Scalar x153 = x142 * x16;
        Scalar x154 = x142 * x87;
        Scalar x155 = x62 * x8;
        Scalar x156 = x139 * x155 + x42;
        Scalar x157 = x146 * x43;
        Scalar x158 = Scalar(pc0_ * x46);
        Scalar x159 = (Scalar(1.0) / (sqrt(x0) * x0 * x0));
        Scalar x160 = 2 * x159;
        Scalar x161 = Scalar((1.0 / 2.0) * pc1_ * x49 * x68 - x158 * x160);
        Scalar x162 = 2 * x48;
        Scalar x163 = _hp0_ * x162;
        Scalar x164 = x103 * x53;
        Scalar x165 = _hp1_ * x163 - x164;
        Scalar x166 = x103 * x56;
        Scalar x167 = _hp2_ * x163 - x166;
        Scalar x168 = 2 * x59;
        Scalar x169 = 2 * x112;
        Scalar x170 = x168 - x169;
        Scalar x171 = x170 * x48;
        Scalar x172 = x119 + x121;
        Scalar x173 = _hp0_ * x171 + x172;
        Scalar x174 = x173 * x28;
        Scalar x175 = LM0 * x55;
        Scalar x176 = LM3 * x137 + x175;
        Scalar x177 = LM0 * x58;
        Scalar x178 = LM4 * x151 + x177;
        Scalar x179 = LM2 * x28;
        Scalar x180 = LM1 * x28;
        Scalar x181 = LM5 * x44 + x116 * x179 - x180 * x84;
        Scalar x182 = LM5 * x41;
        Scalar x183 = x180 * x85;
        Scalar x184 = x117 * x179;
        Scalar x185 = LM1 * x43;
        Scalar x186 = LM2 * x39;
        Scalar x187 = x36 + x37 + 1;
        Scalar x188 = LM3 * x187;
        Scalar x189 = 1.0 / x11;
        Scalar x190 = Scalar((1.0 / 8.0) * pc1_ * x189);
        Scalar x191 = (1.0 / 4.0) * x189;
        Scalar x192 = Scalar(pc1_ * x191);
        Scalar x193 = 4 * _hp1_;
        Scalar x194 = Scalar(_hp0_ * pc0_);
        Scalar x195 = x159 * x194;
        Scalar x196 = x193 * x195;
        Scalar x197 = x39 * x52;
        Scalar x198 = 3 * LM0;
        Scalar x199 = x198 * x7;
        Scalar x200 = LM3 * x135;
        Scalar x201 = LM4 * _hp2_;
        Scalar x202 = x133 * x138;
        Scalar x203 =
            Scalar(-1.0 / 2.0 * LM1 * pc1_ * x68 * x77 - 1.0 / 2.0 * LM2 * pc1_ * x108 * x68 +
                   x133 * x200 + x197 * x199 + x201 * x202);
        Scalar x204 = 4 * _hp2_;
        Scalar x205 = x195 * x204;
        Scalar x206 = x43 * x52;
        Scalar x207 = LM4 * x150;
        Scalar x208 =
            Scalar(-1.0 / 2.0 * LM1 * pc1_ * x68 * x83 - 1.0 / 2.0 * LM2 * pc1_ * x115 * x68 +
                   LM3 * _hp2_ * x202 + x133 * x207 + x199 * x206);
        Scalar x209 = LM5 * x101;
        Scalar x210 = LM1 * x101;
        Scalar x211 = LM2 * x101;
        Scalar x212 = x101 * x40;
        Scalar x213 = LM3 * x212;
        Scalar x214 = LM4 * x212;
        Scalar x215 = x116 * x211 + x148 * x209 + x16 * x214 - x210 * x84 + x213 * x86;
        Scalar x216 = -x117 * x211 - x131 * x209 + x15 * x213 + x210 * x85 + x214 * x87;
        Scalar x217 = x160 * x170 * x194;
        Scalar x218 = x138 * x61;
        Scalar x219 = x56 * x8;
        Scalar x220 = x219 * x61;
        Scalar x221 = x133 * x220;
        Scalar x222 = LM0 * x50 * x63 + x126 * x211 + x210 * x96;
        Scalar x223 = -_hp1_ * x211 + _hp2_ * x210;
        Scalar x224 = x65 * x69;
        Scalar x225 = LM1 * x224 * x25 + LM2 * x224 * x34 + x198 * x98;
        Scalar x226 = x132 * x65 * x68;
        Scalar x227 = LM3 * _hp1_ * x226 + x1 * x211 * x31 + x100 * x210 + x201 * x226 + x209 * x31;
        Scalar x228 = (Scalar(1.0) / (_hp0_ * _hp0_ * _hp0_));
        Scalar x229 = Scalar(LM0 * pc1_ * x11 * x228 * x7);
        Scalar x230 = 4 * x229;
        Scalar x231 = x228 * x8;
        Scalar x232 = x231 * x28;
        Scalar x233 = x187 * x43;
        Scalar x234 = x231 * x233;
        Scalar x235 = 2 * x71;
        Scalar x236 = x228 * x235;
        Scalar x237 = LM5 * x28;
        Scalar x238 = x17 * x2;
        Scalar x239 = x25 * x7;
        Scalar x240 = x228 * x239;
        Scalar x241 = x57 * x71;
        Scalar x242 = LM3 * x71;
        Scalar x243 = LM4 * x109;
        Scalar x244 = x231 * x39;
        Scalar x245 = 2 * x228;
        Scalar x246 = x103 * x245;
        Scalar x247 = x109 * x54;
        Scalar x248 = x179 * (2 * _hp1_ * _hp2_ * x1 * x228 * x30 * x8 +
                              2 * _hp1_ * _hp2_ * x228 * x34 * x7 - x110 * x54 - x166 - x247) +
                      x180 * (2 * _hp1_ * _hp2_ * x17 * x2 * x228 * x8 +
                              2 * _hp1_ * _hp2_ * x228 * x25 * x7 - x138 * x17 - x241 - x57 * x72) +
                      x187 * x243 * x244 + x230 * x78 + x234 * x242 +
                      x237 * (x162 * x78 + x246 * x78);
        Scalar x249 = x200 * x28;
        Scalar x250 = LM4 * x74;
        Scalar x251 = x16 * x39;
        Scalar x252 = LM5 * x43;
        Scalar x253 = x138 * x252;
        Scalar x254 = LM1 * x39;
        Scalar x255 = x21 * x74;
        Scalar x256 = x253 - x254 * x255;
        Scalar x257 = x249 * x3 + x250 * x251 + x256;
        Scalar x258 = x15 * x43;
        Scalar x259 =
            Scalar(-LM5 * pc1_ * x27 * x52 * x71 * x8 + x135 * x180 * x2 + x249 * x4 + x250 * x258);
        Scalar x260 = -x170;
        Scalar x261 = _hp1_ * x260;
        Scalar x262 = x231 * x260;
        Scalar x263 = x17 * x59;
        Scalar x264 = 2 * x79;
        Scalar x265 = x264 - x52 * x61 * x7 * x72 + x54 * x94 + x75 * x89 + x82;
        Scalar x266 = x10 * x109;
        Scalar x267 = x34 * x7;
        Scalar x268 = x228 * x261;
        Scalar x269 = x228 * x260;
        Scalar x270 = _hp2_ * x61;
        Scalar x271 = x74 * x88;
        Scalar x272 = x114 - x124 * x54 + x172 - x20 * x271 + x270 * x54;
        Scalar x273 = x138 * x88 + x167;
        Scalar x274 = LM0 * x13;
        Scalar x275 = x274 * x7;
        Scalar x276 = x136 * x262;
        Scalar x277 = x139 * x268 * x8;
        Scalar x278 = x274 * x53;
        Scalar x279 = x78 * x9;
        Scalar x280 = x104 * x30;
        Scalar x281 = x136 * x52;
        Scalar x282 = LM5 * x30;
        Scalar x283 = x139 * x53;
        Scalar x284 = LM4 * x283 + x180 * x263 * x52 + x197 * x282 + x242 * x281;
        Scalar x285 = x187 * x232;
        Scalar x286 = 2 * x109 * x228;
        Scalar x287 = x103 * x286;
        Scalar x288 = 2 * x15 - 2 * x16;
        Scalar x289 = x207 * x28;
        Scalar x290 = LM3 * x74;
        Scalar x291 = x1 * x150 * x179 + x150 * x237 + x251 * x290 + x289 * x3;
        Scalar x292 = LM2 * x43;
        Scalar x293 = x20 * x292 * x74;
        Scalar x294 = -x258 * x290 - x289 * x4 + x293;
        Scalar x295 = _hp2_ * x260;
        Scalar x296 = -_hp1_ * _hp2_ * x52 * x61 * x7 - x17 * x52 * x61 * x8 + x255 * x89 +
                      x57 * x94 + x76 - x8 * x89 * x9;
        Scalar x297 = x228 * x295;
        Scalar x298 = x105 + x107 - x110 * x52 * x61 * x7 + x112 * x271 + x124 * x57 - x264;
        Scalar x299 = Scalar(-2 * _hp0_ * _hp1_ * mu_ * x47 + x164 + x219 * x88);
        Scalar x300 = x138 * x233;
        Scalar x301 = x274 * x56;
        Scalar x302 = x52 * x81;
        Scalar x303 = LM3 * x283 + x112 * x179 * x30 * x52 + x206 * x282 + x243 * x281;
        Scalar x304 = LM3 * x41 + LM4 * x44;
        Scalar x305 = x112 * x155;
        Scalar x306 = x155 * x28;
        Scalar x307 = x16 * x306;
        Scalar x308 = x155 * x21;
        Scalar x309 = LM5 * x9;
        Scalar x310 = LM2 * x98;
        Scalar x311 = LM3 * x98;
        Scalar x312 = LM4 * x98;
        Scalar x313 = LM1 * x98;
        Scalar x314 = x112 * x310 + x16 * x312 - x21 * x313 + x309 * x43 + x311 * x86;
        Scalar x315 = x155 * x39;
        Scalar x316 = x306 * x87;
        Scalar x317 = x155 * x20;
        Scalar x318 = x15 * x311 - x20 * x310 - x309 * x39 + x312 * x87 + x313 * x59;
        Scalar x319 = x229 * x61;
        Scalar x320 = x285 * x61;
        Scalar x321 = _hp1_ * x61;
        Scalar x322 = -x137 - x152 - x234 * x321;
        Scalar x323 = 2 * x240;
        Scalar x324 = x17 * x231;
        Scalar x325 = -x109 + x71;
        Scalar x326 = x245 * x267;
        Scalar x327 = 2 * x20;
        Scalar x328 = x103 * x228;
        Scalar x329 = 2 * x21;
        Scalar x330 = x22 * x52;
        Scalar x331 = x260 * x61;
        Scalar x332 = x228 * x331;
        Scalar x333 = x22 * x74;
        Scalar x334 = x231 * x331;
        Scalar x335 = x103 * x330;
        Scalar x336 = 2 * x155;
        Scalar x337 = x336 * x88;
        Scalar x338 = x103 * x332;
        Scalar x339 = 2 * x63;
        Scalar x340 = -x22;
        Scalar x341 = x2 * x89;
        Scalar x342 = x254 + x292;
        Scalar x343 = x274 * x62;
        Scalar x344 = x1 * x118;
        Scalar x345 = x1 * x120;
        Scalar x346 = x341 * x9;
        Scalar x347 = x2 * x90;
        Scalar x348 = x38 * x62;
        Scalar x349 = x348 * x43;
        Scalar x350 = x25 * x52;
        Scalar x351 = x34 * x52;

        _fx_[0] = x10 * x13;
        _fx_[1] = x26 * x28;
        _fx_[2] = x28 * x35;
        _fx_[3] = x42;
        _fx_[4] = x45;
        _fx_[5] = x28 * x49;

        _jx_(0, 0) = x51;
        _jx_(1, 0) = x70;
        _jx_(2, 0) = x102;
        _jx_(3, 0) = x134;
        _jx_(4, 0) = x149;
        _jx_(5, 0) = x161;
        _jx_(0, 1) = -x55;
        _jx_(1, 1) = x28 * x77;
        _jx_(2, 1) = x108 * x28;
        _jx_(3, 1) = -x137;
        _jx_(4, 1) = x141;
        _jx_(5, 1) = x165 * x28;
        _jx_(0, 2) = -x58;
        _jx_(1, 2) = x28 * x83;
        _jx_(2, 2) = x115 * x28;
        _jx_(3, 2) = x141;
        _jx_(4, 2) = x152;
        _jx_(5, 2) = x167 * x28;
        _jx_(0, 3) = 0;
        _jx_(1, 3) = -x28 * x84;
        _jx_(2, 3) = x116 * x28;
        _jx_(3, 3) = x143;
        _jx_(4, 3) = x153;
        _jx_(5, 3) = x44;
        _jx_(0, 4) = 0;
        _jx_(1, 4) = x28 * x85;
        _jx_(2, 4) = -x117 * x28;
        _jx_(3, 4) = x144;
        _jx_(4, 4) = x154;
        _jx_(5, 4) = -x41;
        _jx_(0, 5) = x64;
        _jx_(1, 5) = x97;
        _jx_(2, 5) = x127;
        _jx_(3, 5) = x145;
        _jx_(4, 5) = x156;
        _jx_(5, 5) = x174;
        _jx_(0, 6) = 0;
        _jx_(1, 6) = x43;
        _jx_(2, 6) = -x39;
        _jx_(3, 6) = 0;
        _jx_(4, 6) = 0;
        _jx_(5, 6) = 0;
        _jx_(0, 7) = x66;
        _jx_(1, 7) = x99;
        _jx_(2, 7) = x128;
        _jx_(3, 7) = 0;
        _jx_(4, 7) = 0;
        _jx_(5, 7) = 0;
        _jx_(0, 8) = 0;
        _jx_(1, 8) = x100 * x28;
        _jx_(2, 8) = x130;
        _jx_(3, 8) = x147;
        _jx_(4, 8) = x157;
        _jx_(5, 8) = x129;

        _gx_[0] = LM0 * x51 + LM1 * x70 + LM2 * x102 + LM3 * x134 + LM4 * x149 + LM5 * x161;
        _gx_[1] = Scalar(LM1 * pc1_ * x27 * x77 + LM2 * pc1_ * x108 * x27 - LM4 * x140 +
                         LM5 * pc1_ * x165 * x27 - x176);
        _gx_[2] = Scalar(LM1 * pc1_ * x27 * x83 + LM2 * pc1_ * x115 * x27 - LM3 * x140 +
                         LM5 * pc1_ * x167 * x27 - x178);
        _gx_[3] = LM3 * x143 + LM4 * x153 + x181;
        _gx_[4] = LM3 * x144 + LM4 * x154 - x182 + x183 - x184;
        _gx_[5] = LM0 * x64 + LM1 * x97 + LM2 * x127 + LM3 * x145 + LM4 * x156 + LM5 * x174;
        _gx_[6] = x185 - x186;
        _gx_[7] = LM0 * x66 + LM1 * x99 + LM2 * x128;
        _gx_[8] = LM2 * x130 + LM3 * x147 + LM4 * x157 + LM5 * x129 + x100 * x180;

        _hx_(0, 0) =
            Scalar((3.0 / 2.0) * LM0 * pc1_ * x68 * x7 * x9 - LM1 * x191 * x67 - LM2 * x192 * x35 -
                   LM4 * x148 * x187 * x190 +
                   LM5 * (-x192 * x49 + 4 * x158 / (sqrt(x0) * x0 * x0 * x0)) - x131 * x188 * x190);
        _hx_(0, 1) = Scalar(LM5 * ((1.0 / 2.0) * pc1_ * x165 * x68 - x196) - x203);
        _hx_(1, 1) = LM4 * x234 * x71 + (_hp1_ * _hp1_ * _hp1_) * x188 * x232 +
                     x179 * (2 * x1 * x228 * x30 * x71 * x8 - 2 * x164 + 2 * x228 * x34 * x7 * x71 -
                             2 * x241) +
                     x180 * (x235 * x240 + x236 * x238 * x8 - 2 * x54 * x72) + x230 * x71 +
                     x237 * (x103 * x236 + x162 * x71);
        _hx_(0, 2) = Scalar(LM5 * ((1.0 / 2.0) * pc1_ * x167 * x68 - x205) - x208);
        _hx_(1, 2) = x248;
        _hx_(2, 2) = LM4 * (_hp2_ * _hp2_ * _hp2_) * x285 + x109 * x188 * x244 + x109 * x230 +
                     x179 * (x1 * x287 - 2 * x110 * x57 + x267 * x286) +
                     x180 * (x109 * x2 * x228 * x288 * x8 + 2 * x109 * x228 * x25 * x7 -
                             x219 * x288 - 2 * x247) +
                     x237 * (x109 * x162 + x287);
        _hx_(0, 3) = x215;
        _hx_(1, 3) = Scalar(LM2 * pc1_ * x27 * (x148 - x20 * x219) - x257);
        _hx_(2, 3) = Scalar(LM1 * pc1_ * x27 * (x109 * x2 * x52 * x8 - x148) - x291);
        _hx_(3, 3) = x304;
        _hx_(0, 4) = x216;
        _hx_(1, 4) = Scalar(LM2 * pc1_ * x27 * (x1 * x52 * x71 * x8 - x131) - x259);
        _hx_(2, 4) = x180 * (x131 - x138 * x21) + x253 + x294;
        _hx_(3, 4) = 0;
        _hx_(4, 4) = x304;
        _hx_(0, 5) = Scalar(LM3 * x133 * x218 - LM3 * x149 + LM4 * x134 + LM4 * x221 +
                            LM5 * ((1.0 / 2.0) * pc1_ * x173 * x68 - x217) + x222);
        _hx_(1, 5) = Scalar(-LM4 * x137 - LM4 * x277 + x138 * x188 * x43 + x178 +
                            x179 * (x10 * x71 - x103 * x20 * x269 - x266 - x267 * x268 + x272) +
                            x180 * (-x240 * x261 - x262 * x263 - x265) +
                            x237 * (2 * _hp1_ * mu_ * x47 * x60 - x103 * x268 - x273) -
                            x242 * x276 - x268 * x275);
        _hx_(2, 5) = Scalar(
            LM1 * pc1_ * x27 * (-x240 * x295 - x262 * x81 - x266 - x296 + x7 * x71 * x9) +
            LM2 * pc1_ * x27 * (-x113 * x269 - x267 * x297 - x298) +
            (1.0 / 2.0) * LM3 * pc1_ * x109 * x187 * x27 * x52 * x8 - LM3 * x277 - LM4 * x300 +
            LM5 * pc1_ * x27 * (2 * _hp2_ * mu_ * x47 * x60 - x103 * x297 - x299) - x176 -
            x243 * x276 - x275 * x297);
        _hx_(3, 5) = -LM3 * x153 + LM3 * x306 * x86 + LM4 * x143 + LM4 * x307 + x155 * x252 +
                     x179 * x305 - x180 * x308 + x182 - x183 + x184;
        _hx_(4, 5) = LM3 * x15 * x306 - LM3 * x154 + LM4 * x144 + LM4 * x316 - LM5 * x315 +
                     x155 * x180 * x59 - x179 * x317 + x181;
        _hx_(5, 5) =
            Scalar(LM3 * (_hp1_ * pc1_ * x22 * x27 * x38 * x52 * x8 +
                          _hp1_ * pc1_ * x228 * x260 * x27 * x38 * x61 * x8 - x155 * x233 - x42) +
                   LM4 * (x139 * x333 + x139 * x334 + x187 * x315 - x45) +
                   x179 * (x1 * x19 + x1 * x335 + x1 * x337 + x1 * x338 +
                           x10 * (_hp2_ * x340 + 2 * x92 + x93) + x124 * x339 + x267 * x330 +
                           x267 * x332 + x29) +
                   x180 * (x10 * (_hp1_ * x340 - 2 * x123 - x24) - x14 + x2 * x32 + x238 * x333 +
                           x238 * x334 + x239 * x330 + x240 * x331 + x336 * x341 + x339 * x94) +
                   x237 * (_hp0_ * x48 * (-x327 - x329) + x171 * x60 + x19 + x335 + x337 + x338) +
                   x275 * x330 + x275 * x332);
        _hx_(0, 6) = x223;
        _hx_(1, 6) = 0;
        _hx_(2, 6) = 0;
        _hx_(3, 6) = 0;
        _hx_(4, 6) = 0;
        _hx_(5, 6) = x342;
        _hx_(6, 6) = 0;
        _hx_(0, 7) = x225;
        _hx_(1, 7) = x179 * (-x106 + x279) + x180 * (x72 * x9 - x73) - x278;
        _hx_(2, 7) = x179 * (x110 * x9 - x111) + x180 * (x279 - x80) - x301;
        _hx_(3, 7) = 0;
        _hx_(4, 7) = 0;
        _hx_(5, 7) = x179 * (x122 + x125) + x180 * (x91 + x95) + x343;
        _hx_(6, 7) = 0;
        _hx_(7, 7) = 0;
        _hx_(0, 8) = x227;
        _hx_(1, 8) = Scalar(LM2 * pc1_ * x27 * (-x280 + x31) - x284);
        _hx_(2, 8) = Scalar(LM1 * pc1_ * x27 * (x18 - x302) - x303);
        _hx_(3, 8) = x314;
        _hx_(4, 8) = x318;
        _hx_(5, 8) =
            Scalar(LM3 * (_hp1_ * pc1_ * x27 * x38 * x52 * x61 - x157) + LM4 * (x147 + x349) +
                   x179 * (x344 + x345) + x180 * (x346 + x347) + x237 * (x118 + x120));
        _hx_(6, 8) = 0;
        _hx_(7, 8) = 0;
        _hx_(8, 8) = 0;

        _hx_(1, 0) = _hx_(0, 1);
        _hx_(2, 0) = _hx_(0, 2);
        _hx_(3, 0) = _hx_(0, 3);
        _hx_(4, 0) = _hx_(0, 4);
        _hx_(5, 0) = _hx_(0, 5);
        _hx_(6, 0) = _hx_(0, 6);
        _hx_(7, 0) = _hx_(0, 7);
        _hx_(8, 0) = _hx_(0, 8);
        _hx_(2, 1) = _hx_(1, 2);
        _hx_(3, 1) = _hx_(1, 3);
        _hx_(4, 1) = _hx_(1, 4);
        _hx_(5, 1) = _hx_(1, 5);
        _hx_(6, 1) = _hx_(1, 6);
        _hx_(7, 1) = _hx_(1, 7);
        _hx_(8, 1) = _hx_(1, 8);
        _hx_(3, 2) = _hx_(2, 3);
        _hx_(4, 2) = _hx_(2, 4);
        _hx_(5, 2) = _hx_(2, 5);
        _hx_(6, 2) = _hx_(2, 6);
        _hx_(7, 2) = _hx_(2, 7);
        _hx_(8, 2) = _hx_(2, 8);
        _hx_(4, 3) = _hx_(3, 4);
        _hx_(5, 3) = _hx_(3, 5);
        _hx_(6, 3) = _hx_(3, 6);
        _hx_(7, 3) = _hx_(3, 7);
        _hx_(8, 3) = _hx_(3, 8);
        _hx_(5, 4) = _hx_(4, 5);
        _hx_(6, 4) = _hx_(4, 6);
        _hx_(7, 4) = _hx_(4, 7);
        _hx_(8, 4) = _hx_(4, 8);
        _hx_(6, 5) = _hx_(5, 6);
        _hx_(7, 5) = _hx_(5, 7);
        _hx_(8, 5) = _hx_(5, 8);
        _hx_(7, 6) = _hx_(6, 7);
        _hx_(8, 6) = _hx_(6, 8);
        _hx_(8, 7) = _hx_(7, 8);
    }
};

} // namespace tycho::astro
