// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_mee_dynamics.py — do not edit manually.
// =============================================================================
#pragma once

#include <limits>
#include <stdexcept>

#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

class MEEDynamics
    : public VectorFunction<MEEDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic> {
    public:
    using Base = VectorFunction<MEEDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);
    static constexpr bool is_vectorizable = true;

    private:
    double mu_ = std::numeric_limits<double>::quiet_NaN(); // Gravitational Parameter

    // Precomputed from constructor parameters
    double pc0_ = std::numeric_limits<double>::quiet_NaN();
    double pc1_ = std::numeric_limits<double>::quiet_NaN();
    double pc2_ = std::numeric_limits<double>::quiet_NaN();

    void recompute_cache_() {
        pc0_ = (1.0/(std::sqrt(mu_)));
        pc1_ = 2*pc0_;
        pc2_ = 4*pc0_;
    }

    public:
    MEEDynamics() : MEEDynamics(1.0) {}

    MEEDynamics(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument(
                "MEEDynamics: mu must satisfy mu > 0.0");
        this->set_io_rows(9, 6);
        mu_ = mu;
        this->recompute_cache_();
    }

    void set_mu(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument(
                "MEEDynamics: mu must satisfy mu > 0.0");
        mu_ = mu;
        this->recompute_cache_();
    }

    [[nodiscard]] double mu() const noexcept { return mu_; }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = x1*cos(x5) + x2*sin(x5) + 1;
        Scalar x9 = 1.0/_hp0_;
        Scalar x10 = x7*x9;
        Scalar x11 = sin(x5);
        Scalar x12 = cos(x5);
        Scalar x13 = x8*x9;
        Scalar x14 = x13*(x11*x3 - x12*x4);
        Scalar x15 = x1*x12 + x11*x2 + 2;
        Scalar x16 = Scalar(pc0_*sqrt(x0));
        Scalar x17 = x13*x16*((1.0/2.0)*(x3*x3) + (1.0/2.0)*(x4*x4) + 1.0/2.0);
        
        _fx_[0] = Scalar(pc1_*(sqrt(x0)*x0)*x10);
        _fx_[1] = x16*(x10*(x1 + x12*x15) + x11*x6 - x14*x2);
        _fx_[2] = x16*(x1*x14 + x10*(x11*x15 + x2) - x12*x6);
        _fx_[3] = x12*x17;
        _fx_[4] = x11*x17;
        _fx_[5] = Scalar(x16*((_hp0_*_hp0_)*mu_/(x0*x0) + x14));
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_,
                         CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = x1*cos(x5) + x2*sin(x5) + 1;
        Scalar _hp1_ = cos(x5);
        Scalar _hp2_ = sin(x5);
        Scalar x9 = 1.0/_hp0_;
        Scalar x10 = x7*x9;
        Scalar x11 = Scalar(pc1_*(sqrt(x0)*x0));
        Scalar x12 = _hp2_*x6;
        Scalar x13 = _hp1_*x4;
        Scalar x14 = _hp2_*x3 - x13;
        Scalar x15 = x8*x9;
        Scalar x16 = x14*x15;
        Scalar x17 = _hp1_*x1;
        Scalar x18 = _hp2_*x2;
        Scalar x19 = x17 + x18 + 2;
        Scalar x20 = _hp1_*x19;
        Scalar x21 = x1 + x20;
        Scalar x22 = x10*x21 + x12 - x16*x2;
        Scalar x23 = sqrt(x0);
        Scalar x24 = Scalar(pc0_*x23);
        Scalar x25 = _hp1_*x6;
        Scalar x26 = _hp2_*x19;
        Scalar x27 = x2 + x26;
        Scalar x28 = x1*x16 + x10*x27 - x25;
        Scalar x29 = (x3*x3);
        Scalar x30 = (x4*x4);
        Scalar x31 = (1.0/2.0)*x29 + (1.0/2.0)*x30 + 1.0/2.0;
        Scalar x32 = _hp1_*x24;
        Scalar x33 = x15*x32;
        Scalar x34 = x31*x33;
        Scalar x35 = _hp2_*x24;
        Scalar x36 = x15*x35;
        Scalar x37 = x31*x36;
        Scalar x38 = (Scalar(1.0)/(x0*x0));
        Scalar x39 = (_hp0_*_hp0_);
        Scalar x40 = Scalar(mu_*x39);
        Scalar x41 = x16 + x38*x40;
        Scalar x42 = 1.0/x39;
        Scalar x43 = x42*x7;
        Scalar x44 = x11*x43;
        Scalar x45 = _hp1_*x2;
        Scalar x46 = -_hp2_*x1 + x45;
        Scalar x47 = -x46;
        Scalar x48 = 1.0/x23;
        Scalar x49 = Scalar(pc0_*x48);
        Scalar x50 = (1.0/2.0)*x49;
        Scalar x51 = (_hp1_*_hp1_);
        Scalar x52 = x42*x8;
        Scalar x53 = x14*x52;
        Scalar x54 = x21*x43;
        Scalar x55 = _hp1_*_hp2_*x10;
        Scalar x56 = x15*x24;
        Scalar x57 = _hp1_*x3;
        Scalar x58 = _hp2_*x4;
        Scalar x59 = x15*(x57 + x58);
        Scalar x60 = x47*x53;
        Scalar x61 = x24*x9;
        Scalar x62 = x14*x61;
        Scalar x63 = x27*x43;
        Scalar x64 = (_hp2_*_hp2_);
        Scalar x65 = _hp2_*x1;
        Scalar x66 = (1.0/4.0)*x15*x49*(x29 + x30 + 1);
        Scalar x67 = x31*x52;
        Scalar x68 = x24*x67;
        Scalar x69 = x35*x67;
        Scalar x70 = -_hp1_*x69;
        Scalar x71 = x31*x9;
        Scalar x72 = Scalar(_hp0_*mu_*x38);
        Scalar x73 = 2*x72;
        
        _fx_[0] = x10*x11;
        _fx_[1] = x22*x24;
        _fx_[2] = x24*x28;
        _fx_[3] = x34;
        _fx_[4] = x37;
        _fx_[5] = x24*x41;
        
        _jx_(0,0) = 3*x10*x24;
        _jx_(1,0) = x22*x50;
        _jx_(2,0) = x28*x50;
        _jx_(3,0) = _hp1_*x66;
        _jx_(4,0) = _hp2_*x66;
        _jx_(5,0) = Scalar((1.0/2.0)*pc0_*x41*x48 - pc1_*x40/(sqrt(x0)*x0*x0));
        _jx_(0,1) = -_hp1_*x44;
        _jx_(1,1) = x24*(-_hp1_*x54 + x10*(x51 + 1) + x45*x53);
        _jx_(2,1) = x24*(-_hp1_*x63 + x16 - x17*x53 + x55);
        _jx_(3,1) = -x51*x68;
        _jx_(4,1) = x70;
        _jx_(5,1) = x24*(-_hp1_*x53 + _hp1_*x73);
        _jx_(0,2) = -_hp2_*x44;
        _jx_(1,2) = x24*(-_hp2_*x54 - x16 + x18*x53 + x55);
        _jx_(2,2) = x24*(-_hp2_*x63 - x53*x65 + x7*x9*(x64 + 1));
        _jx_(3,2) = x70;
        _jx_(4,2) = -x64*x68;
        _jx_(5,2) = x24*(-_hp2_*x53 + _hp2_*x73);
        _jx_(0,3) = 0;
        _jx_(1,3) = -x18*x56;
        _jx_(2,3) = x56*x65;
        _jx_(3,3) = x56*x57;
        _jx_(4,3) = _hp2_*x3*x56;
        _jx_(5,3) = x36;
        _jx_(0,4) = 0;
        _jx_(1,4) = x45*x56;
        _jx_(2,4) = -x17*x56;
        _jx_(3,4) = x13*x56;
        _jx_(4,4) = x56*x58;
        _jx_(5,4) = -x33;
        _jx_(0,5) = x44*x47;
        _jx_(1,5) = x24*(x10*(_hp1_*x46 - x26) - x2*x59 - x2*x60 + x25 + x47*x54);
        _jx_(2,5) = x24*(x1*x59 + x1*x60 + x10*(_hp2_*x46 + x20) + x12 + x47*x63);
        _jx_(3,5) = Scalar(_hp1_*pc0_*x23*x31*x42*x47*x8 - x37);
        _jx_(4,5) = x34 + x47*x69;
        _jx_(5,5) = x24*(x59 + x60 + x72*(2*x45 - 2*x65));
        _jx_(0,6) = 0;
        _jx_(1,6) = x35;
        _jx_(2,6) = -x32;
        _jx_(3,6) = 0;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = x11*x9;
        _jx_(1,7) = x21*x61;
        _jx_(2,7) = x27*x61;
        _jx_(3,7) = 0;
        _jx_(4,7) = 0;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = -x2*x62;
        _jx_(2,8) = x1*x62;
        _jx_(3,8) = x32*x71;
        _jx_(4,8) = x35*x71;
        _jx_(5,8) = x62;
    }

    template <class InType, class OutType, class JacType,
                 class AdjGradType, class AdjHessType,
                 class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_,
        CVecRef<OutType> fx_,
        CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_,
        CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar _hp0_ = x1*cos(x5) + x2*sin(x5) + 1;
        Scalar _hp1_ = cos(x5);
        Scalar _hp2_ = sin(x5);
        Scalar x9 = 1.0/_hp0_;
        Scalar x10 = x7*x9;
        Scalar x11 = (sqrt(x0)*x0);
        Scalar x12 = Scalar(pc1_*x11);
        Scalar x13 = _hp2_*x6;
        Scalar x14 = _hp1_*x4;
        Scalar x15 = _hp2_*x3 - x14;
        Scalar x16 = x15*x9;
        Scalar x17 = x16*x8;
        Scalar x18 = x17*x2;
        Scalar x19 = _hp1_*x1;
        Scalar x20 = _hp2_*x2;
        Scalar x21 = x19 + x20;
        Scalar x22 = x21 + 2;
        Scalar x23 = _hp1_*x22;
        Scalar x24 = x1 + x23;
        Scalar x25 = x10*x24 + x13 - x18;
        Scalar x26 = sqrt(x0);
        Scalar x27 = Scalar(pc0_*x26);
        Scalar x28 = _hp1_*x6;
        Scalar x29 = x1*x17;
        Scalar x30 = _hp2_*x22;
        Scalar x31 = x2 + x30;
        Scalar x32 = x10*x31 - x28 + x29;
        Scalar x33 = (x3*x3);
        Scalar x34 = (x4*x4);
        Scalar x35 = (1.0/2.0)*x33 + (1.0/2.0)*x34 + 1.0/2.0;
        Scalar x36 = _hp1_*x27;
        Scalar x37 = x8*x9;
        Scalar x38 = x36*x37;
        Scalar x39 = x35*x38;
        Scalar x40 = _hp2_*x27;
        Scalar x41 = x37*x40;
        Scalar x42 = x35*x41;
        Scalar x43 = (Scalar(1.0)/(x0*x0));
        Scalar x44 = (_hp0_*_hp0_);
        Scalar x45 = Scalar(mu_*x44);
        Scalar x46 = x17 + x43*x45;
        Scalar x47 = 3*x27;
        Scalar x48 = x10*x47;
        Scalar x49 = 1.0/x44;
        Scalar x50 = _hp1_*x49;
        Scalar x51 = x50*x7;
        Scalar x52 = x12*x51;
        Scalar x53 = _hp2_*x49;
        Scalar x54 = x53*x7;
        Scalar x55 = x12*x54;
        Scalar x56 = _hp1_*x2;
        Scalar x57 = -_hp2_*x1 + x56;
        Scalar x58 = -x57;
        Scalar x59 = x49*x58;
        Scalar x60 = x59*x7;
        Scalar x61 = x12*x60;
        Scalar x62 = x12*x9;
        Scalar x63 = Scalar(pc0_*x25);
        Scalar x64 = 1.0/x26;
        Scalar x65 = (1.0/2.0)*x64;
        Scalar x66 = x63*x65;
        Scalar x67 = (_hp1_*_hp1_);
        Scalar x68 = x67 + 1;
        Scalar x69 = x68*x9;
        Scalar x70 = x24*x50;
        Scalar x71 = x7*x70;
        Scalar x72 = x15*x8;
        Scalar x73 = x49*x72;
        Scalar x74 = x56*x73 - x71;
        Scalar x75 = x69*x7 + x74;
        Scalar x76 = -x17;
        Scalar x77 = _hp1_*_hp2_;
        Scalar x78 = x10*x77;
        Scalar x79 = x24*x53;
        Scalar x80 = x20*x73 - x7*x79;
        Scalar x81 = x76 + x78 + x80;
        Scalar x82 = x20*x37;
        Scalar x83 = x37*x56;
        Scalar x84 = _hp1_*x3;
        Scalar x85 = _hp2_*x4;
        Scalar x86 = x84 + x85;
        Scalar x87 = x86*x9;
        Scalar x88 = x8*x87;
        Scalar x89 = x15*x59;
        Scalar x90 = x8*x89;
        Scalar x91 = x24*x59;
        Scalar x92 = _hp1_*x57;
        Scalar x93 = -x30;
        Scalar x94 = x92 + x93;
        Scalar x95 = x9*x94;
        Scalar x96 = -x2*x88 - x2*x90 + x28 + x7*x91 + x7*x95;
        Scalar x97 = x27*x96;
        Scalar x98 = x27*x9;
        Scalar x99 = x24*x98;
        Scalar x100 = x16*x27;
        Scalar x101 = x100*x2;
        Scalar x102 = Scalar(pc0_*x65);
        Scalar x103 = x102*x32;
        Scalar x104 = x19*x73;
        Scalar x105 = x31*x50;
        Scalar x106 = x105*x7;
        Scalar x107 = -x104 - x106 + x17 + x78;
        Scalar x108 = (_hp2_*_hp2_);
        Scalar x109 = x108 + 1;
        Scalar x110 = x31*x53;
        Scalar x111 = _hp2_*x1;
        Scalar x112 = x110*x7 + x111*x73;
        Scalar x113 = x109*x7*x9 - x112;
        Scalar x114 = x111*x37;
        Scalar x115 = x19*x37;
        Scalar x116 = x31*x59;
        Scalar x117 = _hp2_*x57;
        Scalar x118 = x117 + x23;
        Scalar x119 = x118*x9;
        Scalar x120 = x1*x88 + x1*x90 + x116*x7 + x119*x7 + x13;
        Scalar x121 = x120*x27;
        Scalar x122 = x31*x98;
        Scalar x123 = x1*x100;
        Scalar x124 = x33 + x34 + 1;
        Scalar x125 = _hp1_*x37;
        Scalar x126 = x124*x125;
        Scalar x127 = Scalar((1.0/4.0)*pc0_*x64);
        Scalar x128 = x126*x127;
        Scalar x129 = x27*x35;
        Scalar x130 = x49*x8;
        Scalar x131 = x130*x67;
        Scalar x132 = x129*x131;
        Scalar x133 = x35*x40;
        Scalar x134 = x50*x8;
        Scalar x135 = x133*x134;
        Scalar x136 = -x135;
        Scalar x137 = x27*x37;
        Scalar x138 = x137*x84;
        Scalar x139 = x137*x14;
        Scalar x140 = Scalar(_hp1_*pc0_*x26*x35*x49*x58*x8 - x42);
        Scalar x141 = x35*x9;
        Scalar x142 = x141*x36;
        Scalar x143 = _hp2_*x37;
        Scalar x144 = x124*x127;
        Scalar x145 = x143*x144;
        Scalar x146 = x108*x130;
        Scalar x147 = x129*x146;
        Scalar x148 = -x147;
        Scalar x149 = _hp2_*x3;
        Scalar x150 = x137*x149;
        Scalar x151 = x137*x85;
        Scalar x152 = x59*x8;
        Scalar x153 = x133*x152 + x39;
        Scalar x154 = x141*x40;
        Scalar x155 = (Scalar(1.0)/(sqrt(x0)*x0*x0));
        Scalar x156 = Scalar(pc1_*x155);
        Scalar x157 = Scalar((1.0/2.0)*pc0_*x46*x64 - x156*x45);
        Scalar x158 = Scalar(mu_*x43);
        Scalar x159 = 2*x158;
        Scalar x160 = _hp0_*x159;
        Scalar x161 = x50*x72;
        Scalar x162 = -x161;
        Scalar x163 = _hp1_*x160 + x162;
        Scalar x164 = x53*x72;
        Scalar x165 = _hp2_*x160 - x164;
        Scalar x166 = 2*x111;
        Scalar x167 = -x166 + 2*x56;
        Scalar x168 = x158*x167;
        Scalar x169 = x88 + x90;
        Scalar x170 = _hp0_*x168 + x169;
        Scalar x171 = x170*x27;
        Scalar x172 = LM0*x52;
        Scalar x173 = LM3*x132 + x172;
        Scalar x174 = LM0*x55;
        Scalar x175 = LM4*x147 + x174;
        Scalar x176 = LM2*x27;
        Scalar x177 = LM1*x27;
        Scalar x178 = LM5*x41 + x114*x176 - x177*x82;
        Scalar x179 = LM5*x38;
        Scalar x180 = x177*x83;
        Scalar x181 = x115*x176;
        Scalar x182 = LM1*x40;
        Scalar x183 = LM2*x36;
        Scalar x184 = 1.0/x11;
        Scalar x185 = Scalar((1.0/8.0)*pc0_*x184);
        Scalar x186 = (1.0/4.0)*x184;
        Scalar x187 = Scalar(pc0_*x186);
        Scalar x188 = Scalar(_hp1_*pc2_);
        Scalar x189 = Scalar(_hp0_*mu_);
        Scalar x190 = x155*x189;
        Scalar x191 = x188*x190;
        Scalar x192 = 3*LM0;
        Scalar x193 = x192*x49*x7;
        Scalar x194 = LM3*x144;
        Scalar x195 = LM4*x144;
        Scalar x196 = _hp2_*x195;
        Scalar x197 = Scalar(-1.0/2.0*LM1*pc0_*x64*x75 - 1.0/2.0*LM2*pc0_*x107*x64 + x131*x194 + x134*x196 + x193*x36);
        Scalar x198 = Scalar(_hp2_*pc2_);
        Scalar x199 = x190*x198;
        Scalar x200 = Scalar(-1.0/2.0*LM1*pc0_*x64*x81 - 1.0/2.0*LM2*pc0_*x113*x64 + _hp2_*x134*x194 + x146*x195 + x193*x40);
        Scalar x201 = LM5*x102;
        Scalar x202 = LM1*x102;
        Scalar x203 = LM2*x102;
        Scalar x204 = x102*x37;
        Scalar x205 = LM3*x204;
        Scalar x206 = LM4*x204;
        Scalar x207 = x114*x203 + x143*x201 + x149*x206 - x202*x82 + x205*x84;
        Scalar x208 = -x115*x203 - x125*x201 + x14*x205 + x202*x83 + x206*x85;
        Scalar x209 = x156*x167*x189;
        Scalar x210 = x58*x8;
        Scalar x211 = x210*x50;
        Scalar x212 = x210*x53;
        Scalar x213 = LM0*x47*x60 + x120*x203 + x202*x96;
        Scalar x214 = -_hp1_*x203 + _hp2_*x202;
        Scalar x215 = x192*x98 + x202*x24*x9 + x203*x31*x9;
        Scalar x216 = _hp1_*x194*x9 + x1*x16*x203 - x16*x2*x202 + x16*x201 + x196*x9;
        Scalar x217 = (Scalar(1.0)/(_hp0_*_hp0_*_hp0_));
        Scalar x218 = x217*x67;
        Scalar x219 = LM0*x11*x7;
        Scalar x220 = Scalar(pc2_*x219);
        Scalar x221 = LM3*x27;
        Scalar x222 = x124*x8;
        Scalar x223 = x217*x222;
        Scalar x224 = LM4*x40;
        Scalar x225 = x218*x222;
        Scalar x226 = 2*x217*x67*x72;
        Scalar x227 = LM5*x27;
        Scalar x228 = x54*x67;
        Scalar x229 = x217*x220;
        Scalar x230 = LM3*x40;
        Scalar x231 = LM4*x108;
        Scalar x232 = x223*x36;
        Scalar x233 = 2*x217;
        Scalar x234 = x233*x72;
        Scalar x235 = 2*x20;
        Scalar x236 = x217*x72;
        Scalar x237 = x235*x236;
        Scalar x238 = x108*x51;
        Scalar x239 = x176*(2*_hp1_*_hp2_*x1*x15*x217*x8 + 2*_hp1_*_hp2_*x217*x31*x7 - x109*x51 - x164 - x238) + x177*(2*_hp1_*_hp2_*x217*x24*x7 - _hp1_*x237 - x162 - x228 - x54*x68) + x225*x230 + x227*(x159*x77 + x234*x77) + x229*x77 + x231*x232;
        Scalar x240 = x19*x8;
        Scalar x241 = x131*x221;
        Scalar x242 = x130*x149*x36;
        Scalar x243 = LM5*x40;
        Scalar x244 = x134*x243;
        Scalar x245 = LM1*x36;
        Scalar x246 = -x130*x20*x245 + x244;
        Scalar x247 = LM4*x242 + x241*x3 + x246;
        Scalar x248 = x130*x14;
        Scalar x249 = Scalar(-LM5*pc0_*x26*x49*x67*x8 + x131*x177*x2 + x224*x248 + x241*x4);
        Scalar x250 = x24*x7;
        Scalar x251 = x217*x250;
        Scalar x252 = -x167;
        Scalar x253 = _hp1_*x252;
        Scalar x254 = 2*x78;
        Scalar x255 = -_hp1_*x2*x49*x8*x86 + x254 - x49*x58*x68*x7 + x51*x94 + x80;
        Scalar x256 = _hp2_*x58;
        Scalar x257 = x256*x51;
        Scalar x258 = x10*x108;
        Scalar x259 = x31*x7;
        Scalar x260 = x217*x253;
        Scalar x261 = x236*x252;
        Scalar x262 = x130*x86;
        Scalar x263 = x112 - x118*x51 + x169 - x19*x262;
        Scalar x264 = x8*x86;
        Scalar x265 = x165 + x264*x50;
        Scalar x266 = LM0*x12;
        Scalar x267 = x266*x7;
        Scalar x268 = x124*x40;
        Scalar x269 = x134*x268;
        Scalar x270 = LM3*x8;
        Scalar x271 = x129*x252;
        Scalar x272 = x133*x260;
        Scalar x273 = x266*x50;
        Scalar x274 = x77*x9;
        Scalar x275 = x15*x49;
        Scalar x276 = x19*x275;
        Scalar x277 = x129*x49;
        Scalar x278 = LM5*x275;
        Scalar x279 = x133*x50;
        Scalar x280 = Scalar(-LM1*_hp1_*pc0_*x15*x2*x26*x49 + LM3*x277*x67 + LM4*x279 + x278*x36);
        Scalar x281 = LM4*x27;
        Scalar x282 = 2*x108*x217;
        Scalar x283 = x282*x72;
        Scalar x284 = x146*x281;
        Scalar x285 = LM3*x242 + x1*x146*x176 + x146*x227 + x284*x3;
        Scalar x286 = x20*x8;
        Scalar x287 = LM2*x40;
        Scalar x288 = x130*x19*x287;
        Scalar x289 = -x230*x248 - x284*x4 + x288;
        Scalar x290 = x54*x94;
        Scalar x291 = _hp2_*x252;
        Scalar x292 = x217*x291;
        Scalar x293 = x104 + x106 - x109*x49*x58*x7 + x111*x262 + x118*x54 - x254;
        Scalar x294 = Scalar(-2*_hp0_*_hp1_*mu_*x43 + x161 + x264*x53);
        Scalar x295 = x266*x53;
        Scalar x296 = LM3*x279 + x111*x176*x275 + x231*x277 + x278*x40;
        Scalar x297 = LM3*x38 + LM4*x41;
        Scalar x298 = x111*x152;
        Scalar x299 = x152*x221;
        Scalar x300 = x152*x281;
        Scalar x301 = x286*x59;
        Scalar x302 = LM5*x9;
        Scalar x303 = LM2*x98;
        Scalar x304 = LM3*x98;
        Scalar x305 = LM4*x98;
        Scalar x306 = LM1*x98;
        Scalar x307 = x111*x303 + x149*x305 - x20*x306 + x302*x40 + x304*x84;
        Scalar x308 = x152*x36;
        Scalar x309 = x240*x59;
        Scalar x310 = x14*x304 - x19*x303 - x302*x36 + x305*x85 + x306*x56;
        Scalar x311 = x217*x219*x58;
        Scalar x312 = x124*x210*x27;
        Scalar x313 = x210*x217;
        Scalar x314 = -_hp1_*x268*x313 - x132 - x148;
        Scalar x315 = _hp1_*x58;
        Scalar x316 = 2*x251;
        Scalar x317 = x233*x259;
        Scalar x318 = 2*x19;
        Scalar x319 = x10*(-x108 + x67) + x257;
        Scalar x320 = x152*x27;
        Scalar x321 = x21*x49;
        Scalar x322 = x252*x58;
        Scalar x323 = x217*x322;
        Scalar x324 = x321*x72;
        Scalar x325 = 2*x264*x59;
        Scalar x326 = x323*x72;
        Scalar x327 = 2*x60;
        Scalar x328 = -x21;
        Scalar x329 = x245 + x287;
        Scalar x330 = x266*x59;
        Scalar x331 = x1*x87;
        Scalar x332 = x1*x89;
        Scalar x333 = x2*x87;
        Scalar x334 = x2*x89;
        Scalar x335 = x35*x59;
        Scalar x336 = x335*x40;
        Scalar x337 = x24*x49;
        Scalar x338 = x31*x49;
        
        _fx_[0] = x10*x12;
        _fx_[1] = x25*x27;
        _fx_[2] = x27*x32;
        _fx_[3] = x39;
        _fx_[4] = x42;
        _fx_[5] = x27*x46;
        
        _jx_(0,0) = x48;
        _jx_(1,0) = x66;
        _jx_(2,0) = x103;
        _jx_(3,0) = x128;
        _jx_(4,0) = x145;
        _jx_(5,0) = x157;
        _jx_(0,1) = -x52;
        _jx_(1,1) = x27*x75;
        _jx_(2,1) = x107*x27;
        _jx_(3,1) = -x132;
        _jx_(4,1) = x136;
        _jx_(5,1) = x163*x27;
        _jx_(0,2) = -x55;
        _jx_(1,2) = x27*x81;
        _jx_(2,2) = x113*x27;
        _jx_(3,2) = x136;
        _jx_(4,2) = x148;
        _jx_(5,2) = x165*x27;
        _jx_(0,3) = 0;
        _jx_(1,3) = -x27*x82;
        _jx_(2,3) = x114*x27;
        _jx_(3,3) = x138;
        _jx_(4,3) = x150;
        _jx_(5,3) = x41;
        _jx_(0,4) = 0;
        _jx_(1,4) = x27*x83;
        _jx_(2,4) = -x115*x27;
        _jx_(3,4) = x139;
        _jx_(4,4) = x151;
        _jx_(5,4) = -x38;
        _jx_(0,5) = x61;
        _jx_(1,5) = x97;
        _jx_(2,5) = x121;
        _jx_(3,5) = x140;
        _jx_(4,5) = x153;
        _jx_(5,5) = x171;
        _jx_(0,6) = 0;
        _jx_(1,6) = x40;
        _jx_(2,6) = -x36;
        _jx_(3,6) = 0;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = x62;
        _jx_(1,7) = x99;
        _jx_(2,7) = x122;
        _jx_(3,7) = 0;
        _jx_(4,7) = 0;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = -x101;
        _jx_(2,8) = x123;
        _jx_(3,8) = x142;
        _jx_(4,8) = x154;
        _jx_(5,8) = x100;
        
        _gx_[0] = LM0*x48 + LM1*x66 + LM2*x103 + LM3*x128 + LM4*x145 + LM5*x157;
        _gx_[1] = Scalar(LM1*pc0_*x26*x75 + LM2*pc0_*x107*x26 - LM4*x135 + LM5*pc0_*x163*x26 - x173);
        _gx_[2] = Scalar(LM1*pc0_*x26*x81 + LM2*pc0_*x113*x26 - LM3*x135 + LM5*pc0_*x165*x26 - x175);
        _gx_[3] = LM3*x138 + LM4*x150 + x178;
        _gx_[4] = LM3*x139 + LM4*x151 - x179 + x180 - x181;
        _gx_[5] = LM0*x61 + LM1*x97 + LM2*x121 + LM3*x140 + LM4*x153 + LM5*x171;
        _gx_[6] = x182 - x183;
        _gx_[7] = LM0*x62 + LM1*x99 + LM2*x122;
        _gx_[8] = -LM1*x101 + LM2*x123 + LM3*x142 + LM4*x154 + LM5*x100;
        
        _hx_(0,0) = Scalar((3.0/2.0)*LM0*pc0_*x64*x7*x9 - LM1*x186*x63 - LM2*x187*x32 - LM3*x126*x185 - LM4*x124*x143*x185 + LM5*(pc2_*x45/(sqrt(x0)*x0*x0*x0) - x187*x46));
        _hx_(0,1) = Scalar(LM5*((1.0/2.0)*pc0_*x163*x64 - x191) - x197);
        _hx_(1,1) = (_hp1_*_hp1_*_hp1_)*x221*x223 + x176*(2*x1*x15*x217*x67*x8 - 2*x161 + 2*x217*x31*x67*x7 - 2*x228) + x177*(-x2*x226 + 2*x217*x24*x67*x7 - 2*x51*x68) + x218*x220 + x224*x225 + x227*(x159*x67 + x226);
        _hx_(0,2) = Scalar(LM5*((1.0/2.0)*pc0_*x165*x64 - x199) - x200);
        _hx_(1,2) = x239;
        _hx_(2,2) = LM3*x108*x232 + (_hp2_*_hp2_*_hp2_)*x223*x281 + x108*x229 + x176*(x1*x283 - 2*x109*x54 + x259*x282) + x177*(2*_hp2_*x15*x49*x8 + 2*x108*x217*x24*x7 - x2*x283 - 2*x238) + x227*(x108*x159 + x283);
        _hx_(0,3) = x207;
        _hx_(1,3) = Scalar(LM2*pc0_*x26*(x143 - x240*x53) - x247);
        _hx_(2,3) = Scalar(LM1*pc0_*x26*(x108*x2*x49*x8 - x143) - x285);
        _hx_(3,3) = x297;
        _hx_(0,4) = x208;
        _hx_(1,4) = Scalar(LM2*pc0_*x26*(x1*x49*x67*x8 - x125) - x249);
        _hx_(2,4) = x177*(x125 - x286*x50) + x244 + x289;
        _hx_(3,4) = 0;
        _hx_(4,4) = x297;
        _hx_(0,5) = Scalar(-LM3*x145 + LM4*x128 + LM5*((1.0/2.0)*pc0_*x170*x64 - x209) + x194*x211 + x195*x212 + x213);
        _hx_(1,5) = Scalar(LM3*x269 - LM4*x132 - LM4*x272*x8 + x175 + x176*(x10*x67 - x19*x261 + x257 - x258 - x259*x260 + x263) + x177*(_hp1_*x15*x2*x217*x252*x8 - x251*x253 - x255) - x218*x270*x271 + x227*(2*_hp1_*mu_*x43*x57 - x260*x72 - x265) - x260*x267);
        _hx_(2,5) = Scalar(LM1*pc0_*x26*(_hp1_*_hp2_*x49*x58*x7 + _hp1_*x15*x2*x49*x8 + _hp2_*x15*x2*x217*x252*x8 + _hp2_*x2*x49*x8*x86 - x169 - x251*x291 - x258 - x290 + x67*x7*x9 - x71) + LM2*pc0_*x26*(-x111*x261 - x259*x292 - x293) + (1.0/2.0)*LM3*pc0_*x108*x124*x26*x49*x8 - LM4*x269 + LM5*pc0_*x26*(2*_hp2_*mu_*x43*x57 - x292*x72 - x294) - x173 - x217*x231*x271*x8 - x267*x292 - x270*x272);
        _hx_(3,5) = -LM3*x150 + LM4*x138 + x149*x300 + x152*x243 + x176*x298 - x177*x301 + x179 - x180 + x181 + x299*x84;
        _hx_(4,5) = -LM3*x151 + LM4*x139 - LM5*x308 + x14*x299 + x152*x177*x56 - x176*x309 + x178 + x300*x85;
        _hx_(5,5) = Scalar(LM3*(_hp1_*pc0_*x21*x26*x35*x49*x8 + _hp1_*pc0_*x217*x252*x26*x35*x58*x8 - x152*x268 - x39) + LM4*(x124*x308 + x130*x133*x21 + x133*x252*x313 - x42) + x176*(x1*x324 + x1*x325 + x1*x326 + x10*(_hp2_*x328 + 2*x92 + x93) + x118*x327 + x259*x321 + x259*x323 + x28 - x29) + x177*(x10*(_hp1_*x328 - 2*x117 - x23) - x13 + x18 - x2*x324 - x2*x325 - x2*x326 + x250*x321 + x251*x322 + x327*x94) + x227*(_hp0_*x158*(-x235 - x318) + x168*x57 + x324 + x325 + x326 + x76) + x267*x321 + x267*x323);
        _hx_(0,6) = x214;
        _hx_(1,6) = 0;
        _hx_(2,6) = 0;
        _hx_(3,6) = 0;
        _hx_(4,6) = 0;
        _hx_(5,6) = x329;
        _hx_(6,6) = 0;
        _hx_(0,7) = x215;
        _hx_(1,7) = x176*(-x105 + x274) + x177*(x69 - x70) - x273;
        _hx_(2,7) = x176*(x109*x9 - x110) + x177*(x274 - x79) - x295;
        _hx_(3,7) = 0;
        _hx_(4,7) = 0;
        _hx_(5,7) = x176*(x116 + x119) + x177*(x91 + x95) + x330;
        _hx_(6,7) = 0;
        _hx_(7,7) = 0;
        _hx_(0,8) = x216;
        _hx_(1,8) = Scalar(LM2*pc0_*x26*(x16 - x276) - x280);
        _hx_(2,8) = Scalar(LM1*pc0_*x26*(_hp2_*x15*x2*x49 - x16) - x296);
        _hx_(3,8) = x307;
        _hx_(4,8) = x310;
        _hx_(5,8) = Scalar(LM3*(_hp1_*pc0_*x26*x35*x49*x58 - x154) + LM4*(x142 + x336) + x176*(x331 + x332) + x177*(-x333 - x334) + x227*(x87 + x89));
        _hx_(6,8) = 0;
        _hx_(7,8) = 0;
        _hx_(8,8) = 0;
        
        _hx_(1,0) = _hx_(0,1);
        _hx_(2,0) = _hx_(0,2);
        _hx_(3,0) = _hx_(0,3);
        _hx_(4,0) = _hx_(0,4);
        _hx_(5,0) = _hx_(0,5);
        _hx_(6,0) = _hx_(0,6);
        _hx_(7,0) = _hx_(0,7);
        _hx_(8,0) = _hx_(0,8);
        _hx_(2,1) = _hx_(1,2);
        _hx_(3,1) = _hx_(1,3);
        _hx_(4,1) = _hx_(1,4);
        _hx_(5,1) = _hx_(1,5);
        _hx_(6,1) = _hx_(1,6);
        _hx_(7,1) = _hx_(1,7);
        _hx_(8,1) = _hx_(1,8);
        _hx_(3,2) = _hx_(2,3);
        _hx_(4,2) = _hx_(2,4);
        _hx_(5,2) = _hx_(2,5);
        _hx_(6,2) = _hx_(2,6);
        _hx_(7,2) = _hx_(2,7);
        _hx_(8,2) = _hx_(2,8);
        _hx_(4,3) = _hx_(3,4);
        _hx_(5,3) = _hx_(3,5);
        _hx_(6,3) = _hx_(3,6);
        _hx_(7,3) = _hx_(3,7);
        _hx_(8,3) = _hx_(3,8);
        _hx_(5,4) = _hx_(4,5);
        _hx_(6,4) = _hx_(4,6);
        _hx_(7,4) = _hx_(4,7);
        _hx_(8,4) = _hx_(4,8);
        _hx_(6,5) = _hx_(5,6);
        _hx_(7,5) = _hx_(5,7);
        _hx_(8,5) = _hx_(5,8);
        _hx_(7,6) = _hx_(6,7);
        _hx_(8,6) = _hx_(6,8);
        _hx_(8,7) = _hx_(7,8);
    }

};

} // namespace tycho::astro
