// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_cartesian_dynamics.py — do not edit manually.
// =============================================================================
#pragma once
#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct CartesianDynamics
    : VectorFunction<CartesianDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<CartesianDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu_; // Gravitational Parameter
    static constexpr bool is_vectorizable = true;

    CartesianDynamics() {
        this->set_io_rows(9, 6);
    }
    CartesianDynamics(double mu)
        : mu_(mu) {
        this->set_io_rows(9, 6);
    }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = (x0*x0) + (x1*x1) + (x2*x2);
        Scalar x9 = Scalar(mu_/(sqrt(_hp0_)*_hp0_));
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = -x0*x9 + x6;
        _fx_[4] = -x1*x9 + x7;
        _fx_[5] = -x2*x9 + x8;
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_,
                         CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = (x0*x0) + (x1*x1) + (x2*x2);
        Scalar x9 = Scalar(mu_/(sqrt(_hp0_)*_hp0_));
        Scalar x10 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_*_hp0_));
        Scalar x11 = Scalar(3*mu_*x10);
        Scalar x12 = x0*x11;
        Scalar x13 = x1*x12;
        Scalar x14 = x12*x2;
        Scalar x15 = x1*x11*x2;
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = -x0*x9 + x6;
        _fx_[4] = -x1*x9 + x7;
        _fx_[5] = -x2*x9 + x8;
        
        _jx_(0,0) = 0;
        _jx_(1,0) = 0;
        _jx_(2,0) = 0;
        _jx_(3,0) = Scalar(3*mu_*(x0*x0)*x10 - x9);
        _jx_(4,0) = x13;
        _jx_(5,0) = x14;
        _jx_(0,1) = 0;
        _jx_(1,1) = 0;
        _jx_(2,1) = 0;
        _jx_(3,1) = x13;
        _jx_(4,1) = Scalar(3*mu_*(x1*x1)*x10 - x9);
        _jx_(5,1) = x15;
        _jx_(0,2) = 0;
        _jx_(1,2) = 0;
        _jx_(2,2) = 0;
        _jx_(3,2) = x14;
        _jx_(4,2) = x15;
        _jx_(5,2) = Scalar(3*mu_*x10*(x2*x2) - x9);
        _jx_(0,3) = 1;
        _jx_(1,3) = 0;
        _jx_(2,3) = 0;
        _jx_(3,3) = 0;
        _jx_(4,3) = 0;
        _jx_(5,3) = 0;
        _jx_(0,4) = 0;
        _jx_(1,4) = 1;
        _jx_(2,4) = 0;
        _jx_(3,4) = 0;
        _jx_(4,4) = 0;
        _jx_(5,4) = 0;
        _jx_(0,5) = 0;
        _jx_(1,5) = 0;
        _jx_(2,5) = 1;
        _jx_(3,5) = 0;
        _jx_(4,5) = 0;
        _jx_(5,5) = 0;
        _jx_(0,6) = 0;
        _jx_(1,6) = 0;
        _jx_(2,6) = 0;
        _jx_(3,6) = 1;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = 0;
        _jx_(1,7) = 0;
        _jx_(2,7) = 0;
        _jx_(3,7) = 0;
        _jx_(4,7) = 1;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = 0;
        _jx_(2,8) = 0;
        _jx_(3,8) = 0;
        _jx_(4,8) = 0;
        _jx_(5,8) = 1;
    }

    template <class InType, class OutType, class JacType,
                 class AdjGradType, class AdjHessType,
                 class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_,
        CVecRef<OutType> fx_,
        CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_,
        CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar _hp0_ = (x0*x0) + (x1*x1) + (x2*x2);
        Scalar x9 = Scalar(mu_/(sqrt(_hp0_)*_hp0_));
        Scalar x10 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_*_hp0_));
        Scalar x11 = (x0*x0);
        Scalar x12 = Scalar(3*mu_*x10*x11 - x9);
        Scalar x13 = Scalar(mu_*x10);
        Scalar x14 = 3*x13;
        Scalar x15 = x1*x14;
        Scalar x16 = x0*x15;
        Scalar x17 = x14*x2;
        Scalar x18 = x0*x17;
        Scalar x19 = (x1*x1);
        Scalar x20 = Scalar(3*mu_*x10*x19 - x9);
        Scalar x21 = x15*x2;
        Scalar x22 = (x2*x2);
        Scalar x23 = Scalar(3*mu_*x10*x22 - x9);
        Scalar x24 = LM4*x15;
        Scalar x25 = LM5*x17;
        Scalar x26 = Scalar(15*mu_/(sqrt(_hp0_)*_hp0_*_hp0_*_hp0_));
        Scalar x27 = x11*x26;
        Scalar x28 = x1*x27;
        Scalar x29 = x2*x27;
        Scalar x30 = 9*x13;
        Scalar x31 = x0*x14;
        Scalar x32 = x0*x1*x2*x26;
        Scalar x33 = -LM5*x32;
        Scalar x34 = x19*x26;
        Scalar x35 = x0*x34;
        Scalar x36 = -LM4*x32;
        Scalar x37 = x22*x26;
        Scalar x38 = x0*x37;
        Scalar x39 = LM3*x31;
        Scalar x40 = x2*x34;
        Scalar x41 = LM3*x32;
        Scalar x42 = x1*x37;
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = -x0*x9 + x6;
        _fx_[4] = -x1*x9 + x7;
        _fx_[5] = -x2*x9 + x8;
        
        _jx_(0,0) = 0;
        _jx_(1,0) = 0;
        _jx_(2,0) = 0;
        _jx_(3,0) = x12;
        _jx_(4,0) = x16;
        _jx_(5,0) = x18;
        _jx_(0,1) = 0;
        _jx_(1,1) = 0;
        _jx_(2,1) = 0;
        _jx_(3,1) = x16;
        _jx_(4,1) = x20;
        _jx_(5,1) = x21;
        _jx_(0,2) = 0;
        _jx_(1,2) = 0;
        _jx_(2,2) = 0;
        _jx_(3,2) = x18;
        _jx_(4,2) = x21;
        _jx_(5,2) = x23;
        _jx_(0,3) = 1;
        _jx_(1,3) = 0;
        _jx_(2,3) = 0;
        _jx_(3,3) = 0;
        _jx_(4,3) = 0;
        _jx_(5,3) = 0;
        _jx_(0,4) = 0;
        _jx_(1,4) = 1;
        _jx_(2,4) = 0;
        _jx_(3,4) = 0;
        _jx_(4,4) = 0;
        _jx_(5,4) = 0;
        _jx_(0,5) = 0;
        _jx_(1,5) = 0;
        _jx_(2,5) = 1;
        _jx_(3,5) = 0;
        _jx_(4,5) = 0;
        _jx_(5,5) = 0;
        _jx_(0,6) = 0;
        _jx_(1,6) = 0;
        _jx_(2,6) = 0;
        _jx_(3,6) = 1;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = 0;
        _jx_(1,7) = 0;
        _jx_(2,7) = 0;
        _jx_(3,7) = 0;
        _jx_(4,7) = 1;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = 0;
        _jx_(2,8) = 0;
        _jx_(3,8) = 0;
        _jx_(4,8) = 0;
        _jx_(5,8) = 1;
        
        _gx_[0] = LM3*x12 + LM4*x16 + LM5*x18;
        _gx_[1] = LM3*x16 + LM4*x20 + LM5*x21;
        _gx_[2] = LM3*x18 + LM4*x21 + LM5*x23;
        _gx_[3] = LM0;
        _gx_[4] = LM1;
        _gx_[5] = LM2;
        _gx_[6] = LM3;
        _gx_[7] = LM4;
        _gx_[8] = LM5;
        
        _hx_(0,0) = LM3*(-(x0*x0*x0)*x26 + x0*x30) - LM4*x28 - LM5*x29 + x24 + x25;
        _hx_(0,1) = LM3*(x15 - x28) + LM4*x31 - LM4*x35 + x33;
        _hx_(1,1) = -LM3*x35 + LM4*(-(x1*x1*x1)*x26 + x1*x30) - LM5*x40 + x25 + x39;
        _hx_(0,2) = LM3*(x17 - x29) + LM5*x31 - LM5*x38 + x36;
        _hx_(1,2) = Scalar(LM4*(x17 - x40) + 3*LM5*mu_*x1*x10 - LM5*x42 - x41);
        _hx_(2,2) = -LM3*x38 - LM4*x42 + LM5*(-(x2*x2*x2)*x26 + x2*x30) + x24 + x39;
        _hx_(0,3) = 0;
        _hx_(1,3) = 0;
        _hx_(2,3) = 0;
        _hx_(3,3) = 0;
        _hx_(0,4) = 0;
        _hx_(1,4) = 0;
        _hx_(2,4) = 0;
        _hx_(3,4) = 0;
        _hx_(4,4) = 0;
        _hx_(0,5) = 0;
        _hx_(1,5) = 0;
        _hx_(2,5) = 0;
        _hx_(3,5) = 0;
        _hx_(4,5) = 0;
        _hx_(5,5) = 0;
        _hx_(0,6) = 0;
        _hx_(1,6) = 0;
        _hx_(2,6) = 0;
        _hx_(3,6) = 0;
        _hx_(4,6) = 0;
        _hx_(5,6) = 0;
        _hx_(6,6) = 0;
        _hx_(0,7) = 0;
        _hx_(1,7) = 0;
        _hx_(2,7) = 0;
        _hx_(3,7) = 0;
        _hx_(4,7) = 0;
        _hx_(5,7) = 0;
        _hx_(6,7) = 0;
        _hx_(7,7) = 0;
        _hx_(0,8) = 0;
        _hx_(1,8) = 0;
        _hx_(2,8) = 0;
        _hx_(3,8) = 0;
        _hx_(4,8) = 0;
        _hx_(5,8) = 0;
        _hx_(6,8) = 0;
        _hx_(7,8) = 0;
        _hx_(8,8) = 0;
        
        _hx_(1,0) = _hx_(0,1);
        _hx_(2,0) = _hx_(0,2);
        _hx_(3,0) = _hx_(0,3);
        _hx_(4,0) = _hx_(0,4);
        _hx_(5,0) = _hx_(0,5);
        _hx_(6,0) = _hx_(0,6);
        _hx_(7,0) = _hx_(0,7);
        _hx_(8,0) = _hx_(0,8);
        _hx_(2,1) = _hx_(1,2);
        _hx_(3,1) = _hx_(1,3);
        _hx_(4,1) = _hx_(1,4);
        _hx_(5,1) = _hx_(1,5);
        _hx_(6,1) = _hx_(1,6);
        _hx_(7,1) = _hx_(1,7);
        _hx_(8,1) = _hx_(1,8);
        _hx_(3,2) = _hx_(2,3);
        _hx_(4,2) = _hx_(2,4);
        _hx_(5,2) = _hx_(2,5);
        _hx_(6,2) = _hx_(2,6);
        _hx_(7,2) = _hx_(2,7);
        _hx_(8,2) = _hx_(2,8);
        _hx_(4,3) = _hx_(3,4);
        _hx_(5,3) = _hx_(3,5);
        _hx_(6,3) = _hx_(3,6);
        _hx_(7,3) = _hx_(3,7);
        _hx_(8,3) = _hx_(3,8);
        _hx_(5,4) = _hx_(4,5);
        _hx_(6,4) = _hx_(4,6);
        _hx_(7,4) = _hx_(4,7);
        _hx_(8,4) = _hx_(4,8);
        _hx_(6,5) = _hx_(5,6);
        _hx_(7,5) = _hx_(5,7);
        _hx_(8,5) = _hx_(5,8);
        _hx_(7,6) = _hx_(6,7);
        _hx_(8,6) = _hx_(6,8);
        _hx_(8,7) = _hx_(7,8);
    }

};

} // namespace tycho::astro
