// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_cartesian_dynamics.py — do not edit manually.
// =============================================================================
#pragma once
#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct CartesianDynamics
    : VectorFunction<CartesianDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<CartesianDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu_; // Gravitational Parameter
    static constexpr bool is_vectorizable = true;

    CartesianDynamics() {
        this->set_io_rows(9, 6);
    }
    CartesianDynamics(double mu)
        : mu_(mu) {
        this->set_io_rows(9, 6);
    }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar x9 = Scalar(mu_/pow((x0*x0) + (x1*x1) + (x2*x2), 3.0/2.0));
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = -x0*x9 + x6;
        _fx_[4] = -x1*x9 + x7;
        _fx_[5] = -x2*x9 + x8;
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_,
                         CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar x9 = (x0*x0);
        Scalar x10 = (x1*x1);
        Scalar x11 = (x2*x2);
        Scalar x12 = x10 + x11 + x9;
        Scalar x13 = Scalar(mu_/(sqrt(x12)*x12));
        Scalar x14 = -x13;
        Scalar x15 = Scalar(3*mu_/(sqrt(x12)*x12*x12));
        Scalar x16 = x0*x15;
        Scalar x17 = x1*x16;
        Scalar x18 = x16*x2;
        Scalar x19 = x1*x15*x2;
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = -x0*x13 + x6;
        _fx_[4] = -x1*x13 + x7;
        _fx_[5] = -x13*x2 + x8;
        
        _jx_(0,0) = 0;
        _jx_(1,0) = 0;
        _jx_(2,0) = 0;
        _jx_(3,0) = x14 + x15*x9;
        _jx_(4,0) = x17;
        _jx_(5,0) = x18;
        _jx_(0,1) = 0;
        _jx_(1,1) = 0;
        _jx_(2,1) = 0;
        _jx_(3,1) = x17;
        _jx_(4,1) = x10*x15 + x14;
        _jx_(5,1) = x19;
        _jx_(0,2) = 0;
        _jx_(1,2) = 0;
        _jx_(2,2) = 0;
        _jx_(3,2) = x18;
        _jx_(4,2) = x19;
        _jx_(5,2) = x11*x15 + x14;
        _jx_(0,3) = 1;
        _jx_(1,3) = 0;
        _jx_(2,3) = 0;
        _jx_(3,3) = 0;
        _jx_(4,3) = 0;
        _jx_(5,3) = 0;
        _jx_(0,4) = 0;
        _jx_(1,4) = 1;
        _jx_(2,4) = 0;
        _jx_(3,4) = 0;
        _jx_(4,4) = 0;
        _jx_(5,4) = 0;
        _jx_(0,5) = 0;
        _jx_(1,5) = 0;
        _jx_(2,5) = 1;
        _jx_(3,5) = 0;
        _jx_(4,5) = 0;
        _jx_(5,5) = 0;
        _jx_(0,6) = 0;
        _jx_(1,6) = 0;
        _jx_(2,6) = 0;
        _jx_(3,6) = 1;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = 0;
        _jx_(1,7) = 0;
        _jx_(2,7) = 0;
        _jx_(3,7) = 0;
        _jx_(4,7) = 1;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = 0;
        _jx_(2,8) = 0;
        _jx_(3,8) = 0;
        _jx_(4,8) = 0;
        _jx_(5,8) = 1;
    }

    template <class InType, class OutType, class JacType,
                 class AdjGradType, class AdjHessType,
                 class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_,
        CVecRef<OutType> fx_,
        CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_,
        CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar x9 = (x0*x0);
        Scalar x10 = (x1*x1);
        Scalar x11 = (x2*x2);
        Scalar x12 = x10 + x11 + x9;
        Scalar x13 = Scalar(mu_/(sqrt(x12)*x12));
        Scalar x14 = -x13;
        Scalar x15 = (Scalar(1.0)/(sqrt(x12)*x12*x12));
        Scalar x16 = Scalar(3*mu_*x15);
        Scalar x17 = x14 + x16*x9;
        Scalar x18 = x1*x16;
        Scalar x19 = x0*x18;
        Scalar x20 = x16*x2;
        Scalar x21 = x0*x20;
        Scalar x22 = x10*x16 + x14;
        Scalar x23 = x18*x2;
        Scalar x24 = x11*x16 + x14;
        Scalar x25 = LM4*x18;
        Scalar x26 = LM5*x20;
        Scalar x27 = Scalar(15*mu_/(sqrt(x12)*x12*x12*x12));
        Scalar x28 = x27*x9;
        Scalar x29 = x1*x28;
        Scalar x30 = x2*x28;
        Scalar x31 = x0*x16;
        Scalar x32 = x0*x1*x2*x27;
        Scalar x33 = LM5*x32;
        Scalar x34 = x10*x27;
        Scalar x35 = x0*x34;
        Scalar x36 = Scalar(-3*mu_*x1*x15);
        Scalar x37 = LM4*x32;
        Scalar x38 = x11*x27;
        Scalar x39 = x0*x38;
        Scalar x40 = Scalar(-3*mu_*x15*x2);
        Scalar x41 = Scalar(-3*mu_*x0*x15);
        Scalar x42 = LM3*x31;
        Scalar x43 = x2*x34;
        Scalar x44 = LM3*x32;
        Scalar x45 = x1*x38;
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = -x0*x13 + x6;
        _fx_[4] = -x1*x13 + x7;
        _fx_[5] = -x13*x2 + x8;
        
        _jx_(0,0) = 0;
        _jx_(1,0) = 0;
        _jx_(2,0) = 0;
        _jx_(3,0) = x17;
        _jx_(4,0) = x19;
        _jx_(5,0) = x21;
        _jx_(0,1) = 0;
        _jx_(1,1) = 0;
        _jx_(2,1) = 0;
        _jx_(3,1) = x19;
        _jx_(4,1) = x22;
        _jx_(5,1) = x23;
        _jx_(0,2) = 0;
        _jx_(1,2) = 0;
        _jx_(2,2) = 0;
        _jx_(3,2) = x21;
        _jx_(4,2) = x23;
        _jx_(5,2) = x24;
        _jx_(0,3) = 1;
        _jx_(1,3) = 0;
        _jx_(2,3) = 0;
        _jx_(3,3) = 0;
        _jx_(4,3) = 0;
        _jx_(5,3) = 0;
        _jx_(0,4) = 0;
        _jx_(1,4) = 1;
        _jx_(2,4) = 0;
        _jx_(3,4) = 0;
        _jx_(4,4) = 0;
        _jx_(5,4) = 0;
        _jx_(0,5) = 0;
        _jx_(1,5) = 0;
        _jx_(2,5) = 1;
        _jx_(3,5) = 0;
        _jx_(4,5) = 0;
        _jx_(5,5) = 0;
        _jx_(0,6) = 0;
        _jx_(1,6) = 0;
        _jx_(2,6) = 0;
        _jx_(3,6) = 1;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = 0;
        _jx_(1,7) = 0;
        _jx_(2,7) = 0;
        _jx_(3,7) = 0;
        _jx_(4,7) = 1;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = 0;
        _jx_(2,8) = 0;
        _jx_(3,8) = 0;
        _jx_(4,8) = 0;
        _jx_(5,8) = 1;
        
        _gx_[0] = LM3*x17 + LM4*x19 + LM5*x21;
        _gx_[1] = LM3*x19 + LM4*x22 + LM5*x23;
        _gx_[2] = LM3*x21 + LM4*x23 + LM5*x24;
        _gx_[3] = LM0;
        _gx_[4] = LM1;
        _gx_[5] = LM2;
        _gx_[6] = LM3;
        _gx_[7] = LM4;
        _gx_[8] = LM5;
        
        _hx_(0,0) = Scalar(LM3*(9*mu_*x0*x15 - (x0*x0*x0)*x27) - LM4*x29 - LM5*x30 + x25 + x26);
        _hx_(1,0) = _hx_(0,1);
        _hx_(2,0) = _hx_(0,2);
        _hx_(3,0) = _hx_(0,3);
        _hx_(4,0) = _hx_(0,4);
        _hx_(5,0) = _hx_(0,5);
        _hx_(6,0) = _hx_(0,6);
        _hx_(7,0) = _hx_(0,7);
        _hx_(8,0) = _hx_(0,8);
        _hx_(0,1) = LM3*(-x29 - x36) + LM4*x31 - LM4*x35 - x33;
        _hx_(1,1) = Scalar(-LM3*x35 + LM4*(9*mu_*x1*x15 - (x1*x1*x1)*x27) - LM5*x43 + x26 + x42);
        _hx_(2,1) = _hx_(1,2);
        _hx_(3,1) = _hx_(1,3);
        _hx_(4,1) = _hx_(1,4);
        _hx_(5,1) = _hx_(1,5);
        _hx_(6,1) = _hx_(1,6);
        _hx_(7,1) = _hx_(1,7);
        _hx_(8,1) = _hx_(1,8);
        _hx_(0,2) = LM3*(-x30 - x40) + LM5*x31 - LM5*x39 - x37;
        _hx_(1,2) = Scalar(LM4*(-x40 - x43) + 3*LM5*mu_*x1*x15 - LM5*x45 - x44);
        _hx_(2,2) = Scalar(-LM3*x39 - LM4*x45 + LM5*(9*mu_*x15*x2 - (x2*x2*x2)*x27) + x25 + x42);
        _hx_(3,2) = _hx_(2,3);
        _hx_(4,2) = _hx_(2,4);
        _hx_(5,2) = _hx_(2,5);
        _hx_(6,2) = _hx_(2,6);
        _hx_(7,2) = _hx_(2,7);
        _hx_(8,2) = _hx_(2,8);
        _hx_(0,3) = 0;
        _hx_(1,3) = 0;
        _hx_(2,3) = 0;
        _hx_(3,3) = 0;
        _hx_(4,3) = _hx_(3,4);
        _hx_(5,3) = _hx_(3,5);
        _hx_(6,3) = _hx_(3,6);
        _hx_(7,3) = _hx_(3,7);
        _hx_(8,3) = _hx_(3,8);
        _hx_(0,4) = 0;
        _hx_(1,4) = 0;
        _hx_(2,4) = 0;
        _hx_(3,4) = 0;
        _hx_(4,4) = 0;
        _hx_(5,4) = _hx_(4,5);
        _hx_(6,4) = _hx_(4,6);
        _hx_(7,4) = _hx_(4,7);
        _hx_(8,4) = _hx_(4,8);
        _hx_(0,5) = 0;
        _hx_(1,5) = 0;
        _hx_(2,5) = 0;
        _hx_(3,5) = 0;
        _hx_(4,5) = 0;
        _hx_(5,5) = 0;
        _hx_(6,5) = _hx_(5,6);
        _hx_(7,5) = _hx_(5,7);
        _hx_(8,5) = _hx_(5,8);
        _hx_(0,6) = 0;
        _hx_(1,6) = 0;
        _hx_(2,6) = 0;
        _hx_(3,6) = 0;
        _hx_(4,6) = 0;
        _hx_(5,6) = 0;
        _hx_(6,6) = 0;
        _hx_(7,6) = _hx_(6,7);
        _hx_(8,6) = _hx_(6,8);
        _hx_(0,7) = 0;
        _hx_(1,7) = 0;
        _hx_(2,7) = 0;
        _hx_(3,7) = 0;
        _hx_(4,7) = 0;
        _hx_(5,7) = 0;
        _hx_(6,7) = 0;
        _hx_(7,7) = 0;
        _hx_(8,7) = _hx_(7,8);
        _hx_(0,8) = 0;
        _hx_(1,8) = 0;
        _hx_(2,8) = 0;
        _hx_(3,8) = 0;
        _hx_(4,8) = 0;
        _hx_(5,8) = 0;
        _hx_(6,8) = 0;
        _hx_(7,8) = 0;
        _hx_(8,8) = 0;
    }

};

} // namespace tycho::astro
