// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_crtbp_dynamics.py — do not edit manually.
// =============================================================================
#pragma once
#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct CRTBPDynamics
    : VectorFunction<CRTBPDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<CRTBPDynamics, 9, 6, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu_; // CR3BP Mass Ratio
    static constexpr bool is_vectorizable = true;

    // Precomputed from constructor parameters
    double pc0_;
    double pc1_;
    double pc2_;

    CRTBPDynamics() {
        this->set_io_rows(9, 6);
    }
    CRTBPDynamics(double mu)
        : mu_(mu) {
        this->set_io_rows(9, 6);
        pc0_ = mu_ - 1;
        pc1_ = 3*mu_;
        pc2_ = 5*mu_;
    }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = Scalar((x1*x1) + (x2*x2) + pow(mu_ + x0, 2));
        Scalar _hp1_ = Scalar((x1*x1) + (x2*x2) + pow(mu_ + x0 - 1, 2));
        Scalar x9 = Scalar(mu_ + x0);
        Scalar x10 = Scalar(pc0_/(sqrt(_hp0_)*_hp0_));
        Scalar x11 = Scalar(mu_/(sqrt(_hp1_)*_hp1_));
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = x0 + x10*x9 - x11*(x9 - 1) + 2*x4 + x6;
        _fx_[4] = x1*x10 - x1*x11 + x1 - 2*x3 + x7;
        _fx_[5] = x10*x2 - x11*x2 + x8;
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_,
                         CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar _hp0_ = Scalar((x1*x1) + (x2*x2) + pow(mu_ + x0, 2));
        Scalar _hp1_ = Scalar((x1*x1) + (x2*x2) + pow(mu_ + x0 - 1, 2));
        Scalar x9 = Scalar(mu_ + x0);
        Scalar x10 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_));
        Scalar x11 = Scalar(pc0_*x10);
        Scalar x12 = x9 - 1;
        Scalar x13 = Scalar(mu_/(sqrt(_hp1_)*_hp1_));
        Scalar x14 = Scalar(pc1_ + 3*x0);
        Scalar x15 = -x14;
        Scalar x16 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_*_hp0_));
        Scalar x17 = Scalar(pc0_*x16);
        Scalar x18 = (Scalar(1.0)/(sqrt(_hp1_)*_hp1_*_hp1_));
        Scalar x19 = Scalar(mu_*x18*(3 - x14));
        Scalar x20 = x11 - x13 + 1;
        Scalar x21 = 3*x17;
        Scalar x22 = x21*x9;
        Scalar x23 = Scalar(pc1_*x18);
        Scalar x24 = x12*x23;
        Scalar x25 = (x1*x1);
        Scalar x26 = x1*x2;
        Scalar x27 = -x21*x26 + x23*x26;
        Scalar x28 = (x2*x2);
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = x0 + x11*x9 - x12*x13 + 2*x4 + x6;
        _fx_[4] = x1*x11 - x1*x13 + x1 - 2*x3 + x7;
        _fx_[5] = x11*x2 - x13*x2 + x8;
        
        _jx_(0,0) = 0;
        _jx_(1,0) = 0;
        _jx_(2,0) = 0;
        _jx_(3,0) = -x12*x19 + x15*x17*x9 + x20;
        _jx_(4,0) = Scalar(pc0_*x1*x15*x16 - x1*x19);
        _jx_(5,0) = Scalar(pc0_*x15*x16*x2 - x19*x2);
        _jx_(0,1) = 0;
        _jx_(1,1) = 0;
        _jx_(2,1) = 0;
        _jx_(3,1) = -x1*x22 + x1*x24;
        _jx_(4,1) = x20 - x21*x25 + x23*x25;
        _jx_(5,1) = x27;
        _jx_(0,2) = 0;
        _jx_(1,2) = 0;
        _jx_(2,2) = 0;
        _jx_(3,2) = -x2*x22 + x2*x24;
        _jx_(4,2) = x27;
        _jx_(5,2) = Scalar(pc0_*x10 + pc1_*x18*x28 - x13 - x21*x28);
        _jx_(0,3) = 1;
        _jx_(1,3) = 0;
        _jx_(2,3) = 0;
        _jx_(3,3) = 0;
        _jx_(4,3) = -2;
        _jx_(5,3) = 0;
        _jx_(0,4) = 0;
        _jx_(1,4) = 1;
        _jx_(2,4) = 0;
        _jx_(3,4) = 2;
        _jx_(4,4) = 0;
        _jx_(5,4) = 0;
        _jx_(0,5) = 0;
        _jx_(1,5) = 0;
        _jx_(2,5) = 1;
        _jx_(3,5) = 0;
        _jx_(4,5) = 0;
        _jx_(5,5) = 0;
        _jx_(0,6) = 0;
        _jx_(1,6) = 0;
        _jx_(2,6) = 0;
        _jx_(3,6) = 1;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = 0;
        _jx_(1,7) = 0;
        _jx_(2,7) = 0;
        _jx_(3,7) = 0;
        _jx_(4,7) = 1;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = 0;
        _jx_(2,8) = 0;
        _jx_(3,8) = 0;
        _jx_(4,8) = 0;
        _jx_(5,8) = 1;
    }

    template <class InType, class OutType, class JacType,
                 class AdjGradType, class AdjHessType,
                 class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_,
        CVecRef<OutType> fx_,
        CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_,
        CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar _hp0_ = Scalar((x1*x1) + (x2*x2) + pow(mu_ + x0, 2));
        Scalar _hp1_ = Scalar((x1*x1) + (x2*x2) + pow(mu_ + x0 - 1, 2));
        Scalar x9 = Scalar(mu_ + x0);
        Scalar x10 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_));
        Scalar x11 = Scalar(pc0_*x10);
        Scalar x12 = x9 - 1;
        Scalar x13 = Scalar(mu_/(sqrt(_hp1_)*_hp1_));
        Scalar x14 = Scalar(pc1_ + 3*x0);
        Scalar x15 = -x14;
        Scalar x16 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_*_hp0_));
        Scalar x17 = Scalar(pc0_*x16);
        Scalar x18 = x15*x17;
        Scalar x19 = 3 - x14;
        Scalar x20 = (Scalar(1.0)/(sqrt(_hp1_)*_hp1_*_hp1_));
        Scalar x21 = Scalar(mu_*x20);
        Scalar x22 = x19*x21;
        Scalar x23 = x11 - x13 + 1;
        Scalar x24 = -x12*x22 + x18*x9 + x23;
        Scalar x25 = 3*x17;
        Scalar x26 = x25*x9;
        Scalar x27 = Scalar(pc1_*x20);
        Scalar x28 = x1*x27;
        Scalar x29 = -x1*x26 + x12*x28;
        Scalar x30 = x2*x27;
        Scalar x31 = x12*x30 - x2*x26;
        Scalar x32 = Scalar(pc0_*x1*x15*x16 - x1*x22);
        Scalar x33 = (x1*x1);
        Scalar x34 = x23 - x25*x33 + x27*x33;
        Scalar x35 = x1*x25;
        Scalar x36 = x2*x28 - x2*x35;
        Scalar x37 = Scalar(pc0_*x15*x16*x2 - x2*x22);
        Scalar x38 = (x2*x2);
        Scalar x39 = Scalar(pc0_*x10 + pc1_*x20*x38 - x13 - x25*x38);
        Scalar x40 = Scalar(pc2_ + 5*x0);
        Scalar x41 = (Scalar(1.0)/(sqrt(_hp0_)*_hp0_*_hp0_*_hp0_));
        Scalar x42 = Scalar(pc0_*x41);
        Scalar x43 = x15*x42;
        Scalar x44 = -x40*x43;
        Scalar x45 = (Scalar(1.0)/(sqrt(_hp1_)*_hp1_*_hp1_*_hp1_));
        Scalar x46 = Scalar(mu_*x45);
        Scalar x47 = 5 - x40;
        Scalar x48 = x19*x47;
        Scalar x49 = x46*x48;
        Scalar x50 = -x35;
        Scalar x51 = 3*x21;
        Scalar x52 = x1*x51 + x50;
        Scalar x53 = -x2*x25;
        Scalar x54 = x2*x51 + x53;
        Scalar x55 = x12*x46;
        Scalar x56 = x12*x51 - x26;
        Scalar x57 = 5*x43;
        Scalar x58 = x1*x57;
        Scalar x59 = Scalar(pc2_*x19);
        Scalar x60 = x1*x45;
        Scalar x61 = x59*x60;
        Scalar x62 = -x2*x58 + x2*x61;
        Scalar x63 = x28 + x50;
        Scalar x64 = Scalar(-pc0_*x15*x16 + x22);
        Scalar x65 = x12*x2*x45;
        Scalar x66 = x2*x9;
        Scalar x67 = x30 + x53;
        Scalar x68 = Scalar(x42*(-3*pc2_ - 15*x0));
        Scalar x69 = x1*x68;
        Scalar x70 = Scalar(pc1_*x47);
        Scalar x71 = x60*x70;
        Scalar x72 = -x2*x69 + x2*x71;
        Scalar x73 = 9*x1;
        Scalar x74 = 15*(x1*x1*x1);
        Scalar x75 = Scalar(15*mu_);
        Scalar x76 = x33*x45*x75;
        Scalar x77 = 15*x42;
        Scalar x78 = x33*x77;
        Scalar x79 = -x2*x76 + x2*x78 + x54;
        Scalar x80 = x38*x45*x75;
        Scalar x81 = x38*x77;
        Scalar x82 = -x1*x80 + x1*x81 + x52;
        Scalar x83 = Scalar(LM3*(15*pc0_*x1*x2*x41*x9 - 15*x1*x2*x55) + LM4*x79 + LM5*x82);
        Scalar x84 = 9*x2;
        Scalar x85 = 15*(x2*x2*x2);
        
        _fx_[0] = x3;
        _fx_[1] = x4;
        _fx_[2] = x5;
        _fx_[3] = x0 + x11*x9 - x12*x13 + 2*x4 + x6;
        _fx_[4] = x1*x11 - x1*x13 + x1 - 2*x3 + x7;
        _fx_[5] = x11*x2 - x13*x2 + x8;
        
        _jx_(0,0) = 0;
        _jx_(1,0) = 0;
        _jx_(2,0) = 0;
        _jx_(3,0) = x24;
        _jx_(4,0) = x32;
        _jx_(5,0) = x37;
        _jx_(0,1) = 0;
        _jx_(1,1) = 0;
        _jx_(2,1) = 0;
        _jx_(3,1) = x29;
        _jx_(4,1) = x34;
        _jx_(5,1) = x36;
        _jx_(0,2) = 0;
        _jx_(1,2) = 0;
        _jx_(2,2) = 0;
        _jx_(3,2) = x31;
        _jx_(4,2) = x36;
        _jx_(5,2) = x39;
        _jx_(0,3) = 1;
        _jx_(1,3) = 0;
        _jx_(2,3) = 0;
        _jx_(3,3) = 0;
        _jx_(4,3) = -2;
        _jx_(5,3) = 0;
        _jx_(0,4) = 0;
        _jx_(1,4) = 1;
        _jx_(2,4) = 0;
        _jx_(3,4) = 2;
        _jx_(4,4) = 0;
        _jx_(5,4) = 0;
        _jx_(0,5) = 0;
        _jx_(1,5) = 0;
        _jx_(2,5) = 1;
        _jx_(3,5) = 0;
        _jx_(4,5) = 0;
        _jx_(5,5) = 0;
        _jx_(0,6) = 0;
        _jx_(1,6) = 0;
        _jx_(2,6) = 0;
        _jx_(3,6) = 1;
        _jx_(4,6) = 0;
        _jx_(5,6) = 0;
        _jx_(0,7) = 0;
        _jx_(1,7) = 0;
        _jx_(2,7) = 0;
        _jx_(3,7) = 0;
        _jx_(4,7) = 1;
        _jx_(5,7) = 0;
        _jx_(0,8) = 0;
        _jx_(1,8) = 0;
        _jx_(2,8) = 0;
        _jx_(3,8) = 0;
        _jx_(4,8) = 0;
        _jx_(5,8) = 1;
        
        _gx_[0] = LM3*x24 + LM4*x32 + LM5*x37;
        _gx_[1] = LM3*x29 + LM4*x34 + LM5*x36;
        _gx_[2] = LM3*x31 + LM4*x36 + LM5*x39;
        _gx_[3] = LM0 - 2*LM4;
        _gx_[4] = LM1 + 2*LM3;
        _gx_[5] = LM2;
        _gx_[6] = LM3;
        _gx_[7] = LM4;
        _gx_[8] = LM5;
        
        _hx_(0,0) = LM3*(2*x18 - 2*x22 + x44*x9 - x48*x55 + x56) + LM4*(x1*x44 - x1*x49 + x52) + LM5*(x2*x44 - x2*x49 + x54);
        _hx_(1,0) = _hx_(0,1);
        _hx_(2,0) = _hx_(0,2);
        _hx_(3,0) = _hx_(0,3);
        _hx_(4,0) = _hx_(0,4);
        _hx_(5,0) = _hx_(0,5);
        _hx_(6,0) = _hx_(0,6);
        _hx_(7,0) = _hx_(0,7);
        _hx_(8,0) = _hx_(0,8);
        _hx_(0,1) = Scalar(LM3*(x12*x61 - x58*x9 + x63) + LM4*(pc2_*x19*x33*x45 - x33*x57 - x64) + LM5*x62);
        _hx_(1,1) = LM3*(-x12*x76 + x56 + x78*x9) + LM4*(-x17*x73 + x21*x73 + x42*x74 - x46*x74) + LM5*x79;
        _hx_(2,1) = _hx_(1,2);
        _hx_(3,1) = _hx_(1,3);
        _hx_(4,1) = _hx_(1,4);
        _hx_(5,1) = _hx_(1,5);
        _hx_(6,1) = _hx_(1,6);
        _hx_(7,1) = _hx_(1,7);
        _hx_(8,1) = _hx_(1,8);
        _hx_(0,2) = Scalar(LM3*(-x57*x66 + x59*x65 + x67) + LM4*x62 + LM5*(pc2_*x19*x38*x45 - x38*x57 - x64));
        _hx_(1,2) = x83;
        _hx_(2,2) = LM3*(-x12*x80 + x56 + x81*x9) + LM4*x82 + LM5*(-x17*x84 + x21*x84 + x42*x85 - x46*x85);
        _hx_(3,2) = _hx_(2,3);
        _hx_(4,2) = _hx_(2,4);
        _hx_(5,2) = _hx_(2,5);
        _hx_(6,2) = _hx_(2,6);
        _hx_(7,2) = _hx_(2,7);
        _hx_(8,2) = _hx_(2,8);
        _hx_(0,3) = 0;
        _hx_(1,3) = 0;
        _hx_(2,3) = 0;
        _hx_(3,3) = 0;
        _hx_(4,3) = _hx_(3,4);
        _hx_(5,3) = _hx_(3,5);
        _hx_(6,3) = _hx_(3,6);
        _hx_(7,3) = _hx_(3,7);
        _hx_(8,3) = _hx_(3,8);
        _hx_(0,4) = 0;
        _hx_(1,4) = 0;
        _hx_(2,4) = 0;
        _hx_(3,4) = 0;
        _hx_(4,4) = 0;
        _hx_(5,4) = _hx_(4,5);
        _hx_(6,4) = _hx_(4,6);
        _hx_(7,4) = _hx_(4,7);
        _hx_(8,4) = _hx_(4,8);
        _hx_(0,5) = 0;
        _hx_(1,5) = 0;
        _hx_(2,5) = 0;
        _hx_(3,5) = 0;
        _hx_(4,5) = 0;
        _hx_(5,5) = 0;
        _hx_(6,5) = _hx_(5,6);
        _hx_(7,5) = _hx_(5,7);
        _hx_(8,5) = _hx_(5,8);
        _hx_(0,6) = 0;
        _hx_(1,6) = 0;
        _hx_(2,6) = 0;
        _hx_(3,6) = 0;
        _hx_(4,6) = 0;
        _hx_(5,6) = 0;
        _hx_(6,6) = 0;
        _hx_(7,6) = _hx_(6,7);
        _hx_(8,6) = _hx_(6,8);
        _hx_(0,7) = 0;
        _hx_(1,7) = 0;
        _hx_(2,7) = 0;
        _hx_(3,7) = 0;
        _hx_(4,7) = 0;
        _hx_(5,7) = 0;
        _hx_(6,7) = 0;
        _hx_(7,7) = 0;
        _hx_(8,7) = _hx_(7,8);
        _hx_(0,8) = 0;
        _hx_(1,8) = 0;
        _hx_(2,8) = 0;
        _hx_(3,8) = 0;
        _hx_(4,8) = 0;
        _hx_(5,8) = 0;
        _hx_(6,8) = 0;
        _hx_(7,8) = 0;
        _hx_(8,8) = 0;
    }

};

} // namespace tycho::astro
