// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_mee_to_cartesian.py — do not edit manually.
// =============================================================================
#pragma once
#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct MEEToCartesian : VectorFunction<MEEToCartesian, 6, 6, DenseDerivativeMode::Analytic,
                                       DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<MEEToCartesian, 6, 6, DenseDerivativeMode::Analytic,
                                DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu; // Gravitational Parameter
    static constexpr bool is_vectorizable = true;

    MEEToCartesian() { this->set_io_rows(6, 6); }
    MEEToCartesian(double mu) : mu(mu) { this->set_io_rows(6, 6); }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_, CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = cos(x5);
        Scalar x7 = (x3 * x3);
        Scalar x8 = (x4 * x4);
        Scalar x9 = x7 - x8;
        Scalar x10 = sin(x5);
        Scalar x11 = x10 * x3;
        Scalar x12 = 2 * x4;
        Scalar x13 = x11 * x12 + x6 * x9;
        Scalar x14 = 1.0 / (x7 + x8 + 1);
        Scalar x15 = x0 * x14 / (x1 * x6 + x10 * x2 + 1);
        Scalar x16 = x4 * x6;
        Scalar x17 = 2 * x3;
        Scalar x18 = x16 * x17;
        Scalar x19 = x10 * x9;
        Scalar x20 = x1 * x3;
        Scalar x21 = Scalar(x14 * sqrt(mu / x0));
        Scalar x22 = x2 * x4;

        _fx_[0] = x15 * (x13 + x6);
        _fx_[1] = x15 * (x10 + x18 - x19);
        _fx_[2] = 2 * x15 * (x11 - x16);
        _fx_[3] = -x21 * (x10 - x12 * x20 - x18 + x19 + x2 * x9 + x2);
        _fx_[4] = -x21 * (x1 * x9 - x1 + x13 + x17 * x22 - x6);
        _fx_[5] = 2 * x21 * (x10 * x4 + x20 + x22 + x3 * x6);
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_, CVecRef<OutType> fx_,
                                      CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = cos(x5);
        Scalar x7 = (x3 * x3);
        Scalar x8 = (x4 * x4);
        Scalar x9 = x7 - x8;
        Scalar x10 = sin(x5);
        Scalar x11 = x10 * x3;
        Scalar x12 = 2 * x11;
        Scalar x13 = x12 * x4 + x6 * x9;
        Scalar x14 = x13 + x6;
        Scalar x15 = x8 + 1;
        Scalar x16 = x15 + x7;
        Scalar x17 = 1.0 / x16;
        Scalar x18 = x1 * x6 + x10 * x2 + 1;
        Scalar x19 = 1.0 / x18;
        Scalar x20 = x17 * x19;
        Scalar x21 = x14 * x20;
        Scalar x22 = x4 * x6;
        Scalar x23 = 2 * x22;
        Scalar x24 = x23 * x3;
        Scalar x25 = x10 * x9;
        Scalar x26 = x10 + x24 - x25;
        Scalar x27 = x20 * x26;
        Scalar x28 = x0 * x20;
        Scalar x29 = x11 - x22;
        Scalar x30 = 2 * x29;
        Scalar x31 = x1 * x3;
        Scalar x32 = 2 * x4;
        Scalar x33 = x10 + x2;
        Scalar x34 = -x24 + x25;
        Scalar x35 = x2 * x9 - x31 * x32 + x33 + x34;
        Scalar x36 = 1.0 / x0;
        Scalar x37 = Scalar(sqrt(mu * x36));
        Scalar x38 = x17 * x37;
        Scalar x39 = x35 * x38;
        Scalar x40 = x2 * x4;
        Scalar x41 = 2 * x3;
        Scalar x42 = x13 - x6;
        Scalar x43 = x1 * x9 - x1 + x40 * x41 + x42;
        Scalar x44 = x38 * x43;
        Scalar x45 = x3 * x6;
        Scalar x46 = x10 * x4;
        Scalar x47 = x45 + x46;
        Scalar x48 = x31 + x40 + x47;
        Scalar x49 = x38 * x48;
        Scalar x50 = x0 * x14;
        Scalar x51 = x17 / (x18 * x18);
        Scalar x52 = x50 * x51;
        Scalar x53 = 2 * x45 + 2 * x46;
        Scalar x54 = -x0 * x17 * x19 * x53;
        Scalar x55 = (Scalar(1.0) / (x16 * x16));
        Scalar x56 = x19 * x55;
        Scalar x57 = x50 * x56;
        Scalar x58 = x12 - x23;
        Scalar x59 = x1 * x10 - x2 * x6;
        Scalar x60 = x0 * x26;
        Scalar x61 = x51 * x60;
        Scalar x62 = x56 * x60;
        Scalar x63 = x0 * x30 * x51;
        Scalar x64 = 4 * x3;
        Scalar x65 = x0 * x29 * x56;
        Scalar x66 = 2 * x28;
        Scalar x67 = 4 * x4;
        Scalar x68 = (1.0 / 2.0) * x36;
        Scalar x69 = x32 * x38;
        Scalar x70 = x3 * x69;
        Scalar x71 = -x38 * (-x1 * x32 + x12 + 2 * x2 * x3 - x23);
        Scalar x72 = x37 * x55;
        Scalar x73 = x35 * x72;
        Scalar x74 = 2 * x31 + 2 * x40 + x53;
        Scalar x75 = x43 * x72;
        Scalar x76 = x48 * x72;

        _fx_[0] = x0 * x21;
        _fx_[1] = x0 * x27;
        _fx_[2] = x28 * x30;
        _fx_[3] = -x39;
        _fx_[4] = -x44;
        _fx_[5] = 2 * x49;

        _jx_(0, 0) = x21;
        _jx_(1, 0) = x27;
        _jx_(2, 0) = x20 * x30;
        _jx_(3, 0) = x39 * x68;
        _jx_(4, 0) = x44 * x68;
        _jx_(5, 0) = -x36 * x49;
        _jx_(0, 1) = -x52 * x6;
        _jx_(1, 1) = -x6 * x61;
        _jx_(2, 1) = -x6 * x63;
        _jx_(3, 1) = x70;
        _jx_(4, 1) = -x38 * (-x15 + x7);
        _jx_(5, 1) = x38 * x41;
        _jx_(0, 2) = -x10 * x52;
        _jx_(1, 2) = -x10 * x61;
        _jx_(2, 2) = -x10 * x63;
        _jx_(3, 2) = -x38 * (x9 + 1);
        _jx_(4, 2) = -x70;
        _jx_(5, 2) = x69;
        _jx_(0, 3) = -x41 * x57 - x54;
        _jx_(1, 3) = -x0 * x17 * x19 * x58 - x41 * x62;
        _jx_(2, 3) = 2 * x0 * x10 * x17 * x19 - x64 * x65;
        _jx_(3, 3) = x41 * x73 + x71;
        _jx_(4, 3) = -x38 * x74 + x41 * x75;
        _jx_(5, 3) = 2 * x17 * x37 * (x1 + x6) - x64 * x76;
        _jx_(0, 4) = x0 * x17 * x19 * x58 - x32 * x57;
        _jx_(1, 4) = -x32 * x62 - x54;
        _jx_(2, 4) = -x6 * x66 - x65 * x67;
        _jx_(3, 4) = x32 * x73 + x38 * x74;
        _jx_(4, 4) = x32 * x75 + x71;
        _jx_(5, 4) = 2 * x17 * x33 * x37 - x67 * x76;
        _jx_(0, 5) = x28 * (-x10 - x34) + x52 * x59;
        _jx_(1, 5) = -x28 * x42 + x59 * x61;
        _jx_(2, 5) = x47 * x66 + x59 * x63;
        _jx_(3, 5) = -x14 * x38;
        _jx_(4, 5) = -x26 * x38;
        _jx_(5, 5) = -2 * x29 * x38;
    }

    template <class InType, class OutType, class JacType, class AdjGradType, class AdjHessType,
              class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_, CVecRef<OutType> fx_, CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_, CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar x6 = cos(x5);
        Scalar x7 = (x3 * x3);
        Scalar x8 = (x4 * x4);
        Scalar x9 = x7 - x8;
        Scalar x10 = sin(x5);
        Scalar x11 = x10 * x3;
        Scalar x12 = 2 * x11;
        Scalar x13 = x12 * x4 + x6 * x9;
        Scalar x14 = x13 + x6;
        Scalar x15 = x8 + 1;
        Scalar x16 = x15 + x7;
        Scalar x17 = 1.0 / x16;
        Scalar x18 = x1 * x6 + x10 * x2;
        Scalar x19 = x18 + 1;
        Scalar x20 = 1.0 / x19;
        Scalar x21 = x17 * x20;
        Scalar x22 = x14 * x21;
        Scalar x23 = x4 * x6;
        Scalar x24 = 2 * x23;
        Scalar x25 = x24 * x3;
        Scalar x26 = x10 * x9;
        Scalar x27 = x10 + x25 - x26;
        Scalar x28 = x21 * x27;
        Scalar x29 = x11 - x23;
        Scalar x30 = 2 * x21;
        Scalar x31 = x29 * x30;
        Scalar x32 = x1 * x3;
        Scalar x33 = 2 * x32;
        Scalar x34 = x10 + x2;
        Scalar x35 = -x25 + x26;
        Scalar x36 = x2 * x9 - x33 * x4 + x34 + x35;
        Scalar x37 = 1.0 / x0;
        Scalar x38 = Scalar(sqrt(mu * x37));
        Scalar x39 = x17 * x38;
        Scalar x40 = x36 * x39;
        Scalar x41 = x2 * x4;
        Scalar x42 = 2 * x41;
        Scalar x43 = x13 - x6;
        Scalar x44 = x1 * x9 - x1 + x3 * x42 + x43;
        Scalar x45 = x39 * x44;
        Scalar x46 = x3 * x6;
        Scalar x47 = x10 * x4;
        Scalar x48 = x46 + x47;
        Scalar x49 = x32 + x41 + x48;
        Scalar x50 = 2 * x39;
        Scalar x51 = (Scalar(1.0) / (x19 * x19));
        Scalar x52 = x17 * x51;
        Scalar x53 = x0 * x52;
        Scalar x54 = x14 * x53;
        Scalar x55 = x54 * x6;
        Scalar x56 = x10 * x54;
        Scalar x57 = -x56;
        Scalar x58 = 2 * x46;
        Scalar x59 = 2 * x47;
        Scalar x60 = x58 + x59;
        Scalar x61 = -x0 * x17 * x20 * x60;
        Scalar x62 = x14 * x3;
        Scalar x63 = (Scalar(1.0) / (x16 * x16));
        Scalar x64 = x20 * x63;
        Scalar x65 = 2 * x64;
        Scalar x66 = x62 * x65;
        Scalar x67 = -x0 * x66 - x61;
        Scalar x68 = x12 - x24;
        Scalar x69 = x14 * x65;
        Scalar x70 = x0 * x69;
        Scalar x71 = x0 * x17 * x20 * x68 - x4 * x70;
        Scalar x72 = -x10 - x35;
        Scalar x73 = x21 * x72;
        Scalar x74 = x1 * x10;
        Scalar x75 = x2 * x6;
        Scalar x76 = x74 - x75;
        Scalar x77 = x52 * x76;
        Scalar x78 = x14 * x77;
        Scalar x79 = x0 * x73 + x0 * x78;
        Scalar x80 = x27 * x53;
        Scalar x81 = x6 * x80;
        Scalar x82 = x10 * x80;
        Scalar x83 = -x82;
        Scalar x84 = -x68;
        Scalar x85 = -x0 * x17 * x20 * x84;
        Scalar x86 = x27 * x65;
        Scalar x87 = x3 * x86;
        Scalar x88 = -x0 * x87 - x85;
        Scalar x89 = x0 * x86;
        Scalar x90 = -x4 * x89 - x61;
        Scalar x91 = -x43;
        Scalar x92 = x21 * x91;
        Scalar x93 = x27 * x77;
        Scalar x94 = x0 * x92 + x0 * x93;
        Scalar x95 = 2 * x6;
        Scalar x96 = x29 * x53;
        Scalar x97 = x95 * x96;
        Scalar x98 = 2 * x10;
        Scalar x99 = x96 * x98;
        Scalar x100 = -x99;
        Scalar x101 = x0 * x21 * x98;
        Scalar x102 = -x101;
        Scalar x103 = 4 * x64;
        Scalar x104 = x29 * x3;
        Scalar x105 = x103 * x104;
        Scalar x106 = -x0 * x105 - x102;
        Scalar x107 = x0 * x21;
        Scalar x108 = x107 * x95;
        Scalar x109 = x103 * x29;
        Scalar x110 = x0 * x109;
        Scalar x111 = -x108 - x110 * x4;
        Scalar x112 = x30 * x48;
        Scalar x113 = x0 * x77;
        Scalar x114 = 2 * x29;
        Scalar x115 = x0 * x112 + x113 * x114;
        Scalar x116 = (1.0 / 2.0) * x37;
        Scalar x117 = x116 * x40;
        Scalar x118 = x3 * x50;
        Scalar x119 = x118 * x4;
        Scalar x120 = x9 + 1;
        Scalar x121 = x120 * x39;
        Scalar x122 = 2 * x1;
        Scalar x123 = x12 - x122 * x4 + 2 * x2 * x3 - x24;
        Scalar x124 = -x123 * x39;
        Scalar x125 = x38 * x63;
        Scalar x126 = 2 * x125;
        Scalar x127 = x126 * x36;
        Scalar x128 = x124 + x127 * x3;
        Scalar x129 = x33 + x42 + x60;
        Scalar x130 = -x129;
        Scalar x131 = x127 * x4 - x130 * x39;
        Scalar x132 = x14 * x39;
        Scalar x133 = x116 * x45;
        Scalar x134 = -x15 + x7;
        Scalar x135 = x134 * x39;
        Scalar x136 = x126 * x44;
        Scalar x137 = -x129 * x39 + x136 * x3;
        Scalar x138 = x124 + x136 * x4;
        Scalar x139 = x27 * x39;
        Scalar x140 = x37 * x39;
        Scalar x141 = x140 * x49;
        Scalar x142 = x4 * x50;
        Scalar x143 = x1 + x6;
        Scalar x144 = 4 * x125;
        Scalar x145 = x144 * x49;
        Scalar x146 = 2 * x143 * x17 * x38 - x145 * x3;
        Scalar x147 = -x145 * x4 + 2 * x17 * x34 * x38;
        Scalar x148 = -x29;
        Scalar x149 = x148 * x50;
        Scalar x150 = LM0 * x55 + LM1 * x81 + LM2 * x97;
        Scalar x151 = LM2 * x99;
        Scalar x152 = LM0 * x56;
        Scalar x153 = LM1 * x82;
        Scalar x154 = LM3 * x132;
        Scalar x155 = LM4 * x139;
        Scalar x156 = (Scalar(1.0) / (x0 * x0));
        Scalar x157 = (3.0 / 4.0) * x156;
        Scalar x158 = LM5 * x140;
        Scalar x159 = x3 * x4;
        Scalar x160 = LM2 * x29;
        Scalar x161 = x160 * x52;
        Scalar x162 = x52 * x6;
        Scalar x163 = LM0 * x14;
        Scalar x164 = LM1 * x27;
        Scalar x165 = -LM3 * x140 * x159 + (1.0 / 2.0) * LM4 * x134 * x17 * x37 * x38 - x158 * x3 -
                      x161 * x95 - x162 * x163 - x162 * x164;
        Scalar x166 = x10 * x52;
        Scalar x167 = (1.0 / 2.0) * LM3 * x120 * x17 * x37 * x38 + LM4 * x17 * x3 * x37 * x38 * x4 -
                      x158 * x4 - x161 * x98 - x163 * x166 - x164 * x166;
        Scalar x168 = x140 * x143;
        Scalar x169 = x3 * x65;
        Scalar x170 = x125 * x3;
        Scalar x171 = x170 * x37;
        Scalar x172 = x171 * x36;
        Scalar x173 = x171 * x44;
        Scalar x174 = x140 * x34;
        Scalar x175 = x21 * x95;
        Scalar x176 = x109 * x4;
        Scalar x177 = x4 * x65;
        Scalar x178 = x125 * x4;
        Scalar x179 = x178 * x37;
        Scalar x180 = x179 * x36;
        Scalar x181 = x179 * x44;
        Scalar x182 = x114 * x77;
        Scalar x183 = x116 * x154 + x116 * x155 - x148 * x158;
        Scalar x184 = (x6 * x6);
        Scalar x185 = x17 / (x19 * x19 * x19);
        Scalar x186 = x0 * x185;
        Scalar x187 = x184 * x186;
        Scalar x188 = 4 * x160;
        Scalar x189 = 2 * x187;
        Scalar x190 = x186 * x6;
        Scalar x191 = x190 * x98;
        Scalar x192 = x10 * x188 * x190 + x163 * x191 + x164 * x191;
        Scalar x193 = x144 * x7;
        Scalar x194 = x193 * x4;
        Scalar x195 = x126 * x3;
        Scalar x196 = x134 * x195;
        Scalar x197 = x53 * x6;
        Scalar x198 = x197 * x60;
        Scalar x199 = x197 * x84;
        Scalar x200 = x197 * x98;
        Scalar x201 = LM2 * x200;
        Scalar x202 = x51 * x63;
        Scalar x203 = x202 * x58;
        Scalar x204 = x0 * x203;
        Scalar x205 = x0 * x188 * x202;
        Scalar x206 = LM5 * x50;
        Scalar x207 = LM3 * x142 - LM4 * x118 + x206;
        Scalar x208 = x144 * x3;
        Scalar x209 = LM5 * x208 * x4;
        Scalar x210 = -x209;
        Scalar x211 = x144 * x8;
        Scalar x212 = x211 * x3;
        Scalar x213 = 2 * x53;
        Scalar x214 = x184 * x213;
        Scalar x215 = x126 * x4;
        Scalar x216 = x134 * x215;
        Scalar x217 = x197 * x68;
        Scalar x218 = x202 * x24;
        Scalar x219 = x0 * x218;
        Scalar x220 = LM3 * x118 + LM4 * x142;
        Scalar x221 = x48 * x53;
        Scalar x222 = x221 * x95;
        Scalar x223 = x197 * x91;
        Scalar x224 = x185 * (2 * x74 - 2 * x75);
        Scalar x225 = x0 * x224;
        Scalar x226 = x160 * x225;
        Scalar x227 = x197 * x72;
        Scalar x228 = x225 * x6;
        Scalar x229 = (x10 * x10);
        Scalar x230 = x186 * x229;
        Scalar x231 = 2 * x230;
        Scalar x232 = x213 * x229;
        Scalar x233 = x10 * x53;
        Scalar x234 = x233 * x60;
        Scalar x235 = x233 * x84;
        Scalar x236 = x120 * x215;
        Scalar x237 = x233 * x68;
        Scalar x238 = x202 * x59;
        Scalar x239 = x0 * x238;
        Scalar x240 = x233 * x72;
        Scalar x241 = x233 * x91;
        Scalar x242 = x221 * x98;
        Scalar x243 = x10 * x225;
        Scalar x244 = x37 * x49;
        Scalar x245 = -x17 * x20 * x60;
        Scalar x246 = -1.0 / 2.0 * x123 * x17 * x37 * x38;
        Scalar x247 = -2 * x17 * x38;
        Scalar x248 = -2 * x17 * x38 * x4 + x194;
        Scalar x249 = -x118;
        Scalar x250 = x0 * x29;
        Scalar x251 = 4 * x202;
        Scalar x252 = x250 * x251;
        Scalar x253 = -x198;
        Scalar x254 = x0 * x14;
        Scalar x255 = x0 * x27;
        Scalar x256 = -x234;
        Scalar x257 = x12 * x202;
        Scalar x258 = (Scalar(1.0) / (x16 * x16 * x16));
        Scalar x259 = 8 * x0;
        Scalar x260 = x259 * x64;
        Scalar x261 = x0 * x60;
        Scalar x262 = x103 * x3;
        Scalar x263 = x20 * x258;
        Scalar x264 = x0 * x84;
        Scalar x265 = 2 * x2 + x98;
        Scalar x266 = x265 * x39;
        Scalar x267 = -2 * x36 * x38 * x63;
        Scalar x268 = x258 * x38;
        Scalar x269 = 8 * x268 * x7;
        Scalar x270 = x122 + x95;
        Scalar x271 = -2 * x38 * x44 * x63;
        Scalar x272 = x144 * x4;
        Scalar x273 = x0 * x103;
        Scalar x274 = x0 * x104;
        Scalar x275 = x0 * x169;
        Scalar x276 = x259 * x263;
        Scalar x277 = -x270 * x39;
        Scalar x278 = 8 * x159 * x268;
        Scalar x279 =
            LM0 * (x101 - x177 * x261 - x275 * x68 + x276 * x4 * x62) +
            LM1 * (x108 + x159 * x27 * x276 - x169 * x261 - x177 * x264) +
            LM2 * (16 * x263 * x274 * x4 + x273 * x46 - x273 * x47) +
            LM3 * (2 * x123 * x38 * x4 * x63 + 2 * x130 * x3 * x38 * x63 - x277 - x278 * x36) +
            LM4 * (2 * x123 * x3 * x38 * x63 + 2 * x129 * x38 * x4 * x63 - x266 - x278 * x44) +
            LM5 * (-x143 * x272 - x208 * x34 + 16 * x258 * x3 * x38 * x4 * x49);
        Scalar x280 = x39 * x60;
        Scalar x281 = -x280;
        Scalar x282 = x126 * x62;
        Scalar x283 = x39 * x84;
        Scalar x284 = x195 * x27;
        Scalar x285 = x39 * x98;
        Scalar x286 = x148 * x208;
        Scalar x287 = 2 * x202;
        Scalar x288 = x0 * x287;
        Scalar x289 = -x0 * x17 * x51 * x60 * x76 + x85;
        Scalar x290 = x27 * x76;
        Scalar x291 = x288 * x290;
        Scalar x292 =
            LM0 * (-x275 * x72 - x288 * x62 * x76 - x289) +
            LM1 * (-x0 * x17 * x20 * x60 + x0 * x17 * x51 * x76 * x84 - x275 * x91 - x291 * x3) +
            LM2 * (2 * x0 * x10 * x17 * x51 * x76 - x0 * x262 * x48 + x108 - x251 * x274 * x76);
        Scalar x293 = x212 + x249;
        Scalar x294 = x263 * x8;
        Scalar x295 = x273 * x4;
        Scalar x296 = 8 * x268 * x8;
        Scalar x297 = x39 * x68;
        Scalar x298 = x14 * x215;
        Scalar x299 = x215 * x27;
        Scalar x300 = x148 * x272;
        Scalar x301 = x0 * x177;
        Scalar x302 = x254 * x76;
        Scalar x303 = LM0 * (x0 * x17 * x51 * x68 * x76 - x287 * x302 * x4 - x301 * x72 - x61) +
                      LM1 * (-x289 - x291 * x4 - x301 * x91) +
                      LM2 * (-x102 - x113 * x95 - x252 * x4 * x76 - x295 * x48);
        Scalar x304 = 4 * x185 * x250 * x76;
        Scalar x305 = x185 * x302;
        Scalar x306 = x186 * x290;
        Scalar x307 = 2 * x113;

        _fx_[0] = x0 * x22;
        _fx_[1] = x0 * x28;
        _fx_[2] = x0 * x31;
        _fx_[3] = -x40;
        _fx_[4] = -x45;
        _fx_[5] = x49 * x50;

        _jx_(0, 0) = x22;
        _jx_(1, 0) = x28;
        _jx_(2, 0) = x31;
        _jx_(3, 0) = x117;
        _jx_(4, 0) = x133;
        _jx_(5, 0) = -x141;
        _jx_(0, 1) = -x55;
        _jx_(1, 1) = -x81;
        _jx_(2, 1) = -x97;
        _jx_(3, 1) = x119;
        _jx_(4, 1) = -x135;
        _jx_(5, 1) = x118;
        _jx_(0, 2) = x57;
        _jx_(1, 2) = x83;
        _jx_(2, 2) = x100;
        _jx_(3, 2) = -x121;
        _jx_(4, 2) = -x119;
        _jx_(5, 2) = x142;
        _jx_(0, 3) = x67;
        _jx_(1, 3) = x88;
        _jx_(2, 3) = x106;
        _jx_(3, 3) = x128;
        _jx_(4, 3) = x137;
        _jx_(5, 3) = x146;
        _jx_(0, 4) = x71;
        _jx_(1, 4) = x90;
        _jx_(2, 4) = x111;
        _jx_(3, 4) = x131;
        _jx_(4, 4) = x138;
        _jx_(5, 4) = x147;
        _jx_(0, 5) = x79;
        _jx_(1, 5) = x94;
        _jx_(2, 5) = x115;
        _jx_(3, 5) = -x132;
        _jx_(4, 5) = -x139;
        _jx_(5, 5) = x149;

        _gx_[0] = LM0 * x22 + LM1 * x28 + LM2 * x31 + LM3 * x117 + LM4 * x133 - LM5 * x141;
        _gx_[1] = 2 * LM3 * x17 * x3 * x38 * x4 - LM4 * x135 + 2 * LM5 * x17 * x3 * x38 - x150;
        _gx_[2] = -LM3 * x121 - LM4 * x119 + 2 * LM5 * x17 * x38 * x4 - x151 - x152 - x153;
        _gx_[3] = LM0 * x67 + LM1 * x88 + LM2 * x106 + LM3 * x128 + LM4 * x137 + LM5 * x146;
        _gx_[4] = LM0 * x71 + LM1 * x90 + LM2 * x111 + LM3 * x131 + LM4 * x138 + LM5 * x147;
        _gx_[5] = LM0 * x79 + LM1 * x94 + LM2 * x115 + LM5 * x149 - x154 - x155;

        _hx_(0, 0) =
            -LM3 * x157 * x40 - LM4 * x157 * x45 + (3.0 / 2.0) * LM5 * x156 * x17 * x38 * x49;
        _hx_(1, 0) = _hx_(0, 1);
        _hx_(2, 0) = _hx_(0, 2);
        _hx_(3, 0) = _hx_(0, 3);
        _hx_(4, 0) = _hx_(0, 4);
        _hx_(5, 0) = _hx_(0, 5);
        _hx_(0, 1) = x165;
        _hx_(1, 1) = x163 * x189 + x164 * x189 + x187 * x188;
        _hx_(2, 1) = _hx_(1, 2);
        _hx_(3, 1) = _hx_(1, 3);
        _hx_(4, 1) = _hx_(1, 4);
        _hx_(5, 1) = _hx_(1, 5);
        _hx_(0, 2) = x167;
        _hx_(1, 2) = x192;
        _hx_(2, 2) = x163 * x231 + x164 * x231 + x188 * x230;
        _hx_(3, 2) = _hx_(2, 3);
        _hx_(4, 2) = _hx_(2, 4);
        _hx_(5, 2) = _hx_(2, 5);
        _hx_(0, 3) = LM0 * x17 * x20 * x60 + LM1 * x17 * x20 * x84 + 2 * LM2 * x10 * x17 * x20 -
                     LM2 * x105 + (1.0 / 2.0) * LM3 * x123 * x17 * x37 * x38 - LM3 * x172 +
                     (1.0 / 2.0) * LM4 * x129 * x17 * x37 * x38 - LM4 * x173 - LM5 * x168 +
                     2 * LM5 * x3 * x37 * x38 * x49 * x63 - x163 * x169 - x164 * x169;
        _hx_(1, 3) = -LM0 * x198 - LM1 * x199 - LM3 * x194 + LM4 * x196 - LM5 * x193 + x163 * x204 +
                     x164 * x204 - x201 + x205 * x46 + x207;
        _hx_(2, 3) = 2 * LM0 * x0 * x10 * x14 * x3 * x51 * x63 - LM0 * x234 +
                     2 * LM1 * x0 * x10 * x27 * x3 * x51 * x63 - LM1 * x235 +
                     4 * LM2 * x0 * x10 * x29 * x3 * x51 * x63 - LM2 * x232 +
                     2 * LM3 * x120 * x3 * x38 * x63 + 4 * LM4 * x38 * x4 * x63 * x7 - x209 - x220;
        _hx_(3, 3) = LM0 * (x108 + x14 * x259 * x263 * x7 - x261 * x262 - x70) +
                     LM1 * (8 * x0 * x20 * x258 * x27 * x7 - x101 - x262 * x264 - x89) +
                     LM2 * (16 * x0 * x20 * x258 * x29 * x7 - x11 * x260 - x110) +
                     LM3 * (4 * x123 * x3 * x38 * x63 - x266 - x267 - x269 * x36) +
                     LM4 * (4 * x129 * x3 * x38 * x63 - x269 * x44 - x270 * x39 - x271) +
                     LM5 * (-8 * x143 * x170 - x145 + 16 * x258 * x38 * x49 * x7);
        _hx_(4, 3) = _hx_(3, 4);
        _hx_(5, 3) = _hx_(3, 5);
        _hx_(0, 4) = LM0 * x17 * x20 * x68 + LM1 * x17 * x20 * x60 - LM2 * x175 - LM2 * x176 +
                     (1.0 / 2.0) * LM3 * x130 * x17 * x37 * x38 - LM3 * x180 +
                     (1.0 / 2.0) * LM4 * x123 * x17 * x37 * x38 - LM4 * x181 - LM5 * x174 +
                     2 * LM5 * x37 * x38 * x4 * x49 * x63 - x163 * x177 - x164 * x177;
        _hx_(1, 4) = -LM0 * x217 - LM1 * x198 + LM2 * x214 - LM3 * x212 + LM4 * x216 + x163 * x219 +
                     x164 * x219 + x205 * x23 + x210 + x220;
        _hx_(2, 4) = -LM0 * x237 - LM1 * x234 + LM3 * x236 + LM4 * x212 - LM5 * x211 + x163 * x239 +
                     x164 * x239 + x201 + x205 * x47 + x207;
        _hx_(3, 4) = x279;
        _hx_(4, 4) = LM0 * (8 * x0 * x14 * x20 * x258 * x8 - x108 - x295 * x68 - x70) +
                     LM1 * (x101 - x103 * x261 * x4 + x259 * x27 * x294 - x89) +
                     LM2 * (-x110 + x23 * x260 + 16 * x250 * x294) +
                     LM3 * (4 * x130 * x38 * x4 * x63 + x265 * x39 - x267 - x296 * x36) +
                     LM4 * (4 * x123 * x38 * x4 * x63 - x271 - x277 - x296 * x44) +
                     LM5 * (-x145 - 8 * x178 * x34 + 16 * x258 * x38 * x49 * x8);
        _hx_(5, 4) = _hx_(4, 5);
        _hx_(0, 5) = LM0 * x73 + LM0 * x78 + LM1 * x92 + LM1 * x93 + LM2 * x112 + LM2 * x182 + x183;
        _hx_(1, 5) = -LM0 * x227 - LM1 * x223 - LM2 * x222 + x151 + x152 + x153 - x163 * x228 -
                     x164 * x228 - x226 * x95;
        _hx_(2, 5) =
            -LM0 * x240 - LM1 * x241 - LM2 * x242 - x150 - x163 * x243 - x164 * x243 - x226 * x98;
        _hx_(3, 5) = LM3 * (x281 + x282) + LM4 * (-x283 + x284) + LM5 * (-x285 - x286) + x292;
        _hx_(4, 5) =
            LM3 * (-x297 + x298) + LM4 * (x281 + x299) + LM5 * (2 * x17 * x38 * x6 - x300) + x303;
        _hx_(5, 5) =
            LM0 * (-x107 * x14 + x18 * x54 + x224 * x302 + x307 * x72) +
            LM1 * (-x107 * x27 + x18 * x80 + x225 * x290 + x307 * x91) +
            LM2 * (x0 * x148 * x30 + 4 * x113 * x48 + x114 * x225 * x76 + x18 * x213 * x29) -
            LM3 * x39 * x72 - LM4 * x39 * x91 - x206 * x48;
    }
};

} // namespace tycho::astro
