// =============================================================================
// Originally from ASSET (AlabamaASRL/asset_asrl)
// Copyright 2020-present The University of Alabama-Astrodynamics and Space
//   Research Lab. Licensed under the Apache License, Version 2.0
// License: notices/asset-apache2.txt.
// Source: https://github.com/AlabamaASRL/asset_asrl
// Original Developer: James B. Pezent
//
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_mee_dynamics.py — do not edit manually, EXCEPT
// that the ASSET attribution block above this banner was reinstated by hand
// after the codegen rewrite stripped it. The codegen script does NOT emit
// that header; if this file is ever regenerated, manually re-prepend the
// ASSET attribution block before committing.
// =============================================================================
#pragma once
#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct MEEDynamics : VectorFunction<MEEDynamics, 9, 6, DenseDerivativeMode::Analytic,
                                    DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<MEEDynamics, 9, 6, DenseDerivativeMode::Analytic,
                                DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu_; // Gravitational Parameter
    static constexpr bool is_vectorizable = true;

    // Precomputed from constructor parameters
    double pc0_;
    double pc1_;

    MEEDynamics() { this->set_io_rows(9, 6); }
    MEEDynamics(double mu) : mu_(mu) {
        this->set_io_rows(9, 6);
        pc0_ = std::sqrt(mu_);
        pc1_ = 1.0 / pc0_;
    }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_, CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar x9 = cos(x5);
        Scalar x10 = sin(x5);
        Scalar x11 = x1 * x9 + x10 * x2;
        Scalar x12 = x11 + 1;
        Scalar x13 = 1.0 / x12;
        Scalar x14 = x13 * x7;
        Scalar x15 = x10 * x3 - x4 * x9;
        Scalar x16 = x13 * x8;
        Scalar x17 = x11 + 2;
        Scalar x18 = Scalar(pc1_ * sqrt(x0));
        Scalar x19 = x15 * x16;
        Scalar x20 = x16 * x18 * ((1.0 / 2.0) * (x3 * x3) + (1.0 / 2.0) * (x4 * x4) + 1.0 / 2.0);

        _fx_[0] = Scalar(2 * pc1_ * (sqrt(x0) * x0) * x14);
        _fx_[1] = x18 * (x10 * x6 + x14 * (x1 + x17 * x9) - x15 * x16 * x2);
        _fx_[2] = x18 * (x1 * x19 + x14 * (x10 * x17 + x2) - x6 * x9);
        _fx_[3] = x20 * x9;
        _fx_[4] = x10 * x20;
        _fx_[5] = Scalar(x18 * (mu_ * (x12 * x12) / (x0 * x0) + x19));
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_, CVecRef<OutType> fx_,
                                      CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar x9 = cos(x5);
        Scalar x10 = x1 * x9;
        Scalar x11 = sin(x5);
        Scalar x12 = x11 * x2;
        Scalar x13 = x10 + x12;
        Scalar x14 = x13 + 1;
        Scalar x15 = 1.0 / x14;
        Scalar x16 = x15 * x7;
        Scalar x17 = Scalar(2 * pc1_ * (sqrt(x0) * x0));
        Scalar x18 = x11 * x6;
        Scalar x19 = x11 * x3;
        Scalar x20 = x19 - x4 * x9;
        Scalar x21 = -x20;
        Scalar x22 = x15 * x8;
        Scalar x23 = x13 + 2;
        Scalar x24 = x23 * x9;
        Scalar x25 = x1 + x24;
        Scalar x26 = x16 * x25 + x18 + x2 * x21 * x22;
        Scalar x27 = sqrt(x0);
        Scalar x28 = Scalar(pc1_ * x27);
        Scalar x29 = x6 * x9;
        Scalar x30 = x20 * x22;
        Scalar x31 = x11 * x23;
        Scalar x32 = x2 + x31;
        Scalar x33 = x1 * x30 + x16 * x32 - x29;
        Scalar x34 = (x3 * x3);
        Scalar x35 = (x4 * x4);
        Scalar x36 = (1.0 / 2.0) * x34 + (1.0 / 2.0) * x35 + 1.0 / 2.0;
        Scalar x37 = x28 * x9;
        Scalar x38 = x22 * x37;
        Scalar x39 = x36 * x38;
        Scalar x40 = x11 * x28;
        Scalar x41 = x22 * x40;
        Scalar x42 = x36 * x41;
        Scalar x43 = (x14 * x14);
        Scalar x44 = Scalar(mu_ / (x0 * x0));
        Scalar x45 = x30 + x43 * x44;
        Scalar x46 = 1.0 / x43;
        Scalar x47 = x46 * x7;
        Scalar x48 = x17 * x47;
        Scalar x49 = x1 * x11;
        Scalar x50 = x2 * x9;
        Scalar x51 = x49 - x50;
        Scalar x52 = 1.0 / x27;
        Scalar x53 = Scalar(pc1_ * x52);
        Scalar x54 = (1.0 / 2.0) * x53;
        Scalar x55 = (x9 * x9);
        Scalar x56 = x46 * x8;
        Scalar x57 = x21 * x56;
        Scalar x58 = x25 * x47;
        Scalar x59 = -x11 * x15 * x7 * x9;
        Scalar x60 = x22 * x28;
        Scalar x61 = x3 * x9;
        Scalar x62 = x11 * x4;
        Scalar x63 = x61 + x62;
        Scalar x64 = -x51;
        Scalar x65 = x15 * x28;
        Scalar x66 = x20 * x56;
        Scalar x67 = x32 * x47;
        Scalar x68 = (x11 * x11);
        Scalar x69 = x22 * x63;
        Scalar x70 = x51 * x66;
        Scalar x71 = x20 * x65;
        Scalar x72 = x22 * x53 * ((1.0 / 4.0) * x34 + (1.0 / 4.0) * x35 + 1.0 / 4.0);
        Scalar x73 = x36 * x56;
        Scalar x74 = x28 * x73;
        Scalar x75 = x40 * x73;
        Scalar x76 = -x75 * x9;
        Scalar x77 = x15 * x36;
        Scalar x78 = x14 * x44;
        Scalar x79 = 2 * x78;

        _fx_[0] = x16 * x17;
        _fx_[1] = x26 * x28;
        _fx_[2] = x28 * x33;
        _fx_[3] = x39;
        _fx_[4] = x42;
        _fx_[5] = x28 * x45;

        _jx_(0, 0) = 3 * x16 * x28;
        _jx_(1, 0) = x26 * x54;
        _jx_(2, 0) = x33 * x54;
        _jx_(3, 0) = x72 * x9;
        _jx_(4, 0) = x11 * x72;
        _jx_(5, 0) =
            Scalar(-2 * pc0_ * x43 / (sqrt(x0) * x0 * x0) + (1.0 / 2.0) * pc1_ * x45 * x52);
        _jx_(0, 1) = -x48 * x9;
        _jx_(1, 1) = x28 * (x15 * x7 * (x55 + 1) - x50 * x57 - x58 * x9);
        _jx_(2, 1) = x28 * (-x10 * x66 + x15 * x20 * x8 - x59 - x67 * x9);
        _jx_(3, 1) = -x55 * x74;
        _jx_(4, 1) = x76;
        _jx_(5, 1) = x28 * (-x66 * x9 + x79 * x9);
        _jx_(0, 2) = -x11 * x48;
        _jx_(1, 2) = x28 * (-x11 * x58 - x12 * x57 + x15 * x21 * x8 - x59);
        _jx_(2, 2) = x28 * (-x11 * x67 + x15 * x7 * (x68 + 1) - x49 * x66);
        _jx_(3, 2) = x76;
        _jx_(4, 2) = -x68 * x74;
        _jx_(5, 2) = x28 * (-x11 * x66 + x11 * x79);
        _jx_(0, 3) = 0;
        _jx_(1, 3) = -x12 * x60;
        _jx_(2, 3) = x49 * x60;
        _jx_(3, 3) = x60 * x61;
        _jx_(4, 3) = x19 * x60;
        _jx_(5, 3) = x41;
        _jx_(0, 4) = 0;
        _jx_(1, 4) = x50 * x60;
        _jx_(2, 4) = -x10 * x60;
        _jx_(3, 4) = x4 * x60 * x9;
        _jx_(4, 4) = x60 * x62;
        _jx_(5, 4) = -x38;
        _jx_(0, 5) = x48 * x51;
        _jx_(1, 5) =
            x28 * (x16 * (-x31 + x64 * x9) - x2 * x22 * x63 + x2 * x51 * x57 + x29 + x51 * x58);
        _jx_(2, 5) = x28 * (x1 * x69 + x1 * x70 + x16 * (x11 * x64 + x24) + x18 + x51 * x67);
        _jx_(3, 5) = x37 * x51 * x73 - x42;
        _jx_(4, 5) = x39 + x51 * x75;
        _jx_(5, 5) = x28 * (x69 + x70 + x78 * (2 * x2 * x9 - 2 * x49));
        _jx_(0, 6) = 0;
        _jx_(1, 6) = x40;
        _jx_(2, 6) = -x37;
        _jx_(3, 6) = 0;
        _jx_(4, 6) = 0;
        _jx_(5, 6) = 0;
        _jx_(0, 7) = x15 * x17;
        _jx_(1, 7) = x25 * x65;
        _jx_(2, 7) = x32 * x65;
        _jx_(3, 7) = 0;
        _jx_(4, 7) = 0;
        _jx_(5, 7) = 0;
        _jx_(0, 8) = 0;
        _jx_(1, 8) = x2 * x21 * x65;
        _jx_(2, 8) = x1 * x71;
        _jx_(3, 8) = x37 * x77;
        _jx_(4, 8) = x40 * x77;
        _jx_(5, 8) = x71;
    }

    template <class InType, class OutType, class JacType, class AdjGradType, class AdjHessType,
              class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_, CVecRef<OutType> fx_, CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_, CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar x6 = x_[6];
        Scalar x7 = x_[7];
        Scalar x8 = x_[8];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar x9 = cos(x5);
        Scalar x10 = x1 * x9;
        Scalar x11 = sin(x5);
        Scalar x12 = x11 * x2;
        Scalar x13 = x10 + x12;
        Scalar x14 = x13 + 1;
        Scalar x15 = 1.0 / x14;
        Scalar x16 = x15 * x7;
        Scalar x17 = (sqrt(x0) * x0);
        Scalar x18 = 2 * x17;
        Scalar x19 = Scalar(pc1_ * x18);
        Scalar x20 = x11 * x6;
        Scalar x21 = x11 * x3;
        Scalar x22 = x21 - x4 * x9;
        Scalar x23 = -x22;
        Scalar x24 = x15 * x23;
        Scalar x25 = x24 * x8;
        Scalar x26 = x13 + 2;
        Scalar x27 = x26 * x9;
        Scalar x28 = x1 + x27;
        Scalar x29 = x16 * x28 + x2 * x25 + x20;
        Scalar x30 = sqrt(x0);
        Scalar x31 = Scalar(pc1_ * x30);
        Scalar x32 = x6 * x9;
        Scalar x33 = x15 * x22;
        Scalar x34 = x33 * x8;
        Scalar x35 = x11 * x26;
        Scalar x36 = x2 + x35;
        Scalar x37 = x1 * x34 + x16 * x36 - x32;
        Scalar x38 = (x3 * x3);
        Scalar x39 = (x4 * x4);
        Scalar x40 = (1.0 / 2.0) * x38 + (1.0 / 2.0) * x39 + 1.0 / 2.0;
        Scalar x41 = x31 * x9;
        Scalar x42 = x15 * x8;
        Scalar x43 = x41 * x42;
        Scalar x44 = x40 * x43;
        Scalar x45 = x11 * x31;
        Scalar x46 = x42 * x45;
        Scalar x47 = x40 * x46;
        Scalar x48 = (x14 * x14);
        Scalar x49 = (Scalar(1.0) / (x0 * x0));
        Scalar x50 = Scalar(mu_ * x49);
        Scalar x51 = x34 + x48 * x50;
        Scalar x52 = 3 * x31;
        Scalar x53 = x16 * x52;
        Scalar x54 = 1.0 / x48;
        Scalar x55 = x54 * x9;
        Scalar x56 = x55 * x7;
        Scalar x57 = x19 * x56;
        Scalar x58 = x11 * x54;
        Scalar x59 = x58 * x7;
        Scalar x60 = x19 * x59;
        Scalar x61 = x1 * x11;
        Scalar x62 = x2 * x9;
        Scalar x63 = x61 - x62;
        Scalar x64 = x54 * x63;
        Scalar x65 = x64 * x7;
        Scalar x66 = x19 * x65;
        Scalar x67 = Scalar(pc1_ * x15);
        Scalar x68 = x18 * x67;
        Scalar x69 = Scalar(pc1_ * x29);
        Scalar x70 = 1.0 / x30;
        Scalar x71 = (1.0 / 2.0) * x70;
        Scalar x72 = x69 * x71;
        Scalar x73 = (x9 * x9);
        Scalar x74 = x73 + 1;
        Scalar x75 = x28 * x55;
        Scalar x76 = x54 * x8;
        Scalar x77 = x62 * x76;
        Scalar x78 = x23 * x77 + x7 * x75;
        Scalar x79 = x15 * x7 * x74 - x78;
        Scalar x80 = -x11 * x15 * x7 * x9;
        Scalar x81 = x12 * x23;
        Scalar x82 = x76 * x81;
        Scalar x83 = x28 * x58;
        Scalar x84 = x7 * x83;
        Scalar x85 = x15 * x23 * x8 - x80 - x82 - x84;
        Scalar x86 = x12 * x42;
        Scalar x87 = x42 * x62;
        Scalar x88 = x3 * x9;
        Scalar x89 = x11 * x4;
        Scalar x90 = x88 + x89;
        Scalar x91 = -x90;
        Scalar x92 = x23 * x64;
        Scalar x93 = x28 * x64;
        Scalar x94 = -x63;
        Scalar x95 = x9 * x94;
        Scalar x96 = -x35;
        Scalar x97 = x95 + x96;
        Scalar x98 = x15 * x97;
        Scalar x99 = x2 * x42 * x91 + x2 * x8 * x92 + x32 + x7 * x93 + x7 * x98;
        Scalar x100 = x31 * x99;
        Scalar x101 = x15 * x31;
        Scalar x102 = x101 * x28;
        Scalar x103 = x2 * x24;
        Scalar x104 = Scalar(pc1_ * x71);
        Scalar x105 = x104 * x37;
        Scalar x106 = x36 * x55;
        Scalar x107 = x22 * x8;
        Scalar x108 = x10 * x54;
        Scalar x109 = x106 * x7 + x107 * x108;
        Scalar x110 = -x109 + x15 * x22 * x8 - x80;
        Scalar x111 = (x11 * x11);
        Scalar x112 = x111 + 1;
        Scalar x113 = x36 * x58;
        Scalar x114 = x107 * x61;
        Scalar x115 = x113 * x7 + x114 * x54;
        Scalar x116 = x112 * x15 * x7 - x115;
        Scalar x117 = x42 * x61;
        Scalar x118 = x10 * x42;
        Scalar x119 = x15 * x90;
        Scalar x120 = x119 * x8;
        Scalar x121 = x22 * x64;
        Scalar x122 = x121 * x8;
        Scalar x123 = x36 * x64;
        Scalar x124 = x11 * x94;
        Scalar x125 = x124 + x27;
        Scalar x126 = x125 * x15;
        Scalar x127 = x1 * x120 + x1 * x122 + x123 * x7 + x126 * x7 + x20;
        Scalar x128 = x127 * x31;
        Scalar x129 = x101 * x36;
        Scalar x130 = x31 * x33;
        Scalar x131 = x1 * x130;
        Scalar x132 = x42 * x9;
        Scalar x133 = (1.0 / 4.0) * x38 + (1.0 / 4.0) * x39 + 1.0 / 4.0;
        Scalar x134 = Scalar(pc1_ * x133 * x70);
        Scalar x135 = x132 * x134;
        Scalar x136 = x73 * x76;
        Scalar x137 = x31 * x40;
        Scalar x138 = x136 * x137;
        Scalar x139 = x55 * x8;
        Scalar x140 = x40 * x45;
        Scalar x141 = x139 * x140;
        Scalar x142 = -x141;
        Scalar x143 = x31 * x42;
        Scalar x144 = x143 * x88;
        Scalar x145 = x4 * x9;
        Scalar x146 = x143 * x145;
        Scalar x147 = -x47;
        Scalar x148 = x64 * x8;
        Scalar x149 = x148 * x41;
        Scalar x150 = x147 + x149 * x40;
        Scalar x151 = x15 * x40;
        Scalar x152 = x151 * x41;
        Scalar x153 = x11 * x42;
        Scalar x154 = x134 * x153;
        Scalar x155 = x111 * x76;
        Scalar x156 = x137 * x155;
        Scalar x157 = -x156;
        Scalar x158 = x143 * x21;
        Scalar x159 = x143 * x89;
        Scalar x160 = x140 * x148 + x44;
        Scalar x161 = x151 * x45;
        Scalar x162 = Scalar(pc0_ * x48);
        Scalar x163 = (Scalar(1.0) / (sqrt(x0) * x0 * x0));
        Scalar x164 = 2 * x163;
        Scalar x165 = Scalar((1.0 / 2.0) * pc1_ * x51 * x70 - x162 * x164);
        Scalar x166 = 2 * x50;
        Scalar x167 = x14 * x166;
        Scalar x168 = x107 * x55;
        Scalar x169 = x167 * x9 - x168;
        Scalar x170 = x107 * x58;
        Scalar x171 = x11 * x167 - x170;
        Scalar x172 = 2 * x61;
        Scalar x173 = x172 - 2 * x2 * x9;
        Scalar x174 = -x173;
        Scalar x175 = x174 * x50;
        Scalar x176 = x120 + x122;
        Scalar x177 = x14 * x175 + x176;
        Scalar x178 = x177 * x31;
        Scalar x179 = LM0 * x57;
        Scalar x180 = LM3 * x138 + x179;
        Scalar x181 = LM0 * x60;
        Scalar x182 = LM4 * x156 + x181;
        Scalar x183 = LM2 * x31;
        Scalar x184 = LM1 * x31;
        Scalar x185 = LM5 * x46 + x117 * x183 - x184 * x86;
        Scalar x186 = LM5 * x43;
        Scalar x187 = x184 * x87;
        Scalar x188 = x118 * x183;
        Scalar x189 = LM1 * x45;
        Scalar x190 = LM2 * x41;
        Scalar x191 = x38 + x39 + 1;
        Scalar x192 = LM3 * x191;
        Scalar x193 = 1.0 / x17;
        Scalar x194 = Scalar((1.0 / 8.0) * pc1_ * x193);
        Scalar x195 = (1.0 / 4.0) * x193;
        Scalar x196 = Scalar(pc1_ * x195);
        Scalar x197 = 4 * x9;
        Scalar x198 = Scalar(pc0_ * x14);
        Scalar x199 = x163 * x198;
        Scalar x200 = x197 * x199;
        Scalar x201 = x41 * x54;
        Scalar x202 = 3 * LM0;
        Scalar x203 = x202 * x7;
        Scalar x204 = LM3 * x136;
        Scalar x205 = LM4 * x11;
        Scalar x206 = x134 * x139;
        Scalar x207 =
            Scalar(-1.0 / 2.0 * LM1 * pc1_ * x70 * x79 - 1.0 / 2.0 * LM2 * pc1_ * x110 * x70 +
                   x134 * x204 + x201 * x203 + x205 * x206);
        Scalar x208 = 4 * x11;
        Scalar x209 = x199 * x208;
        Scalar x210 = x45 * x54;
        Scalar x211 = LM4 * x155;
        Scalar x212 =
            Scalar(-1.0 / 2.0 * LM1 * pc1_ * x70 * x85 - 1.0 / 2.0 * LM2 * pc1_ * x116 * x70 +
                   LM3 * x11 * x206 + x134 * x211 + x203 * x210);
        Scalar x213 = LM5 * x104;
        Scalar x214 = LM1 * x104;
        Scalar x215 = LM2 * x104;
        Scalar x216 = x104 * x42;
        Scalar x217 = LM3 * x216;
        Scalar x218 = LM4 * x216;
        Scalar x219 = x117 * x215 + x153 * x213 + x21 * x218 - x214 * x86 + x217 * x88;
        Scalar x220 = -x118 * x215 - x132 * x213 + x145 * x217 + x214 * x87 + x218 * x89;
        Scalar x221 = x164 * x174 * x198;
        Scalar x222 = x139 * x63;
        Scalar x223 = x134 * x222;
        Scalar x224 = x58 * x8;
        Scalar x225 = x224 * x63;
        Scalar x226 = x134 * x225;
        Scalar x227 = LM0 * x52 * x65 + x127 * x215 + x214 * x99;
        Scalar x228 = x11 * x214 - x215 * x9;
        Scalar x229 = x67 * x71;
        Scalar x230 = LM1 * x229 * x28 + LM2 * x229 * x36 + x101 * x202;
        Scalar x231 = x133 * x67 * x70;
        Scalar x232 = LM3 * x231 * x9 + x1 * x215 * x33 + x103 * x214 + x205 * x231 + x213 * x33;
        Scalar x233 = (Scalar(1.0) / (x14 * x14 * x14));
        Scalar x234 = Scalar(LM0 * pc1_ * x17 * x233 * x7);
        Scalar x235 = 4 * x234;
        Scalar x236 = x233 * x8;
        Scalar x237 = x236 * x31;
        Scalar x238 = x191 * x45;
        Scalar x239 = x236 * x238;
        Scalar x240 = 2 * x73;
        Scalar x241 = x233 * x240;
        Scalar x242 = LM5 * x31;
        Scalar x243 = x2 * x23;
        Scalar x244 = x28 * x7;
        Scalar x245 = x233 * x244;
        Scalar x246 = x59 * x73;
        Scalar x247 = x1 * x73;
        Scalar x248 = 2 * x233;
        Scalar x249 = x107 * x248;
        Scalar x250 = x36 * x7;
        Scalar x251 = x11 * x9;
        Scalar x252 = LM3 * x73;
        Scalar x253 = LM4 * x111;
        Scalar x254 = x236 * x41;
        Scalar x255 = x111 * x56;
        Scalar x256 = x183 * (2 * x1 * x11 * x22 * x233 * x8 * x9 + 2 * x11 * x233 * x36 * x7 * x9 -
                              x112 * x56 - x170 - x255) +
                      x184 * (2 * x11 * x2 * x23 * x233 * x8 * x9 + 2 * x11 * x233 * x28 * x7 * x9 -
                              x139 * x23 - x246 - x59 * x74) +
                      x191 * x253 * x254 + x235 * x251 + x239 * x252 +
                      x242 * (x166 * x251 + x249 * x251);
        Scalar x257 = -x153;
        Scalar x258 = x204 * x31;
        Scalar x259 = LM5 * x45;
        Scalar x260 = x139 * x259;
        Scalar x261 = LM4 * x76;
        Scalar x262 = x21 * x41;
        Scalar x263 = LM1 * x41;
        Scalar x264 = x12 * x76;
        Scalar x265 = x263 * x264;
        Scalar x266 = x258 * x3 + x260 + x261 * x262 - x265;
        Scalar x267 = -x132;
        Scalar x268 = x145 * x45;
        Scalar x269 =
            Scalar(-LM5 * pc1_ * x30 * x54 * x73 * x8 + x136 * x184 * x2 + x258 * x4 + x261 * x268);
        Scalar x270 = x173 * x9;
        Scalar x271 = x173 * x236;
        Scalar x272 = x23 * x62;
        Scalar x273 = 2 * x16 * x251;
        Scalar x274 = x273 - x54 * x63 * x7 * x74 + x56 * x97 + x77 * x91 - x82 - x84;
        Scalar x275 = x111 * x16;
        Scalar x276 = x233 * x270;
        Scalar x277 = x173 * x233;
        Scalar x278 = x11 * x63;
        Scalar x279 = x76 * x90;
        Scalar x280 = -x10 * x279 + x115 - x125 * x56 + x176 + x278 * x56;
        Scalar x281 = x139 * x90 + x171;
        Scalar x282 = LM0 * x19;
        Scalar x283 = x282 * x7;
        Scalar x284 = x137 * x271;
        Scalar x285 = x140 * x276 * x8;
        Scalar x286 = x282 * x55;
        Scalar x287 = -x11 * x15 * x9;
        Scalar x288 = x108 * x22;
        Scalar x289 = x137 * x54;
        Scalar x290 = LM5 * x22;
        Scalar x291 = x140 * x55;
        Scalar x292 = LM4 * x291 + x184 * x272 * x54 + x201 * x290 + x252 * x289;
        Scalar x293 = x191 * x237;
        Scalar x294 = 2 * x111;
        Scalar x295 = x233 * x294;
        Scalar x296 = x107 * x295;
        Scalar x297 = -2 * x21 + 2 * x4 * x9;
        Scalar x298 = x111 * x2;
        Scalar x299 = x211 * x31;
        Scalar x300 = LM3 * x76;
        Scalar x301 = x1 * x155 * x183 + x155 * x242 + x262 * x300 + x299 * x3;
        Scalar x302 = LM2 * x45;
        Scalar x303 = x10 * x302 * x76;
        Scalar x304 = x299 * x4;
        Scalar x305 = x268 * x300;
        Scalar x306 = x11 * x173;
        Scalar x307 = -x11 * x54 * x63 * x7 * x9 - x15 * x8 * x91 - x23 * x54 * x63 * x8 +
                      x264 * x91 + x59 * x97 + x78;
        Scalar x308 = x233 * x306;
        Scalar x309 = x109 - x112 * x54 * x63 * x7 + x125 * x59 - x273 + x279 * x61;
        Scalar x310 = Scalar(-2 * mu_ * x14 * x49 * x9 + x168 + x224 * x90);
        Scalar x311 = x139 * x238;
        Scalar x312 = x282 * x58;
        Scalar x313 = x54 * x81;
        Scalar x314 = LM3 * x291 + x183 * x22 * x54 * x61 + x210 * x290 + x253 * x289;
        Scalar x315 = LM3 * x43 + LM4 * x46;
        Scalar x316 = x148 * x61;
        Scalar x317 = x148 * x31;
        Scalar x318 = x317 * x88;
        Scalar x319 = x21 * x317;
        Scalar x320 = x12 * x148;
        Scalar x321 = LM5 * x15;
        Scalar x322 = LM2 * x101;
        Scalar x323 = LM3 * x101;
        Scalar x324 = LM4 * x101;
        Scalar x325 = LM1 * x101;
        Scalar x326 = -x12 * x325 + x21 * x324 + x321 * x45 + x322 * x61 + x323 * x88;
        Scalar x327 = x148 * x62;
        Scalar x328 = x145 * x317;
        Scalar x329 = x317 * x89;
        Scalar x330 = x10 * x148;
        Scalar x331 = -x10 * x322 + x145 * x323 - x321 * x41 + x324 * x89 + x325 * x62;
        Scalar x332 = x234 * x63;
        Scalar x333 = x293 * x63;
        Scalar x334 = x63 * x9;
        Scalar x335 = -x138 - x157 - x239 * x334;
        Scalar x336 = 2 * x245;
        Scalar x337 = x23 * x236;
        Scalar x338 = -x111 + x73;
        Scalar x339 = x248 * x250;
        Scalar x340 = 2 * x10;
        Scalar x341 = x107 * x233;
        Scalar x342 = 2 * x12;
        Scalar x343 = x13 * x54;
        Scalar x344 = x173 * x63;
        Scalar x345 = x233 * x344;
        Scalar x346 = x13 * x76;
        Scalar x347 = x236 * x344;
        Scalar x348 = x40 * x41;
        Scalar x349 = x107 * x343;
        Scalar x350 = 2 * x148;
        Scalar x351 = x350 * x90;
        Scalar x352 = x107 * x345;
        Scalar x353 = 2 * x65;
        Scalar x354 = -x13;
        Scalar x355 = x2 * x91;
        Scalar x356 = x263 + x302;
        Scalar x357 = x282 * x64;
        Scalar x358 = x1 * x119;
        Scalar x359 = x1 * x121;
        Scalar x360 = x15 * x355;
        Scalar x361 = x2 * x92;
        Scalar x362 = x40 * x64;
        Scalar x363 = x362 * x45;
        Scalar x364 = x362 * x41;
        Scalar x365 = x28 * x54;
        Scalar x366 = x36 * x54;

        _fx_[0] = x16 * x19;
        _fx_[1] = x29 * x31;
        _fx_[2] = x31 * x37;
        _fx_[3] = x44;
        _fx_[4] = x47;
        _fx_[5] = x31 * x51;

        _jx_(0, 0) = x53;
        _jx_(1, 0) = x72;
        _jx_(2, 0) = x105;
        _jx_(3, 0) = x135;
        _jx_(4, 0) = x154;
        _jx_(5, 0) = x165;
        _jx_(0, 1) = -x57;
        _jx_(1, 1) = x31 * x79;
        _jx_(2, 1) = x110 * x31;
        _jx_(3, 1) = -x138;
        _jx_(4, 1) = x142;
        _jx_(5, 1) = x169 * x31;
        _jx_(0, 2) = -x60;
        _jx_(1, 2) = x31 * x85;
        _jx_(2, 2) = x116 * x31;
        _jx_(3, 2) = x142;
        _jx_(4, 2) = x157;
        _jx_(5, 2) = x171 * x31;
        _jx_(0, 3) = 0;
        _jx_(1, 3) = -x31 * x86;
        _jx_(2, 3) = x117 * x31;
        _jx_(3, 3) = x144;
        _jx_(4, 3) = x158;
        _jx_(5, 3) = x46;
        _jx_(0, 4) = 0;
        _jx_(1, 4) = x31 * x87;
        _jx_(2, 4) = -x118 * x31;
        _jx_(3, 4) = x146;
        _jx_(4, 4) = x159;
        _jx_(5, 4) = -x43;
        _jx_(0, 5) = x66;
        _jx_(1, 5) = x100;
        _jx_(2, 5) = x128;
        _jx_(3, 5) = x150;
        _jx_(4, 5) = x160;
        _jx_(5, 5) = x178;
        _jx_(0, 6) = 0;
        _jx_(1, 6) = x45;
        _jx_(2, 6) = -x41;
        _jx_(3, 6) = 0;
        _jx_(4, 6) = 0;
        _jx_(5, 6) = 0;
        _jx_(0, 7) = x68;
        _jx_(1, 7) = x102;
        _jx_(2, 7) = x129;
        _jx_(3, 7) = 0;
        _jx_(4, 7) = 0;
        _jx_(5, 7) = 0;
        _jx_(0, 8) = 0;
        _jx_(1, 8) = x103 * x31;
        _jx_(2, 8) = x131;
        _jx_(3, 8) = x152;
        _jx_(4, 8) = x161;
        _jx_(5, 8) = x130;

        _gx_[0] = LM0 * x53 + LM1 * x72 + LM2 * x105 + LM3 * x135 + LM4 * x154 + LM5 * x165;
        _gx_[1] = Scalar(LM1 * pc1_ * x30 * x79 + LM2 * pc1_ * x110 * x30 - LM4 * x141 +
                         LM5 * pc1_ * x169 * x30 - x180);
        _gx_[2] = Scalar(LM1 * pc1_ * x30 * x85 + LM2 * pc1_ * x116 * x30 - LM3 * x141 +
                         LM5 * pc1_ * x171 * x30 - x182);
        _gx_[3] = LM3 * x144 + LM4 * x158 + x185;
        _gx_[4] = LM3 * x146 + LM4 * x159 - x186 + x187 - x188;
        _gx_[5] = LM0 * x66 + LM1 * x100 + LM2 * x128 + LM3 * x150 + LM4 * x160 + LM5 * x178;
        _gx_[6] = x189 - x190;
        _gx_[7] = LM0 * x68 + LM1 * x102 + LM2 * x129;
        _gx_[8] = LM2 * x131 + LM3 * x152 + LM4 * x161 + LM5 * x130 + x103 * x184;

        _hx_(0, 0) =
            Scalar((3.0 / 2.0) * LM0 * pc1_ * x15 * x7 * x70 - LM1 * x195 * x69 - LM2 * x196 * x37 -
                   LM4 * x153 * x191 * x194 +
                   LM5 * (-x196 * x51 + 4 * x162 / (sqrt(x0) * x0 * x0 * x0)) - x132 * x192 * x194);
        _hx_(1, 0) = _hx_(0, 1);
        _hx_(2, 0) = _hx_(0, 2);
        _hx_(3, 0) = _hx_(0, 3);
        _hx_(4, 0) = _hx_(0, 4);
        _hx_(5, 0) = _hx_(0, 5);
        _hx_(6, 0) = _hx_(0, 6);
        _hx_(7, 0) = _hx_(0, 7);
        _hx_(8, 0) = _hx_(0, 8);
        _hx_(0, 1) = Scalar(LM5 * ((1.0 / 2.0) * pc1_ * x169 * x70 - x200) - x207);
        _hx_(1, 1) = LM4 * x239 * x73 + x183 * (-2 * x168 + x241 * x250 - 2 * x246 + x247 * x249) +
                     x184 * (x240 * x245 + x241 * x243 * x8 - 2 * x56 * x74) +
                     x192 * x237 * (x9 * x9 * x9) + x235 * x73 + x242 * (x107 * x241 + x166 * x73);
        _hx_(2, 1) = _hx_(1, 2);
        _hx_(3, 1) = _hx_(1, 3);
        _hx_(4, 1) = _hx_(1, 4);
        _hx_(5, 1) = _hx_(1, 5);
        _hx_(6, 1) = _hx_(1, 6);
        _hx_(7, 1) = _hx_(1, 7);
        _hx_(8, 1) = _hx_(1, 8);
        _hx_(0, 2) = Scalar(LM5 * ((1.0 / 2.0) * pc1_ * x171 * x70 - x209) - x212);
        _hx_(1, 2) = x256;
        _hx_(2, 2) = LM4 * (x11 * x11 * x11) * x293 + x111 * x192 * x254 + x111 * x235 +
                     x183 * (x1 * x296 - 2 * x112 * x59 + x250 * x295) +
                     x184 * (-x224 * x297 + x236 * x297 * x298 + x245 * x294 - 2 * x255) +
                     x242 * (x111 * x166 + x296);
        _hx_(3, 2) = _hx_(2, 3);
        _hx_(4, 2) = _hx_(2, 4);
        _hx_(5, 2) = _hx_(2, 5);
        _hx_(6, 2) = _hx_(2, 6);
        _hx_(7, 2) = _hx_(2, 7);
        _hx_(8, 2) = _hx_(2, 8);
        _hx_(0, 3) = x219;
        _hx_(1, 3) = Scalar(LM2 * pc1_ * x30 * (-x10 * x224 - x257) - x266);
        _hx_(2, 3) = Scalar(LM1 * pc1_ * x30 * (x257 + x298 * x76) - x301);
        _hx_(3, 3) = x315;
        _hx_(4, 3) = _hx_(3, 4);
        _hx_(5, 3) = _hx_(3, 5);
        _hx_(6, 3) = _hx_(3, 6);
        _hx_(7, 3) = _hx_(3, 7);
        _hx_(8, 3) = _hx_(3, 8);
        _hx_(0, 4) = x220;
        _hx_(1, 4) = Scalar(LM2 * pc1_ * x30 * (x247 * x76 + x267) - x269);
        _hx_(2, 4) = x184 * (-x12 * x139 - x267) + x260 + x303 - x304 - x305;
        _hx_(3, 4) = 0;
        _hx_(4, 4) = x315;
        _hx_(5, 4) = _hx_(4, 5);
        _hx_(6, 4) = _hx_(4, 6);
        _hx_(7, 4) = _hx_(4, 7);
        _hx_(8, 4) = _hx_(4, 8);
        _hx_(0, 5) = Scalar(-LM3 * x154 + LM3 * x223 + LM4 * x135 + LM4 * x226 +
                            LM5 * ((1.0 / 2.0) * pc1_ * x177 * x70 - x221) + x227);
        _hx_(1, 5) = Scalar(-LM4 * x138 - LM4 * x285 + x139 * x192 * x45 + x182 +
                            x183 * (-x10 * x107 * x277 + x16 * x73 - x250 * x276 - x275 + x280) +
                            x184 * (-x245 * x270 - x271 * x272 - x274) +
                            x242 * (2 * mu_ * x49 * x9 * x94 - x107 * x276 - x281) - x252 * x284 -
                            x276 * x283);
        _hx_(2, 5) = Scalar(
            LM1 * pc1_ * x30 * (x15 * x7 * x73 - x245 * x306 - x271 * x81 - x275 - x307) +
            LM2 * pc1_ * x30 * (-x114 * x277 - x250 * x308 - x309) +
            (1.0 / 2.0) * LM3 * pc1_ * x111 * x191 * x30 * x54 * x8 - LM3 * x285 - LM4 * x311 +
            LM5 * pc1_ * x30 * (2 * mu_ * x11 * x49 * x94 - x107 * x308 - x310) - x180 -
            x253 * x284 - x283 * x308);
        _hx_(3, 5) = -LM3 * x158 + LM3 * x318 + LM4 * x144 + LM4 * x319 + x148 * x259 +
                     x183 * x316 - x184 * x320 + x186 - x187 + x188;
        _hx_(4, 5) = -LM3 * x159 + LM3 * x328 + LM4 * x146 + LM4 * x329 - LM5 * x149 - x183 * x330 +
                     x184 * x327 + x185;
        _hx_(5, 5) = LM3 * (-x148 * x238 + x346 * x348 + x347 * x348 - x44) +
                     LM4 * (x140 * x346 + x140 * x347 + x147 + x149 * x191) +
                     x183 * (x1 * x25 + x1 * x349 + x1 * x351 + x1 * x352 + x125 * x353 +
                             x16 * (x11 * x354 + 2 * x95 + x96) + x250 * x343 + x250 * x345 + x32) +
                     x184 * (x16 * (-2 * x124 - x27 + x354 * x9) + x2 * x34 - x20 + x243 * x346 +
                             x243 * x347 + x244 * x343 + x245 * x344 + x350 * x355 + x353 * x97) +
                     x242 * (x14 * x50 * (-x340 - x342) + x175 * x94 + x25 + x349 + x351 + x352) +
                     x283 * x343 + x283 * x345;
        _hx_(6, 5) = _hx_(5, 6);
        _hx_(7, 5) = _hx_(5, 7);
        _hx_(8, 5) = _hx_(5, 8);
        _hx_(0, 6) = x228;
        _hx_(1, 6) = 0;
        _hx_(2, 6) = 0;
        _hx_(3, 6) = 0;
        _hx_(4, 6) = 0;
        _hx_(5, 6) = x356;
        _hx_(6, 6) = 0;
        _hx_(7, 6) = _hx_(6, 7);
        _hx_(8, 6) = _hx_(6, 8);
        _hx_(0, 7) = x230;
        _hx_(1, 7) = x183 * (-x106 - x287) + x184 * (x15 * x74 - x75) - x286;
        _hx_(2, 7) = x183 * (x112 * x15 - x113) + x184 * (-x287 - x83) - x312;
        _hx_(3, 7) = 0;
        _hx_(4, 7) = 0;
        _hx_(5, 7) = x183 * (x123 + x126) + x184 * (x93 + x98) + x357;
        _hx_(6, 7) = 0;
        _hx_(7, 7) = 0;
        _hx_(8, 7) = _hx_(7, 8);
        _hx_(0, 8) = x232;
        _hx_(1, 8) = Scalar(LM2 * pc1_ * x30 * (x15 * x22 - x288) - x292);
        _hx_(2, 8) = Scalar(LM1 * pc1_ * x30 * (x15 * x23 - x313) - x314);
        _hx_(3, 8) = x326;
        _hx_(4, 8) = x331;
        _hx_(5, 8) = LM3 * (-x161 + x364) + LM4 * (x152 + x363) + x183 * (x358 + x359) +
                     x184 * (x360 + x361) + x242 * (x119 + x121);
        _hx_(6, 8) = 0;
        _hx_(7, 8) = 0;
        _hx_(8, 8) = 0;
    }
};

} // namespace tycho::astro
