// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_mee_to_cartesian.py — do not edit manually.
// =============================================================================
#pragma once

#include <limits>
#include <stdexcept>

#include "tycho/vector_functions.h"

namespace tycho::astro {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

struct MEEToCartesian : VectorFunction<MEEToCartesian, 6, 6, DenseDerivativeMode::Analytic,
                                       DenseDerivativeMode::Analytic> {
    using Base = VectorFunction<MEEToCartesian, 6, 6, DenseDerivativeMode::Analytic,
                                DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);

    double mu_ = std::numeric_limits<double>::quiet_NaN(); // Gravitational Parameter
    static constexpr bool is_vectorizable = true;

    MEEToCartesian() : MEEToCartesian(1.0) {}

    MEEToCartesian(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument("MEEToCartesian: mu must satisfy mu > 0.0");
        this->set_io_rows(6, 6);
        mu_ = mu;
    }

    void set_mu(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument("MEEToCartesian: mu must satisfy mu > 0.0");
        mu_ = mu;
    }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_, CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar _hp0_ = Scalar(mu_ / x0);
        Scalar x6 = cos(x5);
        Scalar x7 = (x3 * x3);
        Scalar x8 = (x4 * x4);
        Scalar x9 = x7 - x8;
        Scalar x10 = sin(x5);
        Scalar x11 = x10 * x3;
        Scalar x12 = 2 * x4;
        Scalar x13 = x11 * x12 + x6 * x9;
        Scalar x14 = 1.0 / (x7 + x8 + 1);
        Scalar x15 = x0 * x14 / (x1 * x6 + x10 * x2 + 1);
        Scalar x16 = x4 * x6;
        Scalar x17 = 2 * x3;
        Scalar x18 = x16 * x17;
        Scalar x19 = x10 * x9;
        Scalar x20 = x1 * x3;
        Scalar x21 = sqrt(_hp0_) * x14;
        Scalar x22 = x2 * x4;

        _fx_[0] = x15 * (x13 + x6);
        _fx_[1] = x15 * (x10 + x18 - x19);
        _fx_[2] = 2 * x15 * (x11 - x16);
        _fx_[3] = -x21 * (x10 - x12 * x20 - x18 + x19 + x2 * x9 + x2);
        _fx_[4] = -x21 * (x1 * x9 - x1 + x13 + x17 * x22 - x6);
        _fx_[5] = 2 * x21 * (x10 * x4 + x20 + x22 + x3 * x6);
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_, CVecRef<OutType> fx_,
                                      CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar _hp0_ = Scalar(mu_ / x0);
        Scalar x6 = cos(x5);
        Scalar x7 = (x3 * x3);
        Scalar x8 = (x4 * x4);
        Scalar x9 = x7 - x8;
        Scalar x10 = sin(x5);
        Scalar x11 = x10 * x3;
        Scalar x12 = 2 * x11;
        Scalar x13 = x12 * x4 + x6 * x9;
        Scalar x14 = x13 + x6;
        Scalar x15 = x8 + 1;
        Scalar x16 = x15 + x7;
        Scalar x17 = 1.0 / x16;
        Scalar x18 = x1 * x6 + x10 * x2 + 1;
        Scalar x19 = 1.0 / x18;
        Scalar x20 = x17 * x19;
        Scalar x21 = x14 * x20;
        Scalar x22 = x4 * x6;
        Scalar x23 = 2 * x22;
        Scalar x24 = x23 * x3;
        Scalar x25 = x10 * x9;
        Scalar x26 = x10 + x24 - x25;
        Scalar x27 = x20 * x26;
        Scalar x28 = x0 * x20;
        Scalar x29 = x11 - x22;
        Scalar x30 = 2 * x29;
        Scalar x31 = x1 * x3;
        Scalar x32 = 2 * x4;
        Scalar x33 = x10 + x2;
        Scalar x34 = -x24 + x25;
        Scalar x35 = x2 * x9 - x31 * x32 + x33 + x34;
        Scalar x36 = sqrt(_hp0_);
        Scalar x37 = x17 * x36;
        Scalar x38 = x35 * x37;
        Scalar x39 = x2 * x4;
        Scalar x40 = 2 * x3;
        Scalar x41 = x13 - x6;
        Scalar x42 = x1 * x9 - x1 + x39 * x40 + x41;
        Scalar x43 = x37 * x42;
        Scalar x44 = x3 * x6;
        Scalar x45 = x10 * x4;
        Scalar x46 = x44 + x45;
        Scalar x47 = x31 + x39 + x46;
        Scalar x48 = x37 * x47;
        Scalar x49 = x0 * x14;
        Scalar x50 = x17 / (x18 * x18);
        Scalar x51 = x49 * x50;
        Scalar x52 = 2 * x44 + 2 * x45;
        Scalar x53 = -x0 * x17 * x19 * x52;
        Scalar x54 = (Scalar(1.0) / (x16 * x16));
        Scalar x55 = x19 * x54;
        Scalar x56 = x49 * x55;
        Scalar x57 = x12 - x23;
        Scalar x58 = x1 * x10 - x2 * x6;
        Scalar x59 = x0 * x26;
        Scalar x60 = x50 * x59;
        Scalar x61 = x55 * x59;
        Scalar x62 = x0 * x30 * x50;
        Scalar x63 = 4 * x3;
        Scalar x64 = x0 * x29 * x55;
        Scalar x65 = 2 * x28;
        Scalar x66 = 4 * x4;
        Scalar x67 = 1.0 / x0;
        Scalar x68 = (1.0 / 2.0) * x67;
        Scalar x69 = x32 * x37;
        Scalar x70 = x3 * x69;
        Scalar x71 = -x37 * (-x1 * x32 + x12 + 2 * x2 * x3 - x23);
        Scalar x72 = x36 * x54;
        Scalar x73 = x35 * x72;
        Scalar x74 = 2 * x31 + 2 * x39 + x52;
        Scalar x75 = x42 * x72;
        Scalar x76 = x47 * x72;

        _fx_[0] = x0 * x21;
        _fx_[1] = x0 * x27;
        _fx_[2] = x28 * x30;
        _fx_[3] = -x38;
        _fx_[4] = -x43;
        _fx_[5] = 2 * x48;

        _jx_(0, 0) = x21;
        _jx_(1, 0) = x27;
        _jx_(2, 0) = x20 * x30;
        _jx_(3, 0) = x38 * x68;
        _jx_(4, 0) = x43 * x68;
        _jx_(5, 0) = -x48 * x67;
        _jx_(0, 1) = -x51 * x6;
        _jx_(1, 1) = -x6 * x60;
        _jx_(2, 1) = -x6 * x62;
        _jx_(3, 1) = x70;
        _jx_(4, 1) = -x37 * (-x15 + x7);
        _jx_(5, 1) = x37 * x40;
        _jx_(0, 2) = -x10 * x51;
        _jx_(1, 2) = -x10 * x60;
        _jx_(2, 2) = -x10 * x62;
        _jx_(3, 2) = -x37 * (x9 + 1);
        _jx_(4, 2) = -x70;
        _jx_(5, 2) = x69;
        _jx_(0, 3) = -x40 * x56 - x53;
        _jx_(1, 3) = -x0 * x17 * x19 * x57 - x40 * x61;
        _jx_(2, 3) = 2 * x0 * x10 * x17 * x19 - x63 * x64;
        _jx_(3, 3) = x40 * x73 + x71;
        _jx_(4, 3) = -x37 * x74 + x40 * x75;
        _jx_(5, 3) = 2 * x17 * x36 * (x1 + x6) - x63 * x76;
        _jx_(0, 4) = x0 * x17 * x19 * x57 - x32 * x56;
        _jx_(1, 4) = -x32 * x61 - x53;
        _jx_(2, 4) = -x6 * x65 - x64 * x66;
        _jx_(3, 4) = x32 * x73 + x37 * x74;
        _jx_(4, 4) = x32 * x75 + x71;
        _jx_(5, 4) = 2 * x17 * x33 * x36 - x66 * x76;
        _jx_(0, 5) = x28 * (-x10 - x34) + x51 * x58;
        _jx_(1, 5) = -x28 * x41 + x58 * x60;
        _jx_(2, 5) = x46 * x65 + x58 * x62;
        _jx_(3, 5) = -x14 * x37;
        _jx_(4, 5) = -x26 * x37;
        _jx_(5, 5) = -2 * x29 * x37;
    }

    template <class InType, class OutType, class JacType, class AdjGradType, class AdjHessType,
              class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_, CVecRef<OutType> fx_, CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_, CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos;
        using std::sin;
        using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar x0 = x_[0];
        Scalar x1 = x_[1];
        Scalar x2 = x_[2];
        Scalar x3 = x_[3];
        Scalar x4 = x_[4];
        Scalar x5 = x_[5];
        Scalar LM0 = adjvars[0];
        Scalar LM1 = adjvars[1];
        Scalar LM2 = adjvars[2];
        Scalar LM3 = adjvars[3];
        Scalar LM4 = adjvars[4];
        Scalar LM5 = adjvars[5];
        Scalar _hp0_ = Scalar(mu_ / x0);
        Scalar _hp1_ = cos(x5);
        Scalar _hp2_ = sin(x5);
        Scalar x6 = (x3 * x3);
        Scalar x7 = (x4 * x4);
        Scalar x8 = x6 - x7;
        Scalar x9 = _hp2_ * x3;
        Scalar x10 = 2 * x9;
        Scalar x11 = _hp1_ * x8 + x10 * x4;
        Scalar x12 = _hp1_ + x11;
        Scalar x13 = x7 + 1;
        Scalar x14 = x13 + x6;
        Scalar x15 = 1.0 / x14;
        Scalar x16 = _hp1_ * x1 + _hp2_ * x2;
        Scalar x17 = x16 + 1;
        Scalar x18 = 1.0 / x17;
        Scalar x19 = x15 * x18;
        Scalar x20 = x12 * x19;
        Scalar x21 = _hp1_ * x4;
        Scalar x22 = 2 * x21;
        Scalar x23 = x22 * x3;
        Scalar x24 = _hp2_ * x8;
        Scalar x25 = _hp2_ + x23 - x24;
        Scalar x26 = x19 * x25;
        Scalar x27 = -_hp2_ * x3 + x21;
        Scalar x28 = -x27;
        Scalar x29 = 2 * x19;
        Scalar x30 = x28 * x29;
        Scalar x31 = x1 * x3;
        Scalar x32 = 2 * x31;
        Scalar x33 = _hp2_ + x2;
        Scalar x34 = -x23 + x24;
        Scalar x35 = x2 * x8 - x32 * x4 + x33 + x34;
        Scalar x36 = sqrt(_hp0_);
        Scalar x37 = x15 * x36;
        Scalar x38 = x35 * x37;
        Scalar x39 = x2 * x4;
        Scalar x40 = 2 * x39;
        Scalar x41 = -_hp1_ + x11;
        Scalar x42 = x1 * x8 - x1 + x3 * x40 + x41;
        Scalar x43 = x37 * x42;
        Scalar x44 = _hp1_ * x3;
        Scalar x45 = _hp2_ * x4;
        Scalar x46 = x44 + x45;
        Scalar x47 = x31 + x39 + x46;
        Scalar x48 = 2 * x37;
        Scalar x49 = (Scalar(1.0) / (x17 * x17));
        Scalar x50 = x15 * x49;
        Scalar x51 = x0 * x50;
        Scalar x52 = x12 * x51;
        Scalar x53 = _hp1_ * x52;
        Scalar x54 = _hp2_ * x52;
        Scalar x55 = -x54;
        Scalar x56 = 2 * x44;
        Scalar x57 = 2 * x45;
        Scalar x58 = x56 + x57;
        Scalar x59 = -x0 * x15 * x18 * x58;
        Scalar x60 = x12 * x3;
        Scalar x61 = (Scalar(1.0) / (x14 * x14));
        Scalar x62 = x18 * x61;
        Scalar x63 = 2 * x62;
        Scalar x64 = x60 * x63;
        Scalar x65 = -x0 * x64 - x59;
        Scalar x66 = -2 * _hp2_ * x3 + x22;
        Scalar x67 = -x66;
        Scalar x68 = x12 * x63;
        Scalar x69 = x0 * x68;
        Scalar x70 = x0 * x15 * x18 * x67 - x4 * x69;
        Scalar x71 = -_hp2_ - x34;
        Scalar x72 = x19 * x71;
        Scalar x73 = _hp1_ * x2;
        Scalar x74 = _hp2_ * x1 - x73;
        Scalar x75 = x50 * x74;
        Scalar x76 = x12 * x75;
        Scalar x77 = x0 * x72 + x0 * x76;
        Scalar x78 = x25 * x51;
        Scalar x79 = _hp1_ * x78;
        Scalar x80 = _hp2_ * x78;
        Scalar x81 = -x80;
        Scalar x82 = -x0 * x15 * x18 * x66;
        Scalar x83 = x25 * x63;
        Scalar x84 = x3 * x83;
        Scalar x85 = -x0 * x84 - x82;
        Scalar x86 = x0 * x83;
        Scalar x87 = -x4 * x86 - x59;
        Scalar x88 = -x41;
        Scalar x89 = x19 * x88;
        Scalar x90 = x25 * x75;
        Scalar x91 = x0 * x89 + x0 * x90;
        Scalar x92 = 2 * _hp1_;
        Scalar x93 = x28 * x51;
        Scalar x94 = x92 * x93;
        Scalar x95 = 2 * _hp2_;
        Scalar x96 = x93 * x95;
        Scalar x97 = -x96;
        Scalar x98 = x19 * x95;
        Scalar x99 = x0 * x98;
        Scalar x100 = 4 * x62;
        Scalar x101 = x28 * x3;
        Scalar x102 = x100 * x101;
        Scalar x103 = -x0 * x102 + x99;
        Scalar x104 = x0 * x19;
        Scalar x105 = x104 * x92;
        Scalar x106 = x100 * x28;
        Scalar x107 = x0 * x106;
        Scalar x108 = -x105 - x107 * x4;
        Scalar x109 = x29 * x46;
        Scalar x110 = x0 * x75;
        Scalar x111 = 2 * x28;
        Scalar x112 = x0 * x109 + x110 * x111;
        Scalar x113 = 1.0 / x0;
        Scalar x114 = (1.0 / 2.0) * x113;
        Scalar x115 = x114 * x38;
        Scalar x116 = x3 * x48;
        Scalar x117 = x116 * x4;
        Scalar x118 = x8 + 1;
        Scalar x119 = x118 * x37;
        Scalar x120 = 2 * x1;
        Scalar x121 = -x120 * x4 + 2 * x2 * x3 - x66;
        Scalar x122 = -x121 * x37;
        Scalar x123 = x36 * x61;
        Scalar x124 = 2 * x123;
        Scalar x125 = x124 * x35;
        Scalar x126 = x122 + x125 * x3;
        Scalar x127 = x32 + x40 + x58;
        Scalar x128 = -x127;
        Scalar x129 = x125 * x4 - x128 * x37;
        Scalar x130 = x12 * x37;
        Scalar x131 = x114 * x43;
        Scalar x132 = -x13 + x6;
        Scalar x133 = x132 * x37;
        Scalar x134 = x124 * x42;
        Scalar x135 = -x127 * x37 + x134 * x3;
        Scalar x136 = x122 + x134 * x4;
        Scalar x137 = x25 * x37;
        Scalar x138 = x113 * x37;
        Scalar x139 = x138 * x47;
        Scalar x140 = x4 * x48;
        Scalar x141 = _hp1_ + x1;
        Scalar x142 = 4 * x123;
        Scalar x143 = x142 * x47;
        Scalar x144 = 2 * x141 * x15 * x36 - x143 * x3;
        Scalar x145 = -x143 * x4 + 2 * x15 * x33 * x36;
        Scalar x146 = x27 * x48;
        Scalar x147 = LM0 * x53 + LM1 * x79 + LM2 * x94;
        Scalar x148 = LM2 * x96;
        Scalar x149 = LM0 * x54;
        Scalar x150 = LM1 * x80;
        Scalar x151 = LM3 * x130;
        Scalar x152 = LM4 * x137;
        Scalar x153 = (Scalar(1.0) / (x0 * x0));
        Scalar x154 = (3.0 / 4.0) * x153;
        Scalar x155 = LM5 * x138;
        Scalar x156 = x3 * x4;
        Scalar x157 = LM2 * x28;
        Scalar x158 = x157 * x50;
        Scalar x159 = _hp1_ * x50;
        Scalar x160 = LM0 * x12;
        Scalar x161 = LM1 * x25;
        Scalar x162 = -LM3 * x138 * x156 + (1.0 / 2.0) * LM4 * x113 * x132 * x15 * x36 - x155 * x3 -
                      x158 * x92 - x159 * x160 - x159 * x161;
        Scalar x163 = _hp2_ * x50;
        Scalar x164 = (1.0 / 2.0) * LM3 * x113 * x118 * x15 * x36 +
                      LM4 * x113 * x15 * x3 * x36 * x4 - x155 * x4 - x158 * x95 - x160 * x163 -
                      x161 * x163;
        Scalar x165 = x138 * x141;
        Scalar x166 = x3 * x63;
        Scalar x167 = x123 * x3;
        Scalar x168 = x113 * x167;
        Scalar x169 = x168 * x35;
        Scalar x170 = x168 * x42;
        Scalar x171 = x138 * x33;
        Scalar x172 = x19 * x92;
        Scalar x173 = x106 * x4;
        Scalar x174 = x4 * x63;
        Scalar x175 = x123 * x4;
        Scalar x176 = x113 * x175;
        Scalar x177 = x176 * x35;
        Scalar x178 = x176 * x42;
        Scalar x179 = x111 * x75;
        Scalar x180 = x114 * x151 + x114 * x152 - x155 * x27;
        Scalar x181 = (_hp1_ * _hp1_);
        Scalar x182 = x15 / (x17 * x17 * x17);
        Scalar x183 = x0 * x182;
        Scalar x184 = x181 * x183;
        Scalar x185 = 4 * x157;
        Scalar x186 = 2 * x184;
        Scalar x187 = _hp1_ * x183;
        Scalar x188 = x187 * x95;
        Scalar x189 = _hp2_ * x185 * x187 + x160 * x188 + x161 * x188;
        Scalar x190 = x142 * x6;
        Scalar x191 = x190 * x4;
        Scalar x192 = x124 * x3;
        Scalar x193 = x132 * x192;
        Scalar x194 = _hp1_ * x51;
        Scalar x195 = x194 * x58;
        Scalar x196 = x194 * x66;
        Scalar x197 = x194 * x95;
        Scalar x198 = LM2 * x197;
        Scalar x199 = x49 * x61;
        Scalar x200 = x199 * x56;
        Scalar x201 = x0 * x200;
        Scalar x202 = x0 * x185 * x199;
        Scalar x203 = LM5 * x48;
        Scalar x204 = LM3 * x140 - LM4 * x116 + x203;
        Scalar x205 = x142 * x3;
        Scalar x206 = LM5 * x205 * x4;
        Scalar x207 = -x206;
        Scalar x208 = x142 * x7;
        Scalar x209 = x208 * x3;
        Scalar x210 = 2 * x51;
        Scalar x211 = x181 * x210;
        Scalar x212 = x124 * x4;
        Scalar x213 = x132 * x212;
        Scalar x214 = x194 * x67;
        Scalar x215 = x199 * x22;
        Scalar x216 = x0 * x215;
        Scalar x217 = LM3 * x116 + LM4 * x140;
        Scalar x218 = x46 * x51;
        Scalar x219 = x218 * x92;
        Scalar x220 = x182 * (2 * _hp2_ * x1 - 2 * x73);
        Scalar x221 = x0 * x220;
        Scalar x222 = x157 * x221;
        Scalar x223 = x194 * x88;
        Scalar x224 = x194 * x71;
        Scalar x225 = _hp1_ * x221;
        Scalar x226 = (_hp2_ * _hp2_);
        Scalar x227 = x183 * x226;
        Scalar x228 = 2 * x227;
        Scalar x229 = x210 * x226;
        Scalar x230 = _hp2_ * x51;
        Scalar x231 = x230 * x58;
        Scalar x232 = x230 * x66;
        Scalar x233 = x118 * x212;
        Scalar x234 = x230 * x67;
        Scalar x235 = x199 * x57;
        Scalar x236 = x0 * x235;
        Scalar x237 = x230 * x71;
        Scalar x238 = x230 * x88;
        Scalar x239 = x218 * x95;
        Scalar x240 = _hp2_ * x221;
        Scalar x241 = x113 * x47;
        Scalar x242 = -x15 * x18 * x58;
        Scalar x243 = -1.0 / 2.0 * x113 * x121 * x15 * x36;
        Scalar x244 = -2 * x15 * x36;
        Scalar x245 = -2 * x15 * x36 * x4 + x191;
        Scalar x246 = -x116;
        Scalar x247 = -x195;
        Scalar x248 = x0 * x12;
        Scalar x249 = x0 * x25;
        Scalar x250 = -x231;
        Scalar x251 = x10 * x199;
        Scalar x252 = (Scalar(1.0) / (x14 * x14 * x14));
        Scalar x253 = 8 * x0;
        Scalar x254 = x253 * x62;
        Scalar x255 = x0 * x58;
        Scalar x256 = x100 * x3;
        Scalar x257 = x18 * x252;
        Scalar x258 = x0 * x66;
        Scalar x259 = 2 * x2 + x95;
        Scalar x260 = x259 * x37;
        Scalar x261 = -2 * x35 * x36 * x61;
        Scalar x262 = x252 * x36;
        Scalar x263 = 8 * x262 * x6;
        Scalar x264 = x120 + x92;
        Scalar x265 = -2 * x36 * x42 * x61;
        Scalar x266 = x142 * x4;
        Scalar x267 = x0 * x100;
        Scalar x268 = x0 * x101;
        Scalar x269 = x0 * x166;
        Scalar x270 = x253 * x257;
        Scalar x271 = -x264 * x37;
        Scalar x272 = 8 * x156 * x262;
        Scalar x273 =
            LM0 * (-x174 * x255 - x269 * x67 + x270 * x4 * x60 + x99) +
            LM1 * (x105 + x156 * x25 * x270 - x166 * x255 - x174 * x258) +
            LM2 * (16 * x257 * x268 * x4 + x267 * x44 - x267 * x45) +
            LM3 * (2 * x121 * x36 * x4 * x61 + 2 * x128 * x3 * x36 * x61 - x271 - x272 * x35) +
            LM4 * (2 * x121 * x3 * x36 * x61 + 2 * x127 * x36 * x4 * x61 - x260 - x272 * x42) +
            LM5 * (-x141 * x266 - x205 * x33 + 16 * x252 * x3 * x36 * x4 * x47);
        Scalar x274 = x37 * x58;
        Scalar x275 = -x274;
        Scalar x276 = x124 * x60;
        Scalar x277 = x37 * x66;
        Scalar x278 = x192 * x25;
        Scalar x279 = x37 * x95;
        Scalar x280 = x205 * x27;
        Scalar x281 = 2 * x199;
        Scalar x282 = x0 * x281;
        Scalar x283 = -x0 * x15 * x49 * x58 * x74 + x82;
        Scalar x284 = x25 * x74;
        Scalar x285 = x282 * x284;
        Scalar x286 = 4 * x199;
        Scalar x287 =
            LM0 * (-x269 * x71 - x282 * x60 * x74 - x283) +
            LM1 * (-x0 * x15 * x18 * x58 + x0 * x15 * x49 * x66 * x74 - x269 * x88 - x285 * x3) +
            LM2 * (-x0 * x256 * x46 + x105 + x110 * x95 - x268 * x286 * x74);
        Scalar x288 = x209 + x246;
        Scalar x289 = x0 * x28;
        Scalar x290 = x286 * x289;
        Scalar x291 = x257 * x7;
        Scalar x292 = x267 * x4;
        Scalar x293 = 8 * x262 * x7;
        Scalar x294 = x37 * x67;
        Scalar x295 = x12 * x212;
        Scalar x296 = x212 * x25;
        Scalar x297 = x37 * x92;
        Scalar x298 = x266 * x27;
        Scalar x299 = x0 * x174;
        Scalar x300 = x248 * x74;
        Scalar x301 = LM0 * (x0 * x15 * x49 * x67 * x74 - x281 * x300 * x4 - x299 * x71 - x59) +
                      LM1 * (-x283 - x285 * x4 - x299 * x88) +
                      LM2 * (-x110 * x92 - x290 * x4 * x74 - x292 * x46 + x99);
        Scalar x302 = 4 * x182 * x289 * x74;
        Scalar x303 = x182 * x300;
        Scalar x304 = x183 * x284;
        Scalar x305 = 2 * x110;

        _fx_[0] = x0 * x20;
        _fx_[1] = x0 * x26;
        _fx_[2] = x0 * x30;
        _fx_[3] = -x38;
        _fx_[4] = -x43;
        _fx_[5] = x47 * x48;

        _jx_(0, 0) = x20;
        _jx_(1, 0) = x26;
        _jx_(2, 0) = x30;
        _jx_(3, 0) = x115;
        _jx_(4, 0) = x131;
        _jx_(5, 0) = -x139;
        _jx_(0, 1) = -x53;
        _jx_(1, 1) = -x79;
        _jx_(2, 1) = -x94;
        _jx_(3, 1) = x117;
        _jx_(4, 1) = -x133;
        _jx_(5, 1) = x116;
        _jx_(0, 2) = x55;
        _jx_(1, 2) = x81;
        _jx_(2, 2) = x97;
        _jx_(3, 2) = -x119;
        _jx_(4, 2) = -x117;
        _jx_(5, 2) = x140;
        _jx_(0, 3) = x65;
        _jx_(1, 3) = x85;
        _jx_(2, 3) = x103;
        _jx_(3, 3) = x126;
        _jx_(4, 3) = x135;
        _jx_(5, 3) = x144;
        _jx_(0, 4) = x70;
        _jx_(1, 4) = x87;
        _jx_(2, 4) = x108;
        _jx_(3, 4) = x129;
        _jx_(4, 4) = x136;
        _jx_(5, 4) = x145;
        _jx_(0, 5) = x77;
        _jx_(1, 5) = x91;
        _jx_(2, 5) = x112;
        _jx_(3, 5) = -x130;
        _jx_(4, 5) = -x137;
        _jx_(5, 5) = x146;

        _gx_[0] = LM0 * x20 + LM1 * x26 + LM2 * x30 + LM3 * x115 + LM4 * x131 - LM5 * x139;
        _gx_[1] = 2 * LM3 * x15 * x3 * x36 * x4 - LM4 * x133 + 2 * LM5 * x15 * x3 * x36 - x147;
        _gx_[2] = -LM3 * x119 - LM4 * x117 + 2 * LM5 * x15 * x36 * x4 - x148 - x149 - x150;
        _gx_[3] = LM0 * x65 + LM1 * x85 + LM2 * x103 + LM3 * x126 + LM4 * x135 + LM5 * x144;
        _gx_[4] = LM0 * x70 + LM1 * x87 + LM2 * x108 + LM3 * x129 + LM4 * x136 + LM5 * x145;
        _gx_[5] = LM0 * x77 + LM1 * x91 + LM2 * x112 + LM5 * x146 - x151 - x152;

        _hx_(0, 0) =
            -LM3 * x154 * x38 - LM4 * x154 * x43 + (3.0 / 2.0) * LM5 * x15 * x153 * x36 * x47;
        _hx_(0, 1) = x162;
        _hx_(1, 1) = x160 * x186 + x161 * x186 + x184 * x185;
        _hx_(0, 2) = x164;
        _hx_(1, 2) = x189;
        _hx_(2, 2) = x160 * x228 + x161 * x228 + x185 * x227;
        _hx_(0, 3) = LM0 * x15 * x18 * x58 + LM1 * x15 * x18 * x66 + 2 * LM2 * _hp2_ * x15 * x18 -
                     LM2 * x102 + (1.0 / 2.0) * LM3 * x113 * x121 * x15 * x36 - LM3 * x169 +
                     (1.0 / 2.0) * LM4 * x113 * x127 * x15 * x36 - LM4 * x170 +
                     2 * LM5 * x113 * x3 * x36 * x47 * x61 - LM5 * x165 - x160 * x166 - x161 * x166;
        _hx_(1, 3) = -LM0 * x195 - LM1 * x196 - LM3 * x191 + LM4 * x193 - LM5 * x190 + x160 * x201 +
                     x161 * x201 - x198 + x202 * x44 + x204;
        _hx_(2, 3) = 2 * LM0 * _hp2_ * x0 * x12 * x3 * x49 * x61 - LM0 * x231 +
                     2 * LM1 * _hp2_ * x0 * x25 * x3 * x49 * x61 - LM1 * x232 +
                     4 * LM2 * _hp2_ * x0 * x28 * x3 * x49 * x61 - LM2 * x229 +
                     2 * LM3 * x118 * x3 * x36 * x61 + 4 * LM4 * x36 * x4 * x6 * x61 - x206 - x217;
        _hx_(3, 3) = LM0 * (x105 + x12 * x253 * x257 * x6 - x255 * x256 - x69) +
                     LM1 * (8 * x0 * x18 * x25 * x252 * x6 - x256 * x258 - x86 - x99) +
                     LM2 * (16 * x0 * x18 * x252 * x28 * x6 - x107 - x254 * x9) +
                     LM3 * (4 * x121 * x3 * x36 * x61 - x260 - x261 - x263 * x35) +
                     LM4 * (4 * x127 * x3 * x36 * x61 - x263 * x42 - x264 * x37 - x265) +
                     LM5 * (-8 * x141 * x167 - x143 + 16 * x252 * x36 * x47 * x6);
        _hx_(0, 4) = LM0 * x15 * x18 * x67 + LM1 * x15 * x18 * x58 - LM2 * x172 - LM2 * x173 +
                     (1.0 / 2.0) * LM3 * x113 * x128 * x15 * x36 - LM3 * x177 +
                     (1.0 / 2.0) * LM4 * x113 * x121 * x15 * x36 - LM4 * x178 +
                     2 * LM5 * x113 * x36 * x4 * x47 * x61 - LM5 * x171 - x160 * x174 - x161 * x174;
        _hx_(1, 4) = -LM0 * x214 - LM1 * x195 + LM2 * x211 - LM3 * x209 + LM4 * x213 + x160 * x216 +
                     x161 * x216 + x202 * x21 + x207 + x217;
        _hx_(2, 4) = -LM0 * x234 - LM1 * x231 + LM3 * x233 + LM4 * x209 - LM5 * x208 + x160 * x236 +
                     x161 * x236 + x198 + x202 * x45 + x204;
        _hx_(3, 4) = x273;
        _hx_(4, 4) = LM0 * (8 * x0 * x12 * x18 * x252 * x7 - x105 - x292 * x67 - x69) +
                     LM1 * (-x100 * x255 * x4 + x25 * x253 * x291 - x86 + x99) +
                     LM2 * (-x107 + x21 * x254 + 16 * x289 * x291) +
                     LM3 * (4 * x128 * x36 * x4 * x61 + x259 * x37 - x261 - x293 * x35) +
                     LM4 * (4 * x121 * x36 * x4 * x61 - x265 - x271 - x293 * x42) +
                     LM5 * (-x143 - 8 * x175 * x33 + 16 * x252 * x36 * x47 * x7);
        _hx_(0, 5) = LM0 * x72 + LM0 * x76 + LM1 * x89 + LM1 * x90 + LM2 * x109 + LM2 * x179 + x180;
        _hx_(1, 5) = -LM0 * x224 - LM1 * x223 - LM2 * x219 + x148 + x149 + x150 - x160 * x225 -
                     x161 * x225 - x222 * x92;
        _hx_(2, 5) =
            -LM0 * x237 - LM1 * x238 - LM2 * x239 - x147 - x160 * x240 - x161 * x240 - x222 * x95;
        _hx_(3, 5) = LM3 * (x275 + x276) + LM4 * (-x277 + x278) + LM5 * (-x279 - x280) + x287;
        _hx_(4, 5) = LM3 * (-x294 + x295) + LM4 * (x275 + x296) + LM5 * (x297 - x298) + x301;
        _hx_(5, 5) =
            LM0 * (-x104 * x12 + x16 * x52 + x220 * x300 + x305 * x71) +
            LM1 * (-x104 * x25 + x16 * x78 + x221 * x284 + x305 * x88) +
            LM2 * (x0 * x27 * x29 + 4 * x110 * x46 + x111 * x221 * x74 + x16 * x210 * x28) -
            LM3 * x37 * x71 - LM4 * x37 * x88 - x203 * x46;

        _hx_(1, 0) = _hx_(0, 1);
        _hx_(2, 0) = _hx_(0, 2);
        _hx_(3, 0) = _hx_(0, 3);
        _hx_(4, 0) = _hx_(0, 4);
        _hx_(5, 0) = _hx_(0, 5);
        _hx_(2, 1) = _hx_(1, 2);
        _hx_(3, 1) = _hx_(1, 3);
        _hx_(4, 1) = _hx_(1, 4);
        _hx_(5, 1) = _hx_(1, 5);
        _hx_(3, 2) = _hx_(2, 3);
        _hx_(4, 2) = _hx_(2, 4);
        _hx_(5, 2) = _hx_(2, 5);
        _hx_(4, 3) = _hx_(3, 4);
        _hx_(5, 3) = _hx_(3, 5);
        _hx_(5, 4) = _hx_(4, 5);
    }
};

} // namespace tycho::astro
