"""TychoHeaderGen — SymPy-based C++ VectorFunction code generator.

Generates CSE-optimized VectorFunction structs with analytic Jacobian,
adjoint gradient, and adjoint Hessian from SymPy expression matrices.

Usage:
    from CodeGen import TychoHeaderGen

    header = TychoHeaderGen("MyFunc", Eq, sp.Matrix(Xs),
                            [(mu, "gravitational parameter")])
    header.make_header(output_dir="include/tycho/detail/astro")
"""

import os
import re

import sympy as sp

# Indent unit used in generated code
_IND = "    "

# Copyright header template
_COPYRIGHT = """\
// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by {script} — do not edit manually.
// =============================================================================
"""

# Using declarations injected into the namespace block
_USING_DECLS = """\
// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;
"""


class TychoHeaderGen:
    def __init__(
        self,
        Name,
        F,
        Xs,
        ScalarParams=[],  # [(Symbol, Description),]
        VectorParams=[],  # [(Vec, Cppname, Description),]
        MatrixParams=[],  # [(Mat, Cppname, Description),]
        docstr="A doc string",
        namespace="tycho::astro",
        include_path="tycho/vector_functions.h",
        gen_build_method=False,
    ):

        self.Name = Name
        self.namespace = namespace
        self.include_path = include_path
        self.gen_build_method = gen_build_method
        self.ninputs = len(Xs)
        self.noutputs = len(F)

        # Rename scalar param symbols to the member-convention trailing
        # underscore form (e.g. mu → mu_) so the generated compute bodies
        # reference the C++ member directly. The original (non-underscore)
        # name is preserved as the constructor parameter name.
        param_subs = {}
        renamed_scalar_params = []
        self._ctor_arg_for = {}
        for sym, descr in ScalarParams:
            name = str(sym)
            if name.endswith("_"):
                renamed_scalar_params.append((sym, descr))
                continue
            new_sym = sp.Symbol(name + "_")
            param_subs[sym] = new_sym
            renamed_scalar_params.append((new_sym, descr))
            self._ctor_arg_for[name + "_"] = name

        if param_subs:
            F = sp.Matrix(list(F)).xreplace(param_subs)

        self.Func = sp.Matrix(list(F))
        self.Inputs = sp.Matrix(list(Xs))
        self.ScalarParams = renamed_scalar_params
        self.VectorParams = VectorParams
        self.MatrixParams = MatrixParams

        self.docstr = docstr

        # Input symbol names (for dependency analysis)
        self._input_syms = {s for s in self.Inputs}

        print("Generating Jacobian")
        self.Jac = self.Func.jacobian(self.Inputs)
        print("Finished Jacobian")
        self.LMults = sp.Matrix(sp.symbols("LM:" + str(self.noutputs)))
        print("Generating Gradient")
        self.Grad = self.Jac.transpose() * self.LMults
        print("Finished Gradient")
        print("Generating Hessian")
        self.Hess = self.Grad.jacobian(self.Inputs)
        print("Finished Hessian")

        # Precomputed parameter-only subexpressions.
        # Substituted into Func/Jac/Grad/Hess at the SymPy level so that
        # per-method CSE naturally uses the member symbols (pcN_).
        self._precomputed = []  # [(member_name, resolved_expr), ...]
        self._identify_precomputed()

    def _identify_precomputed(self):
        """Find param-only CSE subexpressions and substitute into expressions.

        Runs CSE on the full expression set, identifies subexpressions that
        depend only on constructor parameters (not inputs), then rebuilds
        Func/Jac/Grad/Hess with member symbols (pcN_) in place of those
        subexpressions. Works by expanding all input-dependent CSE variables
        back while keeping param-only ones as pcN_ atoms, so per-method CSE
        in _gen_cse_body() naturally re-optimizes without duplicating the
        precomputed work.
        """
        print("Identifying parameter-only subexpressions")
        all_cses, reduced = sp.cse([self.Func, self.Jac, self.Grad, self.Hess])
        param_cses, input_cses = self._partition_cses(all_cses)

        if not param_cses:
            print("  No parameter-only subexpressions found")
            return

        print(f"  Found {len(param_cses)} parameter-only subexpressions")

        # Build param CSE sym → member sym map and constructor expressions
        param_map = {}  # cse_sym → member_sym
        for i, (cse_sym, cse_expr) in enumerate(param_cses):
            member_name = f"pc{i}_"
            member_sym = sp.Symbol(member_name)
            param_map[cse_sym] = member_sym
            # Constructor expression: resolve earlier CSE refs to pcN_
            resolved = cse_expr.subs(
                [(s, m) for s, m in param_map.items() if s != cse_sym]
            )
            self._precomputed.append((member_name, resolved))

        # Build expansion map for all CSE symbols:
        # - param CSE syms → pcN_ member symbols
        # - input CSE syms → their RHS with all CSE refs fully expanded
        #   (param refs become pcN_, input refs become their expanded forms)
        expansion = dict(param_map)
        for cse_sym, cse_expr in input_cses:
            expanded = cse_expr
            for s, repl in expansion.items():
                expanded = expanded.subs(s, repl)
            expansion[cse_sym] = expanded

        # Expand reduced expressions: replace all CSE symbols with their
        # expanded forms. The result contains pcN_ atoms but no CSE vars.
        print("  Substituting into Func/Jac/Grad/Hess")
        subs_list = list(expansion.items())
        new_exprs = []
        for item in reduced:
            if isinstance(item, sp.Matrix):
                new_exprs.append(item.subs(subs_list))
            elif isinstance(item, list):
                new_exprs.append([e.subs(subs_list) for e in item])
            else:
                new_exprs.append(item.subs(subs_list))

        self.Func = new_exprs[0]
        self.Jac = new_exprs[1]
        self.Grad = new_exprs[2]
        self.Hess = new_exprs[3]

    def _partition_cses(self, cses):
        """Split CSE list into (param_only, input_dependent).

        A CSE variable is parameter-only if its RHS expression contains
        no input symbols and no CSE variables that depend on inputs.
        """
        param_syms = set()
        for P, _ in self.ScalarParams:
            param_syms.add(P)
        for Vec, _, _ in self.VectorParams:
            for elem in Vec:
                param_syms.add(elem)
        for Mat, _, _ in self.MatrixParams:
            for elem in Mat:
                param_syms.add(elem)

        # Track which CSE symbols are parameter-only
        param_only_syms = set()
        param_cses = []
        input_cses = []

        for sym, expr in cses:
            free = expr.free_symbols
            if free <= (param_syms | param_only_syms):
                param_only_syms.add(sym)
                param_cses.append((sym, expr))
            else:
                input_cses.append((sym, expr))

        return param_cses, input_cses

    # ── pow simplification ──────────────────────────────────────────────

    def powsimp(self, expr):
        powcount = expr.count("pow")
        if powcount == 0:
            return expr

        # Convert integer pows to multiplies: pow(x, 2) → (x*x)
        # Parentheses prevent precedence bugs in denominator context
        # e.g. 1/pow(x, 2) → 1/(x*x) not 1/x*x
        for i in range(2, 16):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*{i}\s*\)")
            repl = r"(\g<var>"
            for j in range(1, i):
                repl += r"*\g<var>"
            repl += r")"
            expr = re.sub(regex, repl, expr)

        # Convert pow(x, 0.5) → sqrt(x), pow(x, 1.5) → sqrt(x)*x, etc.
        for i in range(0, 7):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*{i}\.5\s*\)")
            repl = r"(sqrt(\g<var>)"
            for j in range(1, i + 1):
                repl += r"*\g<var>"
            repl += r")"
            expr = re.sub(regex, repl, expr)

        # Convert pow(x, -N) → Scalar(1.0)/(x*x*...)
        for i in range(1, 16):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*-{i}\s*\)")
            repl = r"(Scalar(1.0)/(\g<var>"
            for j in range(1, i):
                repl += r"*\g<var>"
            repl += r"))"
            expr = re.sub(regex, repl, expr)

        # Convert pow(x, -0.5) → Scalar(1.0)/sqrt(x)
        for i in range(0, 7):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*-{i}\.5\s*\)")
            repl = r"(Scalar(1.0)/(sqrt(\g<var>)"
            for j in range(1, i + 1):
                repl += r"*\g<var>"
            repl += r"))"
            expr = re.sub(regex, repl, expr)

        # Fractional forms: pow(x, 3.0/2.0) style
        for i in range(1, 10, 2):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*{i}\.0/2\.0\s*\)")
            repl = r"(sqrt(\g<var>)"
            for j in range(0, int((i - 1) / 2)):
                repl += r"*\g<var>"
            repl += r")"
            expr = re.sub(regex, repl, expr)

        for i in range(1, 10, 2):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*-{i}\.0/2\.0\s*\)")
            repl = r"(Scalar(1.0)/(sqrt(\g<var>)"
            for j in range(0, int((i - 1) / 2)):
                repl += r"*\g<var>"
            repl += r"))"
            expr = re.sub(regex, repl, expr)

        # Last-resort for compound-expression pow with single occurrence
        powcount = expr.count("pow")
        commacount = expr.count(",")
        if powcount == 1 and commacount == 1:
            for i in range(0, 7):
                regex = re.compile(rf"pow\((?P<var>\s*([^,]+)),\s*-{i}\.5\s*\)")
                repl = r"(Scalar(1.0)/(sqrt(Scalar(\g<var>))"
                for j in range(1, i + 1):
                    repl += r"*Scalar(\g<var>)"
                repl += r"))"
                expr = re.sub(regex, repl, expr)

        return expr

    # ── fixup: scalar-wrap parameters, apply powsimp ────────────────────

    def fixup(self, expr):
        wrapscalar = False

        for Param, Descr in self.ScalarParams:
            Name = str(Param)
            if Name in expr:
                wrapscalar = True

        for Vec, Name, Descr in self.VectorParams:
            for i, elem in enumerate(Vec):
                symname = str(elem)
                if symname in expr:
                    replname = "({0:}[{1:}])".format(Name, i)
                    regex = re.compile(rf"\b{symname}\b")
                    expr = re.sub(symname, replname, expr)
                    wrapscalar = True

        for Mat, Name, Descr in self.MatrixParams:
            rows = len(Mat)
            cols = len(Mat[0])
            for i in range(0, rows):
                for j in range(0, cols):
                    symname = str(Mat[i, j])
                    if symname in expr:
                        replname = "({0:}({1:},{2:}))".format(Name, i, j)
                        regex = re.compile(rf"\b{symname}\b")
                        expr = re.sub(regex, replname, expr)
                        wrapscalar = True

        # Check for precomputed member references (pcN_)
        for member_name, _ in self._precomputed:
            if member_name in expr:
                wrapscalar = True

        if wrapscalar:
            expr = "Scalar(" + expr + ")"

        expr = self.powsimp(expr)

        return expr

    # ── CSE generation with precomputed hoisting ────────────────────────

    def _gen_cse_body(self, exprs):
        """Run CSE on exprs and return (cses, reduced_exprs).

        Parameter-only subexpressions have already been substituted with
        member symbols (pcN_) in _identify_precomputed(), so no partitioning
        is needed here — CSE just operates on what remains.

        Before running CSE, we walk the expression tree and extract compound
        bases of half-integer powers (``Pow(base, Rational(n, 2))`` with an
        Add/Mul base) into fresh ``_hpN_`` symbols. This gives the downstream
        regex post-processor a bare identifier to rewrite, so expressions
        like ``pow((x0*x0 + x1*x1 + x2*x2), 3.0/2.0)`` become
        ``sqrt(_hp0_) * _hp0_`` with ``_hp0_`` assigned once as its own
        temporary — avoiding a runtime ``pow()`` call.
        """
        pre_cses, rewritten = self._extract_compound_pow_bases(exprs)
        cses, reduced = sp.cse(rewritten)
        # Prepend halfpow temporaries so they're emitted before the
        # regular CSE assignments that reference them.
        return pre_cses + cses, reduced

    def _extract_compound_pow_bases(self, exprs):
        """Pre-CSE: replace Pow(compound, n/2) bases with _hpN_ symbols.

        Returns (pow_cses, rewritten_exprs) where ``pow_cses`` is a
        list of ``(Symbol, compound_base)`` pairs that should be emitted as
        assignments before the regular CSE body. Bases are de-duplicated by
        structural equality so identical compound bases share one temporary.
        """
        pow_cses = []  # [(Symbol, compound_expr)]
        base_to_sym = {}  # compound_expr → Symbol
        counter = [0]

        def _rewrite(expr):
            if not isinstance(expr, sp.Basic) or expr.is_Atom:
                return expr
            # Post-order: rewrite args first.
            new_args = tuple(_rewrite(a) for a in expr.args)
            if new_args != expr.args:
                expr = expr.func(*new_args)
            if (
                isinstance(expr, sp.Pow)
                and not expr.base.is_Atom
                and not expr.base.is_Symbol
            ):
                exp = expr.exp
                # Accept half-integer exponents (Rational(n, 2)) and
                # small integer exponents n >= 2. SymPy leaves Pow(Add, n)
                # unexpanded for integer n, and the downstream regex only
                # rewrites pow(sym, n) / pow(sym, n/2) when the base is a
                # bare identifier — so compound bases need extraction.
                is_half_int = isinstance(exp, sp.Rational) and exp.q == 2
                is_small_int = isinstance(exp, sp.Integer) and 2 <= int(exp) <= 16
                if is_half_int or is_small_int:
                    base = expr.base
                    if base not in base_to_sym:
                        sym = sp.Symbol(f"_hp{counter[0]}_")
                        counter[0] += 1
                        base_to_sym[base] = sym
                        pow_cses.append((sym, base))
                    return sp.Pow(base_to_sym[base], exp)
            return expr

        def _apply(obj):
            if isinstance(obj, sp.Matrix):
                return obj.applyfunc(_rewrite)
            if isinstance(obj, list):
                return [_apply(e) for e in obj]
            if isinstance(obj, tuple):
                return tuple(_apply(e) for e in obj)
            return _rewrite(obj)

        rewritten = _apply(exprs)
        return pow_cses, rewritten

    # ── class header generation ─────────────────────────────────────────

    def gen_class_header(self):
        I = _IND
        dm = "DenseDerivativeMode::Analytic"

        lines = []
        lines.append(f"struct {self.Name}")
        lines.append(
            f"{I}: VectorFunction<{self.Name}, {self.ninputs}, "
            f"{self.noutputs}, {dm}, {dm}> {{"
        )
        lines.append(
            f"{I}using Base = VectorFunction<{self.Name}, "
            f"{self.ninputs}, {self.noutputs}, {dm}, {dm}>;"
        )
        lines.append(f"{I}VF_TYPE_ALIASES(Base);")
        lines.append("")

        # Members: scalar params + vector/matrix params
        for P, Descr in self.ScalarParams:
            lines.append(f"{I}double {P}; // {Descr}")
        for Vec, Name, Descr in self.VectorParams:
            vsize = len(Vec)
            lines.append(f"{I}Eigen::Matrix<double, {vsize}, 1> {Name}; // {Descr}")
        for Mat, Name, Descr in self.MatrixParams:
            rows, cols = len(Mat), len(Mat[0])
            lines.append(f"{I}Eigen::Matrix<double, {rows}, {cols}> {Name}; // {Descr}")

        lines.append(f"{I}static constexpr bool is_vectorizable = true;")

        # Precomputed member declarations
        if self._precomputed:
            lines.append("")
            lines.append(f"{I}// Precomputed from constructor parameters")
            for member_name, _ in self._precomputed:
                lines.append(f"{I}double {member_name};")
        lines.append("")

        # Constructor params (use the original non-underscore name so the
        # caller-facing API is e.g. MEEDynamics(double mu) rather than mu_).
        params = []
        for P, Descr in self.ScalarParams:
            ctor_arg = self._ctor_arg_for.get(str(P), str(P))
            params.append(f"double {ctor_arg}")
        for Vec, Name, Descr in self.VectorParams:
            vsize = len(Vec)
            params.append(f"const Eigen::Matrix<double, {vsize}, 1>& {Name}")
        for Mat, Name, Descr in self.MatrixParams:
            rows, cols = len(Mat), len(Mat[0])
            params.append(f"const Eigen::Matrix<double, {rows}, {cols}>& {Name}")

        paramstr = ", ".join(params)
        assigns = []
        for P, _ in self.ScalarParams:
            ctor_arg = self._ctor_arg_for.get(str(P), str(P))
            assigns.append(f"{P}({ctor_arg})")
        for Vec, Name, _ in self.VectorParams:
            assigns.append(f"{Name}({Name})")
        for Mat, Name, _ in self.MatrixParams:
            assigns.append(f"{Name}({Name})")
        initlist = ", ".join(assigns)

        # Default constructor
        lines.append(f"{I}{self.Name}() {{")
        lines.append(f"{I}{I}this->set_io_rows({self.ninputs}, {self.noutputs});")
        lines.append(f"{I}}}")

        # Parameterized constructor
        if initlist:
            lines.append(f"{I}{self.Name}({paramstr})")
            lines.append(f"{I}{I}: {initlist} {{")
        else:
            lines.append(f"{I}{self.Name}({paramstr}) {{")
        lines.append(f"{I}{I}this->set_io_rows({self.ninputs}, {self.noutputs});")

        # Precomputed initializations (use std:: prefix for math
        # functions since VF overloads may shadow them in this scope)
        if self._precomputed:
            for member_name, expr in self._precomputed:
                rhs = str(sp.ccode(expr))
                rhs = self.powsimp(rhs)
                # Prefix bare math functions with std::
                for fn in [
                    "sqrt",
                    "sin",
                    "cos",
                    "tan",
                    "asin",
                    "acos",
                    "atan",
                    "atan2",
                    "exp",
                    "log",
                ]:
                    rhs = re.sub(rf"\b{fn}\(", f"std::{fn}(", rhs)
                lines.append(f"{I}{I}{member_name} = {rhs};")

        lines.append(f"{I}}}")
        lines.append("")

        return "\n".join(lines) + "\n"

    # ── compute_impl ────────────────────────────────────────────────────

    def gen_compute_impl(self):
        I = _IND
        lines = []
        lines.append(f"{I}template <class InType, class OutType>")
        lines.append(f"{I}inline void compute_impl(CVecRef<InType> x_,")
        lines.append(f"{I}{I}{I}{I}{I}{I} CVecRef<OutType> fx_) const {{")
        lines.append(f"{I}{I}typedef typename InType::Scalar Scalar;")
        lines.append(f"{I}{I}using std::cos; using std::sin; using std::sqrt;")
        lines.append(f"{I}{I}VecRef<OutType> _fx_ = fx_.const_cast_derived();")
        lines.append("")

        body_lines = self._gen_input_names()
        cses, funcs = self._gen_cse_body(self.Func)
        body_lines += self._gen_cselist(cses)
        body_lines.append("")
        for i, F in enumerate(funcs[0]):
            body_lines.append(self._assignment(f"_fx_[{i}]", sp.ccode(F), False))
        lines += [f"{I}{I}{l}" for l in body_lines]

        lines.append(f"{I}}}")
        lines.append("")
        return "\n".join(lines) + "\n"

    # ── compute_jacobian_impl ───────────────────────────────────────────

    def gen_compute_jacobian_impl(self):
        I = _IND
        lines = []
        lines.append(f"{I}template <class InType, class OutType, class JacType>")
        lines.append(f"{I}inline void compute_jacobian_impl(CVecRef<InType> x_,")
        lines.append(f"{I}{I}{I}{I}{I}{I} CVecRef<OutType> fx_,")
        lines.append(f"{I}{I}{I}{I}{I}{I} CMatRef<JacType> jx_) const {{")
        lines.append(f"{I}{I}typedef typename InType::Scalar Scalar;")
        lines.append(f"{I}{I}using std::cos; using std::sin; using std::sqrt;")
        lines.append(f"{I}{I}VecRef<OutType> _fx_ = fx_.const_cast_derived();")
        lines.append(f"{I}{I}MatRef<JacType> _jx_ = jx_.const_cast_derived();")
        lines.append("")

        body_lines = self._gen_input_names()
        cses, funcs = self._gen_cse_body([self.Func, self.Jac])
        body_lines += self._gen_cselist(cses)
        body_lines.append("")

        for i, F in enumerate(funcs[0]):
            body_lines.append(self._assignment(f"_fx_[{i}]", sp.ccode(F), False))
        body_lines.append("")

        for col in range(self.ninputs):
            for row in range(self.noutputs):
                expr = funcs[1][row, col]
                body_lines.append(
                    self._assignment(f"_jx_({row},{col})", sp.ccode(expr), False)
                )

        lines += [f"{I}{I}{l}" for l in body_lines]
        lines.append(f"{I}}}")
        lines.append("")
        return "\n".join(lines) + "\n"

    # ── compute_jacobian_adjointgradient_adjointhessian_impl ────────────

    def gen_compute_all(self):
        I = _IND
        lines = []
        lines.append(f"{I}template <class InType, class OutType, class JacType,")
        lines.append(f"{I}{I}{I}{I} class AdjGradType, class AdjHessType,")
        lines.append(f"{I}{I}{I}{I} class AdjVarType>")
        lines.append(
            f"{I}inline void compute_jacobian_adjointgradient_adjointhessian_impl("
        )
        lines.append(f"{I}{I}CVecRef<InType> x_,")
        lines.append(f"{I}{I}CVecRef<OutType> fx_,")
        lines.append(f"{I}{I}CMatRef<JacType> jx_,")
        lines.append(f"{I}{I}CVecRef<AdjGradType> adjgrad_,")
        lines.append(f"{I}{I}CMatRef<AdjHessType> adjhess_,")
        lines.append(f"{I}{I}CVecRef<AdjVarType> adjvars) const {{")
        lines.append(f"{I}{I}typedef typename InType::Scalar Scalar;")
        lines.append(f"{I}{I}using std::cos; using std::sin; using std::sqrt;")
        lines.append(f"{I}{I}VecRef<OutType> _fx_ = fx_.const_cast_derived();")
        lines.append(f"{I}{I}MatRef<JacType> _jx_ = jx_.const_cast_derived();")
        lines.append(f"{I}{I}VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();")
        lines.append(f"{I}{I}MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();")
        lines.append("")

        body_lines = self._gen_input_names()
        body_lines += self._gen_mult_names()
        cses, funcs = self._gen_cse_body([self.Func, self.Jac, self.Grad, self.Hess])
        body_lines += self._gen_cselist(cses)
        body_lines.append("")

        for i, F in enumerate(funcs[0]):
            body_lines.append(self._assignment(f"_fx_[{i}]", sp.ccode(F), False))
        body_lines.append("")
        for col in range(self.ninputs):
            for row in range(self.noutputs):
                body_lines.append(
                    self._assignment(
                        f"_jx_({row},{col})", sp.ccode(funcs[1][row, col]), False
                    )
                )
        body_lines.append("")
        for row in range(self.ninputs):
            body_lines.append(
                self._assignment(f"_gx_[{row}]", sp.ccode(funcs[2][row]), False)
            )

        # Hessian — exploit symmetry: compute upper triangle, copy lower
        body_lines.append("")
        n = self.ninputs
        for col in range(n):
            for row in range(col + 1):  # upper triangle only
                body_lines.append(
                    self._assignment(
                        f"_hx_({row},{col})", sp.ccode(funcs[3][row, col]), False
                    )
                )
            for row in range(col + 1, n):  # lower triangle = copy
                body_lines.append(f"_hx_({row},{col}) = _hx_({col},{row});")

        lines += [f"{I}{I}{l}" for l in body_lines]
        lines.append(f"{I}}}")
        lines.append("")
        return "\n".join(lines) + "\n"

    # ── helpers ─────────────────────────────────────────────────────────

    def _assignment(self, lhs, rhs, is_scalar=False):
        """Return a single assignment line (no leading newline/indent)."""
        rhs = self.fixup(str(rhs))
        prefix = "Scalar " if is_scalar else ""
        return f"{prefix}{lhs} = {rhs};"

    def _gen_input_names(self):
        return [
            self._assignment(str(X), f"x_[{i}]", True)
            for i, X in enumerate(self.Inputs)
        ]

    def _gen_mult_names(self):
        return [
            self._assignment(str(L), f"adjvars[{i}]", True)
            for i, L in enumerate(self.LMults)
        ]

    def _gen_cselist(self, cses):
        return [self._assignment(str(cse[0]), sp.ccode(cse[1]), True) for cse in cses]

    # ── output ──────────────────────────────────────────────────────────

    def print_header(self):
        print(self._build_text())

    def make_header(self, output_dir=None, script_name=None):
        text = self._build_text(script_name=script_name)
        # Tycho convention: header files are snake_case even when the type
        # they declare is PascalCase (e.g. MEEDynamics → mee_dynamics.h).
        fname = self._snake_case(self.Name) + ".h"
        if output_dir:
            fname = os.path.join(output_dir, fname)
        with open(fname, "w") as f:
            f.write(text)

    @staticmethod
    def _snake_case(name):
        # MEEDynamics → mee_dynamics, MEEToCartesian → mee_to_cartesian
        s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
        s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
        return s.lower()

    def _build_text(self, script_name=None):
        copyright = _COPYRIGHT.format(script=script_name or "TychoHeaderGen")
        include = f'#pragma once\n#include "{self.include_path}"\n'
        ns_open = f"\nnamespace {self.namespace} {{\n\n{_USING_DECLS}\n"
        header = self.gen_class_header()
        compute = self.gen_compute_impl()
        jacobian = self.gen_compute_jacobian_impl()
        all_impl = self.gen_compute_all()
        ns_close = f"}};\n\n}} // namespace {self.namespace}\n"

        return (
            copyright
            + include
            + ns_open
            + header
            + compute
            + jacobian
            + all_impl
            + ns_close
        )
