"""TychoHeaderGen — SymPy-based C++ VectorFunction code generator.

Generates CSE-optimized VectorFunction structs with analytic Jacobian,
adjoint gradient, and adjoint Hessian from SymPy expression matrices.

Usage:
    from CodeGen import TychoHeaderGen

    header = TychoHeaderGen("MyFunc", Eq, sp.Matrix(Xs),
                            [(mu, "gravitational parameter")])
    header.make_header(output_dir="include/tycho/detail/astro")
"""

import os
import re

import sympy as sp

# Indent unit used in generated code
_IND = "    "

# Supported pow exponent ranges. Shared between powsimp (the regex-based
# post-CSE rewriter) and _extract_compound_pow_bases (the pre-CSE walker
# that lifts compound bases out of Pow). Keeping both in sync prevents a
# compound base from being lifted into an _hpN_ temporary that powsimp
# then fails to rewrite, leaving a literal pow() call in generated code.
_POW_INT_RANGE = range(2, 17)  # pow(x, 2) .. pow(x, 16)
_POW_NEG_INT_RANGE = range(1, 17)  # pow(x, -1) .. pow(x, -16)
_POW_HALF_INT_RANGE = range(0, 7)  # pow(x, ±0.5) .. pow(x, ±6.5)

# Reserved symbol pattern for precompute-discovered members.  Inputs and
# parameters that match this name pattern would be silently mis-classified
# by _partition_cses (which treats pcN_ symbols as parameters so the
# post-diff pass doesn't double-count them).
_PC_RESERVED = re.compile(r"^pc\d+_$")


def _format_default_literal(value):
    """Format a Python scalar as a C++ literal for the delegating default ctor.

    Handles int → "<n>" and float → "<x>.<y>" with a trailing decimal so
    that 1 emits as "1.0" (avoiding integer-narrowing warnings in the
    generated ctor delegation).
    """
    if isinstance(value, bool):
        # bool is a subclass of int — guard against accidental True/False.
        raise TypeError(
            f"Default value for scalar param must be int or float, got bool {value!r}"
        )
    if isinstance(value, int):
        return f"{value}.0"
    if isinstance(value, float):
        s = repr(value)
        # repr returns "1.0" for floats already; integers cast to float
        # similarly. No special handling needed beyond ensuring a decimal.
        return s if "." in s or "e" in s or "E" in s else f"{s}.0"
    raise TypeError(
        f"Default value for scalar param must be int or float, got {type(value).__name__} {value!r}"
    )


# Copyright header template
_COPYRIGHT = """\
// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by {script} — do not edit manually.
// =============================================================================
"""

# Using declarations injected into the namespace block
_USING_DECLS = """\
// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;
"""


class TychoHeaderGen:
    def __init__(
        self,
        Name,
        F,
        Xs,
        ScalarParams=[],  # [(Symbol, Description) | (Symbol, Description, Constraint) | (Symbol, Description, Constraint, DefaultValue)]
        VectorParams=[],  # [(Vec, Cppname, Description) | (..., Constraint)]
        MatrixParams=[],  # [(Mat, Cppname, Description) | (..., Constraint)]
        docstr="A doc string",
        namespace="tycho::astro",
        include_path="tycho/vector_functions.h",
        gen_build_method=False,
        compute_hessian=True,
        precompute_params=True,
        is_vectorizable=True,
    ):

        self.Name = Name
        self.namespace = namespace
        self.include_path = include_path
        self.gen_build_method = gen_build_method
        self.compute_hessian = compute_hessian
        self.precompute_params = precompute_params
        self.is_vectorizable = is_vectorizable
        self.ninputs = len(Xs)
        self.noutputs = len(F)

        # Rename scalar param symbols to the member-convention trailing
        # underscore form (e.g. mu → mu_) so the generated compute bodies
        # reference the C++ member directly. The original (non-underscore)
        # name is preserved as the constructor parameter name.
        #
        # Each scalar param is normalized to a 3-tuple
        # (member_sym, descr, constraint_or_None). The optional third
        # element is a C++ boolean expression written in terms of the
        # caller-facing (non-underscore) parameter name; it is emitted as
        # an ``if (!(<expr>)) throw std::invalid_argument(...);`` check at
        # the top of the valued constructor and any auto-generated setter.
        param_subs = {}
        renamed_scalar_params = []
        self._ctor_arg_for = {}
        # Maps member-form name (e.g. "mu_") to default value (Python scalar)
        # — used by the default constructor delegation below.
        self._scalar_param_defaults = {}
        for entry in ScalarParams:
            if len(entry) == 2:
                sym, descr = entry
                constraint = None
                default_value = None
            elif len(entry) == 3:
                sym, descr, constraint = entry
                default_value = None
            elif len(entry) == 4:
                sym, descr, constraint, default_value = entry
            else:
                raise ValueError(
                    f"ScalarParams entry must be (Symbol, Description), "
                    f"(Symbol, Description, Constraint), or "
                    f"(Symbol, Description, Constraint, DefaultValue); got {entry!r}"
                )
            name = str(sym)
            if name.endswith("_"):
                renamed_scalar_params.append((sym, descr, constraint))
                if default_value is not None:
                    self._scalar_param_defaults[name] = default_value
                continue
            new_sym = sp.Symbol(name + "_")
            param_subs[sym] = new_sym
            renamed_scalar_params.append((new_sym, descr, constraint))
            self._ctor_arg_for[name + "_"] = name
            if default_value is not None:
                self._scalar_param_defaults[name + "_"] = default_value

        if param_subs:
            F = sp.Matrix(list(F)).xreplace(param_subs)

        # Normalize vector/matrix params to 4-tuples
        # (Payload, cpp_name, descr, constraint_or_None).
        def _normalize_compound(entries, kind):
            out = []
            for entry in entries:
                if len(entry) == 3:
                    payload, name, descr = entry
                    constraint = None
                elif len(entry) == 4:
                    payload, name, descr, constraint = entry
                else:
                    raise ValueError(
                        f"{kind} entry must be (Payload, Name, Description) or "
                        f"(Payload, Name, Description, Constraint); got {entry!r}"
                    )
                out.append((payload, name, descr, constraint))
            return out

        self.Func = sp.Matrix(list(F))
        self.Inputs = sp.Matrix(list(Xs))
        self.ScalarParams = renamed_scalar_params
        self.VectorParams = _normalize_compound(VectorParams, "VectorParams")
        self.MatrixParams = _normalize_compound(MatrixParams, "MatrixParams")

        self.docstr = docstr

        # Input symbol names (for dependency analysis)
        self._input_syms = {s for s in self.Inputs}

        # Guard against user symbols colliding with the pcN_ namespace.
        # _partition_cses promotes pcN_ to "treat as parameter" so the
        # post-diff pass classifies them correctly; a user symbol named
        # pcN_ would be silently mis-classified.  Raise loudly here so
        # the failure mode is obvious at codegen time, not as a wrong
        # constructor body two passes later.
        for sym in self._input_syms:
            if _PC_RESERVED.match(str(sym)):
                raise ValueError(
                    f"Input symbol {sym!r} collides with reserved pcN_ "
                    f"namespace; rename to avoid clashing with "
                    f"precompute-discovered members."
                )
        for P, _, _ in self.ScalarParams:
            if _PC_RESERVED.match(str(P)):
                raise ValueError(
                    f"ScalarParams symbol {P!r} collides with reserved "
                    f"pcN_ namespace; rename to avoid clashing with "
                    f"precompute-discovered members."
                )

        # Precomputed parameter-only subexpressions.  Discovery runs in two
        # passes:
        #   1. Pre-diff: sp.cse on Func only, before differentiation.  Cheap
        #      (Func is small).  Substitutes pcN_ atoms into Func; chain rule
        #      on input variables preserves any param-only subexpression
        #      already in Func as a constant factor in the derivative
        #      entries, so the pcN_ atoms ride through Jac/Grad/Hess.
        #   2. Post-diff: sp.cse on the fully-differentiated set (Func, Jac,
        #      [Grad, Hess] if compute_hessian).  Catches what pre-diff
        #      can miss: (a) a single-use param subexpr in Func that
        #      becomes multi-use across derivative entries via product
        #      rule, and (b) the narrow case where differentiation
        #      synthesises a brand-new param-only function (e.g.
        #      d/dx(mu**x) = log(mu) * mu**x).  Operates on the
        #      pre-compressed set (pcN_ atoms already in place), so this
        #      pass is cheaper than running it on the un-substituted set.
        # Skip both with precompute_params=False.
        self._precomputed = []  # [(member_name, resolved_expr), ...]
        if self.precompute_params:
            self._identify_precomputed_pre_diff()

        print("Generating Jacobian")
        self.Jac = self.Func.jacobian(self.Inputs)
        print("Finished Jacobian")
        self.LMults = sp.Matrix(sp.symbols("LM:" + str(self.noutputs)))
        if self.compute_hessian:
            print("Generating Gradient")
            self.Grad = self.Jac.transpose() * self.LMults
            print("Finished Gradient")
            print("Generating Hessian")
            self.Hess = self.Grad.jacobian(self.Inputs)
            print("Finished Hessian")
        else:
            self.Grad = None
            self.Hess = None

        if self.precompute_params:
            self._identify_precomputed_post_diff()

    def _identify_precomputed_pre_diff(self):
        """Discover param-only subexpressions in Func before differentiation.

        Runs sp.cse on Func only and substitutes pcN_ symbols for the
        param-only entries.  The substituted Func is then differentiated;
        chain rule on input variables preserves the pcN_ atoms as constant
        factors in the derivative entries.

        Cheap: Func is the original symbolic input (small, before the
        Hessian explosion).  Catches the typical pattern where a function
        of mu (e.g. 1/mu, sqrt(mu)) appears in multiple Func entries.  The
        post-diff pass picks up two cases pre-diff can miss: param-only
        subexprs that show up only after product-rule expansion, and rare
        cases where differentiation synthesises a new param-only function
        (e.g. d/dx(mu**x) = log(mu) * mu**x).
        """
        print("Identifying parameter-only subexpressions (pre-diff)")
        self._absorb_precomputed_from_cse_or_none([self.Func], "Func")

    def _identify_precomputed_post_diff(self):
        """Discover any additional param-only subexpressions after differentiation.

        Some VFs introduce shared param subexpressions only in the
        derivatives (e.g. f = g(mu) * x1 * x2 has g(mu) once in Func but
        twice in Jac via product rule).  This pass catches them.

        Operates on the pre-compressed expression set (pcN_ atoms already
        substituted by the pre-diff pass), so the input set to sp.cse is
        smaller than it would have been without the pre-diff pass.  Still
        the most expensive single step in the codegen pipeline for
        nontrivial functions.
        """
        print("Identifying parameter-only subexpressions (post-diff)")
        if self.compute_hessian:
            cse_targets = [self.Func, self.Jac, self.Grad, self.Hess]
        else:
            cse_targets = [self.Func, self.Jac]
        new_exprs = self._absorb_precomputed_from_cse_or_none(
            cse_targets, "Func/Jac/Grad/Hess" if self.compute_hessian else "Func/Jac"
        )
        if new_exprs is None:
            return
        self.Func = new_exprs[0]
        self.Jac = new_exprs[1]
        if self.compute_hessian:
            self.Grad = new_exprs[2]
            self.Hess = new_exprs[3]

    def _absorb_precomputed_from_cse_or_none(self, cse_targets, label):
        """Run sp.cse on `cse_targets`, append param-only subexprs to
        self._precomputed (continuing the pcN_ numbering), and return the
        rewritten target expressions in pcN_ form.  Returns None if no new
        param-only subexpressions were discovered.
        """
        all_cses, reduced = sp.cse(cse_targets)
        param_cses, input_cses = self._partition_cses(all_cses)

        if not param_cses:
            print("  No parameter-only subexpressions found")
            # Still return the reduced form for callers that want to
            # rewrite their stored expressions; for the pre-diff path
            # there's nothing to rewrite (no pcN_ to insert), so return
            # None and let the caller leave its Func untouched.
            return None

        start_idx = len(self._precomputed)
        print(
            f"  Found {len(param_cses)} parameter-only subexpressions "
            f"(pc{start_idx}_..pc{start_idx + len(param_cses) - 1}_)"
        )

        # Build CSE sym → pcN_ member sym map.  Using xreplace (literal
        # subtree replacement) instead of subs (mathematical rewrite) -
        # the substitution is well-defined and sympy canonicalization is
        # both unnecessary and expensive on Hessian-sized expressions.
        param_map = {}
        for offset, (cse_sym, cse_expr) in enumerate(param_cses):
            member_name = f"pc{start_idx + offset}_"
            member_sym = sp.Symbol(member_name)
            param_map[cse_sym] = member_sym
            resolved = cse_expr.xreplace(
                {s: m for s, m in param_map.items() if s != cse_sym}
            )
            self._precomputed.append((member_name, resolved))

        # Build full expansion: param CSE syms → pcN_; input CSE syms →
        # their RHS with earlier CSE refs expanded.
        expansion = dict(param_map)
        for cse_sym, cse_expr in input_cses:
            expansion[cse_sym] = cse_expr.xreplace(expansion)

        print(f"  Substituting pcN_ atoms into {label}")

        def _xreplace_any(item):
            if isinstance(item, list):
                return [e.xreplace(expansion) for e in item]
            return item.xreplace(expansion)

        # Single-target pre-diff path: also rewrite self.Func directly so
        # the caller doesn't have to.
        if len(reduced) == 1:
            self.Func = _xreplace_any(reduced[0])
            return None

        return [_xreplace_any(item) for item in reduced]

    def _partition_cses(self, cses):
        """Split CSE list into (param_only, input_dependent).

        A CSE variable is parameter-only if its RHS expression contains
        no input symbols and no CSE variables that depend on inputs.
        Already-discovered pcN_ member symbols (from a previous pre-diff
        pass) count as parameters, so the post-diff pass correctly treats
        any expression rebuilt from them as still param-only.
        """
        param_syms = set()
        for P, _, _ in self.ScalarParams:
            param_syms.add(P)
        for Vec, _, _, _ in self.VectorParams:
            for elem in Vec:
                param_syms.add(elem)
        for Mat, _, _, _ in self.MatrixParams:
            for elem in Mat:
                param_syms.add(elem)
        for member_name, _ in self._precomputed:
            param_syms.add(sp.Symbol(member_name))

        # Track which CSE symbols are parameter-only
        param_only_syms = set()
        param_cses = []
        input_cses = []

        for sym, expr in cses:
            free = expr.free_symbols
            if free <= (param_syms | param_only_syms):
                param_only_syms.add(sym)
                param_cses.append((sym, expr))
            else:
                input_cses.append((sym, expr))

        return param_cses, input_cses

    # ── pow simplification ──────────────────────────────────────────────

    def powsimp(self, expr):
        powcount = expr.count("pow")
        if powcount == 0:
            return expr

        # Convert integer pows to multiplies: pow(x, 2) → (x*x)
        # Parentheses prevent precedence bugs in denominator context
        # e.g. 1/pow(x, 2) → 1/(x*x) not 1/x*x
        for i in _POW_INT_RANGE:
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*{i}\s*\)")
            repl = r"(\g<var>"
            for j in range(1, i):
                repl += r"*\g<var>"
            repl += r")"
            expr = re.sub(regex, repl, expr)

        # Convert pow(x, 0.5) → sqrt(x), pow(x, 1.5) → sqrt(x)*x, etc.
        for i in _POW_HALF_INT_RANGE:
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*{i}\.5\s*\)")
            repl = r"(sqrt(\g<var>)"
            for j in range(1, i + 1):
                repl += r"*\g<var>"
            repl += r")"
            expr = re.sub(regex, repl, expr)

        # Convert pow(x, -N) → Scalar(1.0)/(x*x*...)
        for i in _POW_NEG_INT_RANGE:
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*-{i}\s*\)")
            repl = r"(Scalar(1.0)/(\g<var>"
            for j in range(1, i):
                repl += r"*\g<var>"
            repl += r"))"
            expr = re.sub(regex, repl, expr)

        # Convert pow(x, -0.5) → Scalar(1.0)/sqrt(x)
        for i in _POW_HALF_INT_RANGE:
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*-{i}\.5\s*\)")
            repl = r"(Scalar(1.0)/(sqrt(\g<var>)"
            for j in range(1, i + 1):
                repl += r"*\g<var>"
            repl += r"))"
            expr = re.sub(regex, repl, expr)

        # Fractional forms: pow(x, 3.0/2.0) style
        for i in range(1, 10, 2):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*{i}\.0/2\.0\s*\)")
            repl = r"(sqrt(\g<var>)"
            for j in range(0, int((i - 1) / 2)):
                repl += r"*\g<var>"
            repl += r")"
            expr = re.sub(regex, repl, expr)

        for i in range(1, 10, 2):
            regex = re.compile(rf"pow\((?P<var>[A-Za-z_]\w*)\s*,\s*-{i}\.0/2\.0\s*\)")
            repl = r"(Scalar(1.0)/(sqrt(\g<var>)"
            for j in range(0, int((i - 1) / 2)):
                repl += r"*\g<var>"
            repl += r"))"
            expr = re.sub(regex, repl, expr)

        # Last-resort for compound-expression pow with single occurrence
        powcount = expr.count("pow")
        commacount = expr.count(",")
        if powcount == 1 and commacount == 1:
            for i in range(0, 7):
                regex = re.compile(rf"pow\((?P<var>\s*([^,]+)),\s*-{i}\.5\s*\)")
                repl = r"(Scalar(1.0)/(sqrt(Scalar(\g<var>))"
                for j in range(1, i + 1):
                    repl += r"*Scalar(\g<var>)"
                repl += r"))"
                expr = re.sub(regex, repl, expr)

        return expr

    # ── fixup: scalar-wrap parameters, apply powsimp ────────────────────

    def fixup(self, expr):
        wrapscalar = False

        for Param, _, _ in self.ScalarParams:
            Name = str(Param)
            if re.search(rf"\b{re.escape(Name)}\b", expr):
                wrapscalar = True

        for Vec, Name, _, _ in self.VectorParams:
            for i, elem in enumerate(Vec):
                symname = str(elem)
                if symname in expr:
                    replname = "({0:}[{1:}])".format(Name, i)
                    regex = re.compile(rf"\b{symname}\b")
                    expr = re.sub(regex, replname, expr)
                    wrapscalar = True

        for Mat, Name, _, _ in self.MatrixParams:
            rows = len(Mat)
            cols = len(Mat[0])
            for i in range(0, rows):
                for j in range(0, cols):
                    symname = str(Mat[i, j])
                    if symname in expr:
                        replname = "({0:}({1:},{2:}))".format(Name, i, j)
                        regex = re.compile(rf"\b{symname}\b")
                        expr = re.sub(regex, replname, expr)
                        wrapscalar = True

        # Check for precomputed member references (pcN_)
        for member_name, _ in self._precomputed:
            if re.search(rf"\b{re.escape(member_name)}\b", expr):
                wrapscalar = True

        if wrapscalar:
            expr = "Scalar(" + expr + ")"

        expr = self.powsimp(expr)

        return expr

    # ── CSE generation with precomputed hoisting ────────────────────────

    def _gen_cse_body(self, exprs):
        """Run CSE on exprs and return (cses, reduced_exprs).

        Parameter-only subexpressions have already been substituted with
        member symbols (pcN_) in _identify_precomputed(), so no partitioning
        is needed here — CSE just operates on what remains.

        Before running CSE, we walk the expression tree and extract compound
        bases of half-integer powers (``Pow(base, Rational(n, 2))`` with an
        Add/Mul base) into fresh ``_hpN_`` symbols. This gives the downstream
        regex post-processor a bare identifier to rewrite, so expressions
        like ``pow((x0*x0 + x1*x1 + x2*x2), 3.0/2.0)`` become
        ``sqrt(_hp0_) * _hp0_`` with ``_hp0_`` assigned once as its own
        temporary — avoiding a runtime ``pow()`` call.
        """
        pre_cses, rewritten = self._extract_compound_pow_bases(exprs)
        # Force CSE variable naming to start past the input-symbol range
        # (x0 .. x{ninputs-1}). SymPy's default numbering picks ``x0, x1, ...``
        # skipping free symbols of the expression tree, but the xreplace
        # pass in _extract_compound_pow_bases can hide input symbols behind
        # ``_hpN_`` temporaries — e.g. if every occurrence of ``cos(x5)``
        # becomes ``_hp1_``, then ``x5`` is no longer a free symbol of the
        # reduced tree, and CSE would happily mint it as a fresh temporary,
        # colliding with the ``Scalar x5 = x_[5];`` input unpack at the top
        # of the compute body.
        cse_syms = sp.numbered_symbols("x", start=self.ninputs)
        cses, reduced = sp.cse(rewritten, symbols=cse_syms)
        # Prepend compound-pow temporaries so they're emitted before the
        # regular CSE assignments that reference them.
        return pre_cses + cses, reduced

    def _extract_compound_pow_bases(self, exprs):
        """Pre-CSE: extract compound bases of Pow into ``_hpN_`` temporaries.

        Matches ``Pow(base, n/2)`` (half-integer exponents) and
        ``Pow(base, Integer(n))`` for ``n`` in ``_POW_INT_RANGE`` when
        ``base`` is compound (not an Atom or bare Symbol). Each unique
        compound base is assigned a fresh ``_hpN_`` symbol, and **every**
        occurrence of that base in the expression tree — inside Pow or
        not — is replaced with the symbol. This prevents CSE from later
        re-extracting the same compound as a duplicate temporary.

        Returns ``(pow_cses, rewritten_exprs)`` where ``pow_cses`` is an
        ordered list of ``(Symbol, base_expr)`` pairs to be emitted as
        leading assignments in the compute body. Later entries may
        reference earlier ones (nested extractions), so the RHS of each
        entry is itself xreplace-folded with the partial map accumulated
        up to that point.

        See also: ``gen_compute_all`` Hessian two-pass emission, which
        depends on this extraction not producing aliases between
        ``_hx_(i,j)`` reads and writes.
        """
        # Collision guard: make sure no user-supplied symbol matches the
        # ``_hpN_`` namespace this extractor reserves. If a caller named
        # an input or scalar parameter ``_hp0_``, the xreplace pass below
        # would silently clobber it and produce a redeclared-member C++
        # error (or worse, a silently incorrect compute body). Mirror the
        # rationale of the CSE ``start=self.ninputs`` fix in _gen_cse_body.
        _HPN_RE = re.compile(r"^_hp\d+_$")
        reserved = []
        for s in self._input_syms:
            if _HPN_RE.match(str(s)):
                reserved.append(str(s))
        for P, _, _ in self.ScalarParams:
            if _HPN_RE.match(str(P)):
                reserved.append(str(P))
        for Vec, _, _, _ in self.VectorParams:
            for elem in Vec:
                if _HPN_RE.match(str(elem)):
                    reserved.append(str(elem))
        for Mat, _, _, _ in self.MatrixParams:
            for elem in Mat:
                if _HPN_RE.match(str(elem)):
                    reserved.append(str(elem))
        if reserved:
            raise ValueError(
                f"TychoHeaderGen: symbol(s) {reserved} collide with the "
                f"_hpN_ reserved namespace used by _extract_compound_pow_bases. "
                f"Rename the user-facing symbols."
            )

        collected = []  # compound bases in post-order (deepest first)
        seen = set()

        _int_lo = _POW_INT_RANGE.start
        _int_hi = _POW_INT_RANGE.stop - 1

        def _collect(expr):
            if not isinstance(expr, sp.Basic) or expr.is_Atom:
                return
            for a in expr.args:
                _collect(a)
            if (
                isinstance(expr, sp.Pow)
                and not expr.base.is_Atom
                and not expr.base.is_Symbol
            ):
                exp = expr.exp
                is_half_int = isinstance(exp, sp.Rational) and exp.q == 2
                is_small_int = (
                    isinstance(exp, sp.Integer) and _int_lo <= int(exp) <= _int_hi
                )
                if is_half_int or is_small_int:
                    base = expr.base
                    if base not in seen:
                        seen.add(base)
                        collected.append(base)

        def _walk(obj):
            if isinstance(obj, sp.Matrix):
                for e in obj:
                    _collect(e)
            elif isinstance(obj, (list, tuple)):
                for e in obj:
                    _walk(e)
            elif isinstance(obj, sp.Basic):
                _collect(obj)

        _walk(exprs)

        if not collected:
            return [], exprs

        # Build pow_cses with incremental substitution so nested bases
        # reference earlier _hpN_ entries (e.g. _hp1_ = _hp0_² + y² + z²).
        pow_cses = []
        partial_map = {}
        for i, base in enumerate(collected):
            sym = sp.Symbol(f"_hp{i}_")
            pow_cses.append((sym, base.xreplace(partial_map)))
            partial_map[base] = sym

        full_map = partial_map

        def _apply(obj):
            if isinstance(obj, sp.Matrix):
                return obj.xreplace(full_map)
            if isinstance(obj, list):
                return [_apply(e) for e in obj]
            if isinstance(obj, tuple):
                return tuple(_apply(e) for e in obj)
            if isinstance(obj, sp.Basic):
                return obj.xreplace(full_map)
            return obj

        rewritten = _apply(exprs)
        return pow_cses, rewritten

    # ── class header generation ─────────────────────────────────────────

    # ── precomputed-assignment helpers ──────────────────────────────────

    def _precompute_rhs(self, expr):
        """Render a precomputed-member RHS: ccode → powsimp → std::<fn> prefix.

        Shared between the recompute_cache_() helper, the valued
        constructor, and per-parameter setters so all emit byte-identical
        assignment lines.

        Why we strip Scalar(...) wrappers: powsimp emits ``Scalar(1.0)/...``
        for ``pow(x, -N)`` shapes, which is correct inside the templated
        ``compute_impl`` (where ``Scalar`` is the per-call typedef).  But
        the cache helper and its callers are non-templated member
        functions, and precomputed members are always plain ``double``,
        so keeping the wrapper would fail to compile.  ``Scalar(<n>)``
        on a numeric or single-var argument is a no-op cast there.
        """
        rhs = str(sp.ccode(expr))
        rhs = self.powsimp(rhs)
        rhs = re.sub(r"Scalar\(([^()]*)\)", r"\1", rhs)
        for fn in (
            "sqrt",
            "sin",
            "cos",
            "tan",
            "asin",
            "acos",
            "atan",
            "atan2",
            "exp",
            "log",
        ):
            rhs = re.sub(rf"\b{fn}\(", f"std::{fn}(", rhs)
        return rhs

    def _gen_precompute_assignments(self, targets, indent):
        """Emit ``member = rhs;`` lines for the given precompute targets.

        ``targets`` is a list of ``(member_name, expr)`` tuples (typically
        a subset of ``self._precomputed`` preserving its order).
        """
        return [
            f"{indent}{name} = {self._precompute_rhs(expr)};" for name, expr in targets
        ]

    def _affected_precomputed(self, root_param_names):
        """Return the (ordered) subset of self._precomputed whose expressions
        depend — directly or via earlier ``pcK_`` — on any of the given
        parameters.

        ``root_param_names`` is an iterable of strings (member-form names,
        e.g. ``'mu_'``). Dependency order is preserved by walking
        ``self._precomputed`` in its stored order; any ``pcN_`` whose
        free symbols intersect either the roots or any previously-affected
        ``pcK_`` is itself affected and appended.
        """
        roots = {sp.Symbol(n) for n in root_param_names}
        affected = []
        affected_syms = set()
        for member_name, expr in self._precomputed:
            free = expr.free_symbols
            if (free & roots) or (free & affected_syms):
                affected.append((member_name, expr))
                affected_syms.add(sp.Symbol(member_name))
        return affected

    # ── class header generation ─────────────────────────────────────────

    def gen_class_header(self):
        I = _IND
        jm = "DenseDerivativeMode::Analytic"
        hm = jm if self.compute_hessian else "DenseDerivativeMode::FDiffCentArray"
        nan_init = "std::numeric_limits<double>::quiet_NaN()"

        lines = []
        # `class` (default-private) + `public` inheritance keeps state members
        # encapsulated by default; the public surface is opt-in below.  The
        # explicit `public` on the base class is required because `class`
        # defaults to private inheritance, which would break CRTP.
        lines.append(f"class {self.Name}")
        lines.append(
            f"{I}: public VectorFunction<{self.Name}, {self.ninputs}, "
            f"{self.noutputs}, {jm}, {hm}> {{"
        )
        lines.append(f"{I}public:")
        lines.append(
            f"{I}using Base = VectorFunction<{self.Name}, "
            f"{self.ninputs}, {self.noutputs}, {jm}, {hm}>;"
        )
        lines.append(f"{I}VF_TYPE_ALIASES(Base);")
        vec_flag = "true" if self.is_vectorizable else "false"
        lines.append(f"{I}static constexpr bool is_vectorizable = {vec_flag};")
        lines.append("")

        # State + precomputed members are private — external code must use
        # the constructor / set_xxx setters so cache members stay in sync
        # with their source parameters.
        lines.append(f"{I}private:")

        # Members — scalar params get NSDMI NaN defaults so a nullary-
        # constructed instance fails loudly (NaN propagation) instead of
        # producing garbage from uninitialized memory. Vector/matrix
        # params default-construct to zero via EIGEN_INITIALIZE_MATRICES_BY_ZERO.
        for P, Descr, _ in self.ScalarParams:
            lines.append(f"{I}double {P} = {nan_init}; // {Descr}")
        for Vec, Name, Descr, _ in self.VectorParams:
            vsize = len(Vec)
            lines.append(f"{I}Eigen::Matrix<double, {vsize}, 1> {Name}; // {Descr}")
        for Mat, Name, Descr, _ in self.MatrixParams:
            rows, cols = len(Mat), len(Mat[0])
            lines.append(f"{I}Eigen::Matrix<double, {rows}, {cols}> {Name}; // {Descr}")

        # Precomputed member declarations — also NSDMI NaN so a
        # nullary-constructed instance propagates NaN through the compute
        # path instead of silently reading zero-initialized bytes.
        if self._precomputed:
            lines.append("")
            lines.append(f"{I}// Precomputed from constructor parameters")
            for member_name, _ in self._precomputed:
                lines.append(f"{I}double {member_name} = {nan_init};")

            # Single helper that recomputes every precomputed member from
            # the current parameter state.  The constructor and any setter
            # whose dependency set covers all precomputed members call this
            # to avoid string-duplicating the cache-update sequence.  Setters
            # whose dependency set is a strict subset still inline only the
            # affected entries (preserves the multi-param optimization).
            lines.append("")
            lines.append(f"{I}void recompute_cache_() {{")
            lines += self._gen_precompute_assignments(self._precomputed, 2 * I)
            lines.append(f"{I}}}")
        lines.append("")

        lines.append(f"{I}public:")

        # Constructor params (use the original non-underscore name so the
        # caller-facing API is e.g. MEEDynamics(double mu) rather than mu_).
        def _ctor_args():
            out = []
            for P, _, _ in self.ScalarParams:
                out.append((self._ctor_arg_for.get(str(P), str(P)), "double", False))
            for Vec, Name, _, _ in self.VectorParams:
                vsize = len(Vec)
                out.append((Name, f"const Eigen::Matrix<double, {vsize}, 1>&", True))
            for Mat, Name, _, _ in self.MatrixParams:
                rows, cols = len(Mat), len(Mat[0])
                out.append(
                    (Name, f"const Eigen::Matrix<double, {rows}, {cols}>&", True)
                )
            return out

        ctor_args = _ctor_args()
        paramstr = ", ".join(f"{ty} {nm}" for nm, ty, _ in ctor_args)

        # Zip param entries with their validation constraints and the
        # member-form name used for assignment.
        def _param_records():
            """Yield (member_name, ctor_arg_name, constraint, kind) per param.

            kind is one of 'scalar' | 'vector' | 'matrix'.
            """
            for P, _, constraint in self.ScalarParams:
                ctor_arg = self._ctor_arg_for.get(str(P), str(P))
                yield (str(P), ctor_arg, constraint, "scalar")
            for Vec, Name, _, constraint in self.VectorParams:
                yield (Name, Name, constraint, "vector")
            for Mat, Name, _, constraint in self.MatrixParams:
                yield (Name, Name, constraint, "matrix")

        def _validation_lines(ctor_arg, constraint, indent):
            """Emit an ``if (!(<expr>)) throw ...;`` block for a constraint.

            Constraints are written in the caller-facing name (e.g. ``mu``)
            which matches both ``ctor_arg`` and the setter arg, so the
            same string compiles unchanged in both contexts.
            """
            if not constraint:
                return []
            msg = f"{self.Name}: {ctor_arg} must satisfy {constraint}"
            return [
                f"{indent}if (!({constraint}))",
                f"{indent}{I}throw std::invalid_argument(",
                f'{indent}{I}{I}"{msg}");',
            ]

        # Default constructor.
        #
        # If every scalar param has a declared canonical default and there
        # are no vector/matrix params (which would also need defaults to
        # delegate cleanly), emit a delegating default ctor that constructs
        # via the validating parameterized form.  Otherwise the default
        # ctor is = delete'd: leaving it as a "set_io_rows-only"
        # half-initialized form silently NaN-poisons all compute outputs
        # via the quiet-NaN NSDMI defaults on mu_/pcN_ — a two-phase-init
        # smell flagged by the multi-agent type-design review.
        all_scalars_have_defaults = (
            len(self.ScalarParams) > 0
            and all(
                str(P) in self._scalar_param_defaults for P, _, _ in self.ScalarParams
            )
            and not self.VectorParams
            and not self.MatrixParams
        )
        if all_scalars_have_defaults:
            default_args = ", ".join(
                _format_default_literal(self._scalar_param_defaults[str(P)])
                for P, _, _ in self.ScalarParams
            )
            lines.append(f"{I}{self.Name}() : {self.Name}({default_args}) {{}}")
            lines.append("")
        elif not self.ScalarParams and not self.VectorParams and not self.MatrixParams:
            # Param-free VF: keep the original set_io_rows-only default ctor.
            lines.append(f"{I}{self.Name}() {{")
            lines.append(f"{I}{I}this->set_io_rows({self.ninputs}, {self.noutputs});")
            lines.append(f"{I}}}")
            lines.append("")
        else:
            lines.append(f"{I}{self.Name}() = delete;")
            lines.append("")

        # Parameterized constructor.
        #
        # Validation must precede any assignment, so we use a function-body
        # initializer rather than a member-initializer list — this keeps
        # the emitted shape identical to each per-parameter setter body,
        # and lets both call sites delegate to the same recompute_cache_()
        # helper for cache-update emission.
        lines.append(f"{I}{self.Name}({paramstr}) {{")
        for member_name, ctor_arg, constraint, _ in _param_records():
            lines += _validation_lines(ctor_arg, constraint, 2 * I)
        lines.append(f"{I}{I}this->set_io_rows({self.ninputs}, {self.noutputs});")
        for member_name, ctor_arg, _, kind in _param_records():
            lines.append(f"{I}{I}{member_name} = {ctor_arg};")
        if self._precomputed:
            lines.append(f"{I}{I}this->recompute_cache_();")
        lines.append(f"{I}}}")
        lines.append("")

        # Per-parameter setters. Each setter re-runs the param's
        # constraint, assigns the member, and recomputes any precomputed
        # member that transitively depends on this param (walking the
        # pcN_ dependency graph stored in self._precomputed).
        #
        # For compound (vector/matrix) params, dependency detection must
        # be in terms of the *underlying element symbols* supplied in the
        # SymPy payload, not the C++ container name — the precomputed
        # expressions contain e.g. ``v0, v1, v2``, never a symbol literally
        # named ``v``. Matches the iteration convention in _partition_cses.
        for member_name, ctor_arg, constraint, kind in _param_records():
            if kind == "scalar":
                ty = "double"
                dep_roots = [member_name]
            elif kind == "vector":
                Vec = next(V for V, N, _, _ in self.VectorParams if N == member_name)
                ty = f"const Eigen::Matrix<double, {len(Vec)}, 1>&"
                dep_roots = [str(elem) for elem in Vec]
            else:  # matrix
                Mat = next(M for M, N, _, _ in self.MatrixParams if N == member_name)
                ty = f"const Eigen::Matrix<double, {len(Mat)}, {len(Mat[0])}>&"
                dep_roots = [str(elem) for elem in Mat]
            setter_name = f"set_{ctor_arg}"
            lines.append(f"{I}void {setter_name}({ty} {ctor_arg}) {{")
            lines += _validation_lines(ctor_arg, constraint, 2 * I)
            lines.append(f"{I}{I}{member_name} = {ctor_arg};")
            affected = self._affected_precomputed(dep_roots)
            if affected:
                if len(affected) == len(self._precomputed):
                    lines.append(f"{I}{I}this->recompute_cache_();")
                else:
                    lines += self._gen_precompute_assignments(affected, 2 * I)
            lines.append(f"{I}}}")
            lines.append("")

        # Per-parameter const getters (scalar params only — vector/matrix
        # access is rare enough that the existing public-state setters
        # cover the use case; revisit if a downstream consumer needs them).
        for member_name, ctor_arg, _, kind in _param_records():
            if kind != "scalar":
                continue
            lines.append(
                f"{I}[[nodiscard]] double {ctor_arg}() const noexcept {{ return {member_name}; }}"
            )
            lines.append("")

        return "\n".join(lines) + "\n"

    # ── compute_impl ────────────────────────────────────────────────────

    def gen_compute_impl(self):
        I = _IND
        lines = []
        lines.append(f"{I}template <class InType, class OutType>")
        lines.append(f"{I}inline void compute_impl(CVecRef<InType> x_,")
        lines.append(f"{I}{I}{I}{I}{I}{I} CVecRef<OutType> fx_) const {{")
        lines.append(f"{I}{I}typedef typename InType::Scalar Scalar;")
        lines.append(f"{I}{I}using std::cos; using std::sin; using std::sqrt;")
        lines.append(f"{I}{I}VecRef<OutType> _fx_ = fx_.const_cast_derived();")
        lines.append("")

        body_lines = self._gen_input_names()
        cses, funcs = self._gen_cse_body(self.Func)
        body_lines += self._gen_cselist(cses)
        body_lines.append("")
        for i, F in enumerate(funcs[0]):
            body_lines.append(self._assignment(f"_fx_[{i}]", sp.ccode(F), False))
        lines += [f"{I}{I}{l}" for l in body_lines]

        lines.append(f"{I}}}")
        lines.append("")
        return "\n".join(lines) + "\n"

    # ── compute_jacobian_impl ───────────────────────────────────────────

    def gen_compute_jacobian_impl(self):
        I = _IND
        lines = []
        lines.append(f"{I}template <class InType, class OutType, class JacType>")
        lines.append(f"{I}inline void compute_jacobian_impl(CVecRef<InType> x_,")
        lines.append(f"{I}{I}{I}{I}{I}{I} CVecRef<OutType> fx_,")
        lines.append(f"{I}{I}{I}{I}{I}{I} CMatRef<JacType> jx_) const {{")
        lines.append(f"{I}{I}typedef typename InType::Scalar Scalar;")
        lines.append(f"{I}{I}using std::cos; using std::sin; using std::sqrt;")
        lines.append(f"{I}{I}VecRef<OutType> _fx_ = fx_.const_cast_derived();")
        lines.append(f"{I}{I}MatRef<JacType> _jx_ = jx_.const_cast_derived();")
        lines.append("")

        body_lines = self._gen_input_names()
        cses, funcs = self._gen_cse_body([self.Func, self.Jac])
        body_lines += self._gen_cselist(cses)
        body_lines.append("")

        for i, F in enumerate(funcs[0]):
            body_lines.append(self._assignment(f"_fx_[{i}]", sp.ccode(F), False))
        body_lines.append("")

        for col in range(self.ninputs):
            for row in range(self.noutputs):
                expr = funcs[1][row, col]
                body_lines.append(
                    self._assignment(f"_jx_({row},{col})", sp.ccode(expr), False)
                )

        lines += [f"{I}{I}{l}" for l in body_lines]
        lines.append(f"{I}}}")
        lines.append("")
        return "\n".join(lines) + "\n"

    # ── compute_jacobian_adjointgradient_adjointhessian_impl ────────────

    def gen_compute_all(self):
        I = _IND
        lines = []
        lines.append(f"{I}template <class InType, class OutType, class JacType,")
        lines.append(f"{I}{I}{I}{I} class AdjGradType, class AdjHessType,")
        lines.append(f"{I}{I}{I}{I} class AdjVarType>")
        lines.append(
            f"{I}inline void compute_jacobian_adjointgradient_adjointhessian_impl("
        )
        lines.append(f"{I}{I}CVecRef<InType> x_,")
        lines.append(f"{I}{I}CVecRef<OutType> fx_,")
        lines.append(f"{I}{I}CMatRef<JacType> jx_,")
        lines.append(f"{I}{I}CVecRef<AdjGradType> adjgrad_,")
        lines.append(f"{I}{I}CMatRef<AdjHessType> adjhess_,")
        lines.append(f"{I}{I}CVecRef<AdjVarType> adjvars) const {{")
        lines.append(f"{I}{I}typedef typename InType::Scalar Scalar;")
        lines.append(f"{I}{I}using std::cos; using std::sin; using std::sqrt;")
        lines.append(f"{I}{I}VecRef<OutType> _fx_ = fx_.const_cast_derived();")
        lines.append(f"{I}{I}MatRef<JacType> _jx_ = jx_.const_cast_derived();")
        lines.append(f"{I}{I}VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();")
        lines.append(f"{I}{I}MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();")
        lines.append("")

        body_lines = self._gen_input_names()
        body_lines += self._gen_mult_names()
        cses, funcs = self._gen_cse_body([self.Func, self.Jac, self.Grad, self.Hess])
        body_lines += self._gen_cselist(cses)
        body_lines.append("")

        for i, F in enumerate(funcs[0]):
            body_lines.append(self._assignment(f"_fx_[{i}]", sp.ccode(F), False))
        body_lines.append("")
        for col in range(self.ninputs):
            for row in range(self.noutputs):
                body_lines.append(
                    self._assignment(
                        f"_jx_({row},{col})", sp.ccode(funcs[1][row, col]), False
                    )
                )
        body_lines.append("")
        for row in range(self.ninputs):
            body_lines.append(
                self._assignment(f"_gx_[{row}]", sp.ccode(funcs[2][row]), False)
            )

        # Hessian — exploit symmetry: compute upper triangle, then copy to
        # lower. Must be two separate passes: interleaving the copy inside
        # the upper-triangle loop reads cells that have not been written
        # yet (e.g. at col=0, _hx_(1,0) = _hx_(0,1) but _hx_(0,1) is not
        # assigned until col=1), leaving the lower triangle filled with
        # whatever the matrix was initialized to — zeros in tycho, because
        # the build enables EIGEN_INITIALIZE_MATRICES_BY_ZERO.
        body_lines.append("")
        n = self.ninputs
        for col in range(n):
            for row in range(col + 1):  # upper triangle: write
                body_lines.append(
                    self._assignment(
                        f"_hx_({row},{col})", sp.ccode(funcs[3][row, col]), False
                    )
                )
        body_lines.append("")
        for col in range(n):
            for row in range(col + 1, n):  # lower triangle: copy from upper
                body_lines.append(f"_hx_({row},{col}) = _hx_({col},{row});")

        lines += [f"{I}{I}{l}" for l in body_lines]
        lines.append(f"{I}}}")
        lines.append("")
        return "\n".join(lines) + "\n"

    # ── helpers ─────────────────────────────────────────────────────────

    def _assignment(self, lhs, rhs, is_scalar=False):
        """Return a single assignment line (no leading newline/indent)."""
        rhs = self.fixup(str(rhs))
        prefix = "Scalar " if is_scalar else ""
        return f"{prefix}{lhs} = {rhs};"

    def _gen_input_names(self):
        return [
            self._assignment(str(X), f"x_[{i}]", True)
            for i, X in enumerate(self.Inputs)
        ]

    def _gen_mult_names(self):
        return [
            self._assignment(str(L), f"adjvars[{i}]", True)
            for i, L in enumerate(self.LMults)
        ]

    def _gen_cselist(self, cses):
        return [self._assignment(str(cse[0]), sp.ccode(cse[1]), True) for cse in cses]

    # ── output ──────────────────────────────────────────────────────────

    def print_header(self):
        print(self._build_text())

    def make_header(self, output_dir=None, script_name=None):
        text = self._build_text(script_name=script_name)

        # Defense-in-depth: no compound ``pow(...)`` calls should survive
        # the combination of _extract_compound_pow_bases and powsimp. If
        # one does, it means an exponent outside _POW_INT_RANGE /
        # _POW_HALF_INT_RANGE slipped through, or a base shape the walker
        # doesn't normalize (e.g. a Mul) escaped. Fail the codegen run
        # rather than silently emit an unoptimized runtime pow() call.
        #
        # Scan only the compute bodies: strip C++ line and block comments
        # before checking so a docstring (or any future user-supplied
        # comment) containing the literal ``pow(`` cannot spuriously abort
        # codegen.
        _no_block = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        _no_comments = re.sub(r"//[^\n]*", "", _no_block)
        if "pow(" in _no_comments:
            raise RuntimeError(
                f"TychoHeaderGen({self.Name}): generated text contains an "
                f"unoptimized pow(...) call — check that exponents are in "
                f"_POW_INT_RANGE / _POW_HALF_INT_RANGE and that compound "
                f"bases are lifted by _extract_compound_pow_bases."
            )

        # Tycho convention: header files are snake_case even when the type
        # they declare is PascalCase (e.g. MEEDynamics → mee_dynamics.h).
        fname = self._snake_case(self.Name) + ".h"
        if output_dir:
            fname = os.path.join(output_dir, fname)

        # Atomic write: stage to a sibling ``.tmp`` file, then ``os.replace``.
        # A SymPy/codegen failure partway through must not leave a
        # half-written header committed in the tree.
        tmp = fname + ".tmp"
        with open(tmp, "w") as f:
            f.write(text)
        os.replace(tmp, fname)

    @staticmethod
    def _snake_case(name):
        # MEEDynamics → mee_dynamics, MEEToCartesian → mee_to_cartesian
        s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
        s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
        return s.lower()

    def _build_text(self, script_name=None):
        copyright = _COPYRIGHT.format(script=script_name or "TychoHeaderGen")
        include = (
            f"#pragma once\n"
            f"\n"
            f"#include <limits>\n"
            f"#include <stdexcept>\n"
            f"\n"
            f'#include "{self.include_path}"\n'
        )
        ns_open = f"\nnamespace {self.namespace} {{\n\n{_USING_DECLS}\n"
        header = self.gen_class_header()
        compute = self.gen_compute_impl()
        jacobian = self.gen_compute_jacobian_impl()
        all_impl = self.gen_compute_all() if self.compute_hessian else ""
        ns_close = f"}};\n\n}} // namespace {self.namespace}\n"

        return (
            copyright
            + include
            + ns_open
            + header
            + compute
            + jacobian
            + all_impl
            + ns_close
        )
