///////////////////////////////////////////////////////////////////////////////
// Transcription regression tests (cases 8-12)
//
// Compares current integrator transcription output (Jacobians, Hessians)
// against golden data generated by generate_golden.cpp.
// Uses only public API: integrate_stm, integrate_stm2.
//
// Tolerances are 1e-12 absolute — accommodates ULP-level libm/Eigen 5 trig
// drift across CPUs (see commit babc607).
///////////////////////////////////////////////////////////////////////////////

#include "regression_utils.h"
#include <gtest/gtest.h>

using namespace tycho;
using namespace TychoTest;

class RegressionTranscriptionTest : public VectorFunctionFixture {};

///////////////////////////////////////////////////////////////////////////////
// Helper: compare matrix against golden with tolerance
///////////////////////////////////////////////////////////////////////////////
static void expect_matrix_match(const Eigen::MatrixXd &actual, const Eigen::MatrixXd &golden,
                                double tol, const std::string &label) {
    ASSERT_EQ(actual.rows(), golden.rows()) << label << ": row count mismatch";
    ASSERT_EQ(actual.cols(), golden.cols()) << label << ": col count mismatch";
    for (int i = 0; i < actual.rows(); ++i) {
        for (int j = 0; j < actual.cols(); ++j) {
            EXPECT_NEAR(actual(i, j), golden(i, j), tol)
                << label << ": mismatch at (" << i << "," << j << ")";
        }
    }
}

static void expect_vector_match(const Eigen::VectorXd &actual, const Eigen::VectorXd &golden,
                                double tol, const std::string &label) {
    ASSERT_EQ(actual.size(), golden.size()) << label << ": size mismatch";
    for (int i = 0; i < actual.size(); ++i) {
        EXPECT_NEAR(actual[i], golden[i], tol) << label << ": element " << i;
    }
}

// Relative-tolerance matchers for cases where the golden magnitude spans
// several orders (e.g. single-step transcription Jacobians / Hessians where
// absolute-tolerance comparisons collapse to either bit-exact or useless).
// tol is per-element: |actual - golden| <= tol * max(|golden|, 1.0).
static void expect_matrix_match_rel(const Eigen::MatrixXd &actual, const Eigen::MatrixXd &golden,
                                    double tol, const std::string &label) {
    ASSERT_EQ(actual.rows(), golden.rows()) << label << ": row count mismatch";
    ASSERT_EQ(actual.cols(), golden.cols()) << label << ": col count mismatch";
    for (int i = 0; i < actual.rows(); ++i) {
        for (int j = 0; j < actual.cols(); ++j) {
            double scale = std::max(std::abs(golden(i, j)), 1.0);
            EXPECT_NEAR(actual(i, j), golden(i, j), tol * scale)
                << label << ": mismatch at (" << i << "," << j << ")";
        }
    }
}

static void expect_vector_match_rel(const Eigen::VectorXd &actual, const Eigen::VectorXd &golden,
                                    double tol, const std::string &label) {
    ASSERT_EQ(actual.size(), golden.size()) << label << ": size mismatch";
    for (int i = 0; i < actual.size(); ++i) {
        double scale = std::max(std::abs(golden[i]), 1.0);
        EXPECT_NEAR(actual[i], golden[i], tol * scale) << label << ": element " << i;
    }
}

///////////////////////////////////////////////////////////////////////////////
// Case 8: Two-body Jacobian via integrate_stm
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionTranscriptionTest, Case08_Jacobian) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI87, 10.0);
    integ.set_abs_tol(1e-13);
    integ.set_rel_tol(1e-13);

    auto x0 = leo_circular_x0();
    double tf = leo_period() / 4.0;

    auto [xf, jx] = integ.integrate_stm(x0, tf);

    std::ifstream f(golden_path("trans_08_jacobian.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: trans_08_jacobian.bin";
    auto golden_xf = read_vector(f);
    auto golden_jx = read_matrix(f);

    Eigen::VectorXd xf_dyn = xf;
    expect_vector_match(xf_dyn, golden_xf, 1e-12, "Case08_xf");
    expect_matrix_match(jx, golden_jx, 1e-12, "Case08_Jacobian");
}

///////////////////////////////////////////////////////////////////////////////
// Case 9: Two-body Jacobian+Hessian via integrate_stm2
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionTranscriptionTest, Case09_JacobianHessian) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI87, 10.0);
    integ.set_abs_tol(1e-13);
    integ.set_rel_tol(1e-13);
    integ.vectorize_batch_calls_ = false;

    auto x0 = leo_circular_x0();
    double tf = leo_period() / 4.0;

    using KeplerState = Integrator<Kepler>::IntegRet;
    KeplerState lf;
    auto lf_dyn = deterministic_random_vector(integ.output_rows(), 42, -1.0, 1.0);
    for (int i = 0; i < integ.output_rows(); ++i)
        lf[i] = lf_dyn[i];

    std::vector<KeplerState> x0s = {x0};
    Eigen::VectorXd tfs(1);
    tfs[0] = tf;
    std::vector<KeplerState> lfs = {lf};

    auto results = integ.integrate_stm2(x0s, tfs, lfs);
    auto &[xf, jx, hx] = results[0];

    std::ifstream f(golden_path("trans_09_jacobian_hessian.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: trans_09_jacobian_hessian.bin";
    auto golden_xf = read_vector(f);
    auto golden_jx = read_matrix(f);
    auto golden_hx = read_matrix(f);

    Eigen::VectorXd xf_dyn = xf;
    // Loose numerical tolerance — Hessian values reach magnitudes ~70, where
    // ULP ≈ 1.4e-14; FP reassociation under benign refactors perturbs at
    // that scale. tol=1e-10 is comfortably above ULP at this magnitude
    // without hiding real regressions.
    expect_vector_match(xf_dyn, golden_xf, 1e-13, "Case09_xf");
    expect_matrix_match(jx, golden_jx, 1e-13, "Case09_Jacobian");
    expect_matrix_match(hx, golden_hx, 1e-10, "Case09_Hessian");
}

///////////////////////////////////////////////////////////////////////////////
// Case 10: Batch Jacobians via batch integrate_stm
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionTranscriptionTest, Case10_BatchJacobians) {
    CR3BP_ODE ode(MU_CR3BP);
    Integrator<CR3BP_ODE> integ(ode, IVPAlg::DOPRI87, 0.01);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);
    integ.vectorize_batch_calls_ = true;

    constexpr int N = 4;
    using State = Integrator<CR3BP_ODE>::IntegRet;
    std::vector<State> x0s(N);
    Eigen::VectorXd tfs(N);

    auto base_x0 = cr3bp_l1_x0();
    for (int i = 0; i < N; ++i) {
        x0s[i] = base_x0;
        x0s[i][0] += 0.01 * i;
        x0s[i][4] += 0.02 * (i - 1.5);
        tfs[i] = 0.5 + 0.1 * i;
    }

    auto stm_results = integ.integrate_stm(x0s, tfs);

    std::ifstream f(golden_path("trans_10_batch_jacobians.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: trans_10_batch_jacobians.bin";
    auto golden_jxs = read_matrices(f);

    ASSERT_EQ(static_cast<int>(stm_results.size()), static_cast<int>(golden_jxs.size()))
        << "Batch Jacobian count mismatch";
    for (size_t i = 0; i < stm_results.size(); ++i) {
        auto &jx = std::get<1>(stm_results[i]);
        // Batch SuperScalar Jacobians may have FP noise from instruction ordering
        expect_matrix_match(jx, golden_jxs[i], 1e-14, "Case10_Jac_" + std::to_string(i));
    }
}

// -----------------------------------------------------------------------------
// Cases 11-12: single-step transcription regression.
//
// Single-step Jacobian (Case 11) and Jacobian+Hessian (Case 12) pins exercise
// the non-adaptive integrate_stm / integrate_stm2 paths that aren't covered
// by the adaptive-path regression suite. Goldens are regenerated against the
// current head of branch at abs_tol=rel_tol=1e-13, adaptive_=false — the same
// integrator configuration the tests use — so the golden and live values
// should agree within a few ULPs of double precision.
// -----------------------------------------------------------------------------

// Absolute tolerance for non-adaptive single-step Jacobians/Hessians.
// Single-step integrate at atol=rtol=1e-13 produces values agreeing with
// their goldens to a few ULPs; 1e-13 is comfortably above that noise floor.
static constexpr double kTranscriptionAbsTol = 1e-13;

///////////////////////////////////////////////////////////////////////////////
// Case 11: Two-body single-step Jacobian via integrate_stm (DOPRI54)
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionTranscriptionTest, Case11_SingleStepJacobian) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI54, 10.0);
    integ.set_abs_tol(1e-13);
    integ.set_rel_tol(1e-13);
    integ.adaptive_ = false;

    auto x0 = leo_circular_x0();
    double tf = 10.0;

    auto [xf, jx] = integ.integrate_stm(x0, tf);

    std::ifstream f(golden_path("trans_11_single_step_jac.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: trans_11_single_step_jac.bin";
    auto golden_xf = read_vector(f);
    auto golden_jx = read_matrix(f);

    Eigen::VectorXd xf_dyn = xf;
    expect_vector_match(xf_dyn, golden_xf, kTranscriptionAbsTol, "Case11_xf");
    expect_matrix_match(jx, golden_jx, kTranscriptionAbsTol, "Case11_Jacobian");
}

///////////////////////////////////////////////////////////////////////////////
// Case 12: Two-body single-step Jacobian+Hessian via integrate_stm2 (DOPRI87)
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionTranscriptionTest, Case12_SingleStepJacobianHessian) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI87, 10.0);
    integ.set_abs_tol(1e-13);
    integ.set_rel_tol(1e-13);
    integ.adaptive_ = false;
    integ.vectorize_batch_calls_ = false;

    auto x0 = leo_circular_x0();
    double tf = 10.0;

    using KeplerState = Integrator<Kepler>::IntegRet;
    KeplerState lf;
    auto lf_dyn = deterministic_random_vector(integ.output_rows(), 99, -1.0, 1.0);
    for (int i = 0; i < integ.output_rows(); ++i)
        lf[i] = lf_dyn[i];

    std::vector<KeplerState> x0s = {x0};
    Eigen::VectorXd tfs(1);
    tfs[0] = tf;
    std::vector<KeplerState> lfs = {lf};

    auto results = integ.integrate_stm2(x0s, tfs, lfs);
    auto &[xf, jx, hx] = results[0];

    std::ifstream f(golden_path("trans_12_single_step_jac_hess.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: trans_12_single_step_jac_hess.bin";
    auto golden_xf = read_vector(f);
    auto golden_jx = read_matrix(f);
    auto golden_hx = read_matrix(f);

    Eigen::VectorXd xf_dyn = xf;
    expect_vector_match(xf_dyn, golden_xf, kTranscriptionAbsTol, "Case12_xf");
    expect_matrix_match(jx, golden_jx, kTranscriptionAbsTol, "Case12_Jacobian");
    expect_matrix_match(hx, golden_hx, kTranscriptionAbsTol, "Case12_Hessian");
}
