///////////////////////////////////////////////////////////////////////////////
// IVP regression tests (cases 1-7)
//
// Compares current integrator output against golden data generated by
// generate_golden.cpp. Any deviation indicates a behavioral change that
// must be reviewed before proceeding with refactoring.
//
// Tolerances are 1e-12 absolute (matches expect_vector_match's EXPECT_NEAR
// semantics) — comfortably tight on unit-magnitude state vectors while
// accommodating ULP-level libm/Eigen 5 trig drift across CPUs (see
// commit babc607 for the original drift incident).
///////////////////////////////////////////////////////////////////////////////

#include "regression_utils.h"
#include <cmath>
#include <gtest/gtest.h>

using namespace tycho;
using namespace TychoTest;

class RegressionIVPTest : public VectorFunctionFixture {};

///////////////////////////////////////////////////////////////////////////////
// Helper: compare vector against golden with tolerance
///////////////////////////////////////////////////////////////////////////////
static void expect_vector_match(const Eigen::VectorXd &actual, const Eigen::VectorXd &golden,
                                double tol, const std::string &label) {
    ASSERT_EQ(actual.size(), golden.size()) << label << ": size mismatch";
    for (int i = 0; i < actual.size(); ++i) {
        EXPECT_NEAR(actual[i], golden[i], tol) << label << ": element " << i;
    }
}

///////////////////////////////////////////////////////////////////////////////
// Helper: compare against golden with combined relative + absolute bounds,
// i.e. |actual - golden| <= atol + rtol * |golden| (numpy allclose semantics).
// Use this when the state vector mixes magnitudes (e.g. km-scale positions
// alongside near-zero components), where a single absolute tolerance cannot be
// both tight on the small elements and loose enough for the large ones.
///////////////////////////////////////////////////////////////////////////////
static void expect_vector_close(const Eigen::VectorXd &actual, const Eigen::VectorXd &golden,
                                double rtol, double atol, const std::string &label) {
    ASSERT_EQ(actual.size(), golden.size()) << label << ": size mismatch";
    for (int i = 0; i < actual.size(); ++i) {
        const double bound = atol + rtol * std::abs(golden[i]);
        EXPECT_LE(std::abs(actual[i] - golden[i]), bound)
            << label << ": element " << i << " (actual=" << actual[i]
            << ", golden=" << golden[i] << ", bound=" << bound << ")";
    }
}

///////////////////////////////////////////////////////////////////////////////
// Case 1: Two-body DOPRI54 — LEO circular orbit, quarter period
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case01_TwoBody_DOPRI54) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI54, 10.0);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);

    auto x0 = leo_circular_x0();
    double tf = leo_period() / 4.0;
    auto xf = integ.integrate(x0, tf);

    std::ifstream f(golden_path("ivp_01_twobody_dopri54.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_01_twobody_dopri54.bin";
    auto golden_xf = read_vector(f);

    expect_vector_match(xf, golden_xf, 1e-12, "Case01_xf");
}

///////////////////////////////////////////////////////////////////////////////
// Case 2: Two-body DOPRI87 — Same orbit, same duration
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case02_TwoBody_DOPRI87) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI87, 10.0);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);

    auto x0 = leo_circular_x0();
    double tf = leo_period() / 4.0;
    auto xf = integ.integrate(x0, tf);

    std::ifstream f(golden_path("ivp_02_twobody_dopri87.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_02_twobody_dopri87.bin";
    auto golden_xf = read_vector(f);

    expect_vector_match(xf, golden_xf, 1e-12, "Case02_xf");
}

///////////////////////////////////////////////////////////////////////////////
// Case 3: CR3BP L1 halo DOPRI87 — Earth-Moon system near L1 region
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case03_CR3BP_DOPRI87) {
    CR3BP_ODE ode(MU_CR3BP);
    Integrator<CR3BP_ODE> integ(ode, IVPAlg::DOPRI87, 0.01);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);

    auto x0 = cr3bp_l1_x0();
    double tf = 2.0;
    auto xf = integ.integrate(x0, tf);

    std::ifstream f(golden_path("ivp_03_cr3bp_dopri87.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_03_cr3bp_dopri87.bin";
    auto golden_xf = read_vector(f);

    expect_vector_match(xf, golden_xf, 1e-12, "Case03_xf");
}

///////////////////////////////////////////////////////////////////////////////
// Case 4: Forced control DOPRI54 — BrachODE with constant control
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case04_BrachForced) {
    BrachODE ode(9.81);
    Eigen::VectorXd u(1);
    u << std::numbers::pi / 4.0;
    Integrator<BrachODE> integ(ode, 0.01, u);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);

    Eigen::VectorXd x0(5);
    x0 << 0.0, 10.0, 0.1, 0.0, std::numbers::pi / 4.0;
    double tf = 1.0;
    auto xf = integ.integrate(x0, tf);

    std::ifstream f(golden_path("ivp_04_brach_forced.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_04_brach_forced.bin";
    auto golden_xf = read_vector(f);

    expect_vector_match(xf, golden_xf, 1e-12, "Case04_xf");
}

///////////////////////////////////////////////////////////////////////////////
// Case 5: Altitude crossing event DOPRI54 — Eccentric orbit
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case05_EventCrossing) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI54, 10.0);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);

    auto x0 = eccentric_orbit_x0();
    double tf = eccentric_orbit_period();

    auto args = Arguments<7>();
    auto r = args.head<3>().norm();
    auto event_func = r + (-7000.0);
    GenericFunction<-1, 1> gf(event_func);
    std::vector<Integrator<Kepler>::EventPack> events;
    events.push_back({gf, 0, 0});

    auto [xf, eventlocs] = integ.integrate(x0, tf, events);

    std::ifstream f(golden_path("ivp_05_event_crossing.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_05_event_crossing.bin";
    auto golden_xf = read_vector(f);

    // Final state comparison — event detection introduces some FP noise.
    // 1e-12 absolute accommodates ULP-level libm/Eigen 5 trig drift across
    // CPUs (see commit babc607).
    expect_vector_match(xf, golden_xf, 1e-12, "Case05_xf");

    // Read and compare event locations
    int32_t ngroups = read_int32(f);
    ASSERT_EQ(static_cast<int32_t>(eventlocs.size()), ngroups) << "Event group count mismatch";
    for (int g = 0; g < ngroups; ++g) {
        auto golden_group = read_vectors(f);
        ASSERT_EQ(eventlocs[g].size(), golden_group.size())
            << "Event count mismatch in group " << g;
        for (size_t e = 0; e < eventlocs[g].size(); ++e) {
            // Refined crossings are 1:1 with eventtimes; a golden-test
            // regression would never run against nullopt entries (they
            // mean refinement failed). Assert presence before comparing.
            ASSERT_TRUE(eventlocs[g][e].has_value())
                << "Case05_event_g" << g << "_e" << e << " refinement failed unexpectedly";
            // Event locations are resolved by Newton to event_tol_=1e-6 by
            // default; pinning tighter than that is a platform-brittle FP
            // drift test, not a correctness gate. Use 1e-6 to catch real
            // drift without flagging ULP-level shifts.
            expect_vector_match(*eventlocs[g][e], golden_group[e], 1e-6,
                                "Case05_event_g" + std::to_string(g) + "_e" + std::to_string(e));
        }
    }
}

///////////////////////////////////////////////////////////////////////////////
// Case 6: Batch N=8 trajectories DOPRI87 — SuperScalar batch
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case06_Batch_DOPRI87) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI87, 10.0);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);
    integ.vectorize_batch_calls_ = true;

    constexpr int N = 8;
    using KeplerState = Integrator<Kepler>::IntegRet;
    std::vector<KeplerState> x0s(N);
    Eigen::VectorXd tfs(N);

    for (int i = 0; i < N; ++i) {
        double r0 = 6800.0 + 200.0 * i;
        double v0 = std::sqrt(MU_EARTH / r0);
        x0s[i] << r0, 0.0, 0.0, 0.0, v0, 0.0, 0.0;
        double T = 2.0 * std::numbers::pi * std::sqrt(r0 * r0 * r0 / MU_EARTH);
        tfs[i] = T / 4.0;
    }

    auto xfs = integ.integrate(x0s, tfs);

    std::ifstream f(golden_path("ivp_06_batch_dopri87.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_06_batch_dopri87.bin";
    auto golden_xfs = read_vectors(f);

    ASSERT_EQ(static_cast<int>(xfs.size()), static_cast<int>(golden_xfs.size()))
        << "Batch result count mismatch";
    for (size_t i = 0; i < xfs.size(); ++i) {
        // The SuperScalar batch path differs from the scalar golden by FP
        // instruction-ordering noise. These state vectors mix km-scale
        // positions (~6800-7400) with near-zero components (~1e-10), so a
        // single absolute tolerance cannot fit both: the position drift alone
        // reaches ~1e-11. Compare with combined relative+absolute bounds —
        // 1e-12 relative (consistent with the other cases' tightness on
        // unit-magnitude states) plus a 1e-10 absolute floor for the
        // near-zero elements. The previous 1e-14 absolute tol was below the
        // ULP distance at km magnitudes and inherently un-satisfiable.
        Eigen::VectorXd xf_dyn = xfs[i]; // Convert fixed to dynamic for comparison
        expect_vector_close(xf_dyn, golden_xfs[i], 1e-12, 1e-10,
                            "Case06_batch_" + std::to_string(i));
    }
}

///////////////////////////////////////////////////////////////////////////////
// Case 7: Backward integration DOPRI54 — LEO orbit forward then backward
///////////////////////////////////////////////////////////////////////////////
TEST_F(RegressionIVPTest, Case07_Backward) {
    Kepler kep(MU_EARTH);
    Integrator<Kepler> integ(kep, IVPAlg::DOPRI54, 10.0);
    integ.set_abs_tol(1e-12);
    integ.set_rel_tol(1e-13);

    auto x0 = leo_circular_x0();
    double tf_fwd = leo_period() / 4.0;

    auto xf = integ.integrate(x0, tf_fwd);
    auto xr = integ.integrate(xf, 0.0);

    std::ifstream f(golden_path("ivp_07_backward.bin"), std::ios::binary);
    ASSERT_TRUE(f.good()) << "Golden file not found: ivp_07_backward.bin";
    auto golden_xf = read_vector(f);
    auto golden_xr = read_vector(f);

    expect_vector_match(xf, golden_xf, 1e-12, "Case07_forward");
    expect_vector_match(xr, golden_xr, 1e-12, "Case07_backward");
}
