// =============================================================================
// Tycho fork (Copyright 2026-present Grant R. Hecht, Apache 2.0 — see LICENSE.txt)
//
// Generated by utils/codegen_kepler_propagator.py — do not edit manually.
// =============================================================================
#pragma once

#include <limits>
#include <stdexcept>

#include "tycho/vector_functions.h"

namespace tycho::astro::detail {

// Import cross-namespace types from vf.
using vf::CMatRef;
using vf::CVecRef;
using vf::DenseDerivativeMode;
using vf::MatRef;
using vf::VecRef;
using vf::VectorFunction;

class KeplerResidual
    : public VectorFunction<KeplerResidual, 10, 1, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic> {
    public:
    using Base = VectorFunction<KeplerResidual, 10, 1, DenseDerivativeMode::Analytic, DenseDerivativeMode::Analytic>;
    VF_TYPE_ALIASES(Base);
    static constexpr bool is_vectorizable = true;

    private:
    double mu_ = std::numeric_limits<double>::quiet_NaN(); // Gravitational parameter

    // Precomputed from constructor parameters
    double pc0_ = std::numeric_limits<double>::quiet_NaN();
    double pc1_ = std::numeric_limits<double>::quiet_NaN();

    void recompute_cache_() {
        pc0_ = std::sqrt(mu_);
        pc1_ = 1.0/pc0_;
    }

    public:
    KeplerResidual() : KeplerResidual(1.0) {}

    KeplerResidual(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument(
                "KeplerResidual: mu must satisfy mu > 0.0");
        this->set_io_rows(10, 1);
        mu_ = mu;
        this->recompute_cache_();
    }

    void set_mu(double mu) {
        if (!(mu > 0.0))
            throw std::invalid_argument(
                "KeplerResidual: mu must satisfy mu > 0.0");
        mu_ = mu;
        this->recompute_cache_();
    }

    [[nodiscard]] double mu() const noexcept { return mu_; }

    template <class InType, class OutType>
    inline void compute_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();

        Scalar R0_0 = x_[0];
        Scalar R0_1 = x_[1];
        Scalar R0_2 = x_[2];
        Scalar V0_0 = x_[3];
        Scalar V0_1 = x_[4];
        Scalar V0_2 = x_[5];
        Scalar dt = x_[6];
        Scalar U1 = x_[7];
        Scalar U2 = x_[8];
        Scalar U3 = x_[9];
        Scalar _hp0_ = (R0_0*R0_0) + (R0_1*R0_1) + (R0_2*R0_2);
        
        _fx_[0] = Scalar(U1*sqrt(_hp0_) + U2*pc1_*(R0_0*V0_0 + R0_1*V0_1 + R0_2*V0_2) + U3 - dt*pc0_);
    }

    template <class InType, class OutType, class JacType>
    inline void compute_jacobian_impl(CVecRef<InType> x_,
                         CVecRef<OutType> fx_,
                         CMatRef<JacType> jx_) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();

        Scalar R0_0 = x_[0];
        Scalar R0_1 = x_[1];
        Scalar R0_2 = x_[2];
        Scalar V0_0 = x_[3];
        Scalar V0_1 = x_[4];
        Scalar V0_2 = x_[5];
        Scalar dt = x_[6];
        Scalar U1 = x_[7];
        Scalar U2 = x_[8];
        Scalar U3 = x_[9];
        Scalar _hp0_ = (R0_0*R0_0) + (R0_1*R0_1) + (R0_2*R0_2);
        Scalar x10 = sqrt(_hp0_);
        Scalar x11 = Scalar(pc1_*(R0_0*V0_0 + R0_1*V0_1 + R0_2*V0_2));
        Scalar x12 = Scalar(U2*pc1_);
        Scalar x13 = U1/x10;
        
        _fx_[0] = Scalar(U1*x10 + U2*x11 + U3 - dt*pc0_);
        
        _jx_(0,0) = R0_0*x13 + V0_0*x12;
        _jx_(0,1) = R0_1*x13 + V0_1*x12;
        _jx_(0,2) = R0_2*x13 + V0_2*x12;
        _jx_(0,3) = R0_0*x12;
        _jx_(0,4) = R0_1*x12;
        _jx_(0,5) = R0_2*x12;
        _jx_(0,6) = Scalar(-pc0_);
        _jx_(0,7) = x10;
        _jx_(0,8) = x11;
        _jx_(0,9) = 1;
    }

    template <class InType, class OutType, class JacType,
                 class AdjGradType, class AdjHessType,
                 class AdjVarType>
    inline void compute_jacobian_adjointgradient_adjointhessian_impl(
        CVecRef<InType> x_,
        CVecRef<OutType> fx_,
        CMatRef<JacType> jx_,
        CVecRef<AdjGradType> adjgrad_,
        CMatRef<AdjHessType> adjhess_,
        CVecRef<AdjVarType> adjvars) const {
        typedef typename InType::Scalar Scalar;
        using std::cos; using std::sin; using std::sqrt;
        VecRef<OutType> _fx_ = fx_.const_cast_derived();
        MatRef<JacType> _jx_ = jx_.const_cast_derived();
        VecRef<AdjGradType> _gx_ = adjgrad_.const_cast_derived();
        MatRef<AdjHessType> _hx_ = adjhess_.const_cast_derived();

        Scalar R0_0 = x_[0];
        Scalar R0_1 = x_[1];
        Scalar R0_2 = x_[2];
        Scalar V0_0 = x_[3];
        Scalar V0_1 = x_[4];
        Scalar V0_2 = x_[5];
        Scalar dt = x_[6];
        Scalar U1 = x_[7];
        Scalar U2 = x_[8];
        Scalar U3 = x_[9];
        Scalar LM0 = adjvars[0];
        Scalar _hp0_ = (R0_0*R0_0) + (R0_1*R0_1) + (R0_2*R0_2);
        Scalar x10 = sqrt(_hp0_);
        Scalar x11 = Scalar(pc1_*(R0_0*V0_0 + R0_1*V0_1 + R0_2*V0_2));
        Scalar x12 = Scalar(U2*pc1_);
        Scalar x13 = 1.0/x10;
        Scalar x14 = U1*x13;
        Scalar x15 = R0_0*x14 + V0_0*x12;
        Scalar x16 = R0_1*x14 + V0_1*x12;
        Scalar x17 = R0_2*x14 + V0_2*x12;
        Scalar x18 = R0_0*x12;
        Scalar x19 = R0_1*x12;
        Scalar x20 = R0_2*x12;
        Scalar x21 = -U1*x13;
        Scalar x22 = U1/(sqrt(_hp0_)*_hp0_);
        Scalar x23 = LM0*R0_0*x22;
        Scalar x24 = -R0_1*x23;
        Scalar x25 = -R0_2*x23;
        Scalar x26 = LM0*x12;
        Scalar x27 = LM0*x13;
        Scalar x28 = R0_0*x27;
        Scalar x29 = Scalar(LM0*pc1_);
        Scalar x30 = V0_0*x29;
        Scalar x31 = -LM0*R0_1*R0_2*x22;
        Scalar x32 = R0_1*x27;
        Scalar x33 = V0_1*x29;
        Scalar x34 = R0_2*x27;
        Scalar x35 = V0_2*x29;
        Scalar x36 = R0_0*x29;
        Scalar x37 = R0_1*x29;
        Scalar x38 = R0_2*x29;
        
        _fx_[0] = Scalar(U1*x10 + U2*x11 + U3 - dt*pc0_);
        
        _jx_(0,0) = x15;
        _jx_(0,1) = x16;
        _jx_(0,2) = x17;
        _jx_(0,3) = x18;
        _jx_(0,4) = x19;
        _jx_(0,5) = x20;
        _jx_(0,6) = Scalar(-pc0_);
        _jx_(0,7) = x10;
        _jx_(0,8) = x11;
        _jx_(0,9) = 1;
        
        _gx_[0] = LM0*x15;
        _gx_[1] = LM0*x16;
        _gx_[2] = LM0*x17;
        _gx_[3] = LM0*x18;
        _gx_[4] = LM0*x19;
        _gx_[5] = LM0*x20;
        _gx_[6] = Scalar(-LM0*pc0_);
        _gx_[7] = LM0*x10;
        _gx_[8] = LM0*x11;
        _gx_[9] = LM0;
        
        _hx_(0,0) = LM0*(-(R0_0*R0_0)*x22 - x21);
        _hx_(0,1) = x24;
        _hx_(1,1) = LM0*(-(R0_1*R0_1)*x22 - x21);
        _hx_(0,2) = x25;
        _hx_(1,2) = x31;
        _hx_(2,2) = LM0*(-(R0_2*R0_2)*x22 - x21);
        _hx_(0,3) = x26;
        _hx_(1,3) = 0;
        _hx_(2,3) = 0;
        _hx_(3,3) = 0;
        _hx_(0,4) = 0;
        _hx_(1,4) = x26;
        _hx_(2,4) = 0;
        _hx_(3,4) = 0;
        _hx_(4,4) = 0;
        _hx_(0,5) = 0;
        _hx_(1,5) = 0;
        _hx_(2,5) = x26;
        _hx_(3,5) = 0;
        _hx_(4,5) = 0;
        _hx_(5,5) = 0;
        _hx_(0,6) = 0;
        _hx_(1,6) = 0;
        _hx_(2,6) = 0;
        _hx_(3,6) = 0;
        _hx_(4,6) = 0;
        _hx_(5,6) = 0;
        _hx_(6,6) = 0;
        _hx_(0,7) = x28;
        _hx_(1,7) = x32;
        _hx_(2,7) = x34;
        _hx_(3,7) = 0;
        _hx_(4,7) = 0;
        _hx_(5,7) = 0;
        _hx_(6,7) = 0;
        _hx_(7,7) = 0;
        _hx_(0,8) = x30;
        _hx_(1,8) = x33;
        _hx_(2,8) = x35;
        _hx_(3,8) = x36;
        _hx_(4,8) = x37;
        _hx_(5,8) = x38;
        _hx_(6,8) = 0;
        _hx_(7,8) = 0;
        _hx_(8,8) = 0;
        _hx_(0,9) = 0;
        _hx_(1,9) = 0;
        _hx_(2,9) = 0;
        _hx_(3,9) = 0;
        _hx_(4,9) = 0;
        _hx_(5,9) = 0;
        _hx_(6,9) = 0;
        _hx_(7,9) = 0;
        _hx_(8,9) = 0;
        _hx_(9,9) = 0;
        
        _hx_(1,0) = _hx_(0,1);
        _hx_(2,0) = _hx_(0,2);
        _hx_(3,0) = _hx_(0,3);
        _hx_(4,0) = _hx_(0,4);
        _hx_(5,0) = _hx_(0,5);
        _hx_(6,0) = _hx_(0,6);
        _hx_(7,0) = _hx_(0,7);
        _hx_(8,0) = _hx_(0,8);
        _hx_(9,0) = _hx_(0,9);
        _hx_(2,1) = _hx_(1,2);
        _hx_(3,1) = _hx_(1,3);
        _hx_(4,1) = _hx_(1,4);
        _hx_(5,1) = _hx_(1,5);
        _hx_(6,1) = _hx_(1,6);
        _hx_(7,1) = _hx_(1,7);
        _hx_(8,1) = _hx_(1,8);
        _hx_(9,1) = _hx_(1,9);
        _hx_(3,2) = _hx_(2,3);
        _hx_(4,2) = _hx_(2,4);
        _hx_(5,2) = _hx_(2,5);
        _hx_(6,2) = _hx_(2,6);
        _hx_(7,2) = _hx_(2,7);
        _hx_(8,2) = _hx_(2,8);
        _hx_(9,2) = _hx_(2,9);
        _hx_(4,3) = _hx_(3,4);
        _hx_(5,3) = _hx_(3,5);
        _hx_(6,3) = _hx_(3,6);
        _hx_(7,3) = _hx_(3,7);
        _hx_(8,3) = _hx_(3,8);
        _hx_(9,3) = _hx_(3,9);
        _hx_(5,4) = _hx_(4,5);
        _hx_(6,4) = _hx_(4,6);
        _hx_(7,4) = _hx_(4,7);
        _hx_(8,4) = _hx_(4,8);
        _hx_(9,4) = _hx_(4,9);
        _hx_(6,5) = _hx_(5,6);
        _hx_(7,5) = _hx_(5,7);
        _hx_(8,5) = _hx_(5,8);
        _hx_(9,5) = _hx_(5,9);
        _hx_(7,6) = _hx_(6,7);
        _hx_(8,6) = _hx_(6,8);
        _hx_(9,6) = _hx_(6,9);
        _hx_(8,7) = _hx_(7,8);
        _hx_(9,7) = _hx_(7,9);
        _hx_(9,8) = _hx_(8,9);
    }

};

} // namespace tycho::astro::detail
