from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray

from . import kepler as kepler
import _tychopy.vector_functions


@overload
def cartesian_to_classic(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

@overload
def cartesian_to_classic(arg0: _tychopy.vector_functions.VectorFunction, arg1: float, /) -> _tychopy.vector_functions.VectorFunction: ...

@overload
def cartesian_to_modified(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

@overload
def cartesian_to_modified(arg0: _tychopy.vector_functions.VectorFunction, arg1: float, /) -> _tychopy.vector_functions.VectorFunction: ...

def classic_to_cartesian(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

def classic_to_modified(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

@overload
def modified_to_cartesian(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

@overload
def modified_to_cartesian(arg0: _tychopy.vector_functions.VectorFunction, arg1: float, /) -> _tychopy.vector_functions.VectorFunction: ...

def modified_to_classic(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

def cartesian_to_classic_true(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

class ModifiedToCartesian:
    def __init__(self, arg: float, /) -> None: ...

    def input_rows(self) -> int: ...

    def output_rows(self) -> int: ...

    def name(self) -> str: ...

    def input_domain(self) -> Annotated[NDArray[numpy.int32], dict(shape=(2, None), order='F')]: ...

    def is_linear(self) -> bool: ...

    @overload
    def compute(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def compute(self, arg: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def __call__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def __call__(self, arg: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def jacobian(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def jacobian(self, arg: numpy.ndarray, /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def compute_jacobian(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def compute_jacobian(self, arg: numpy.ndarray, /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def adjointgradient(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def adjointgradient(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def adjointhessian(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def adjointhessian(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def computeall(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def computeall(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    def vf(self) -> _tychopy.vector_functions.VectorFunction: ...

class CartesianToClassic:
    def __init__(self, arg: float, /) -> None: ...

    def input_rows(self) -> int: ...

    def output_rows(self) -> int: ...

    def name(self) -> str: ...

    def input_domain(self) -> Annotated[NDArray[numpy.int32], dict(shape=(2, None), order='F')]: ...

    def is_linear(self) -> bool: ...

    @overload
    def compute(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def compute(self, arg: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def __call__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def __call__(self, arg: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def jacobian(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def jacobian(self, arg: numpy.ndarray, /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def compute_jacobian(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def compute_jacobian(self, arg: numpy.ndarray, /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def adjointgradient(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def adjointgradient(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def adjointhessian(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def adjointhessian(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def computeall(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def computeall(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    def vf(self) -> _tychopy.vector_functions.VectorFunction: ...

class CartesianToMEE:
    def __init__(self, arg: float, /) -> None: ...

    def input_rows(self) -> int: ...

    def output_rows(self) -> int: ...

    def name(self) -> str: ...

    def input_domain(self) -> Annotated[NDArray[numpy.int32], dict(shape=(2, None), order='F')]: ...

    def is_linear(self) -> bool: ...

    @overload
    def compute(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def compute(self, arg: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def __call__(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def __call__(self, arg: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def jacobian(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def jacobian(self, arg: numpy.ndarray, /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def compute_jacobian(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def compute_jacobian(self, arg: numpy.ndarray, /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def adjointgradient(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> numpy.ndarray: ...

    @overload
    def adjointgradient(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> numpy.ndarray: ...

    @overload
    def adjointhessian(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def adjointhessian(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @overload
    def computeall(self, arg0: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    @overload
    def computeall(self, arg0: numpy.ndarray, arg1: numpy.ndarray, /) -> tuple[numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], numpy.ndarray, Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]]: ...

    def vf(self) -> _tychopy.vector_functions.VectorFunction: ...

def propagate_cartesian(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, arg2: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

def propagate_classic(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, arg2: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

def propagate_modified(arg0: Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')], arg1: float, arg2: float, /) -> Annotated[NDArray[numpy.float64], dict(shape=(6), order='C')]: ...

@overload
def lambert_izzo(arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: float, arg3: float, arg4: bool, /) -> "std::array<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 2ul>": ...

@overload
def lambert_izzo(arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: float, arg3: float, arg4: bool, arg5: int, arg6: bool, /) -> "std::array<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 2ul>": ...

@overload
def lambert_izzo(arg0: Annotated[NDArray[numpy.float64], dict(shape=(None, None), writable=False)], arg1: Annotated[NDArray[numpy.float64], dict(shape=(None, None), writable=False)], arg2: Annotated[NDArray[numpy.float64], dict(shape=(None,), writable=False)], arg3: float, arg4: Sequence[bool], arg5: Annotated[NDArray[numpy.float64], dict(shape=(None, None))], arg6: Annotated[NDArray[numpy.float64], dict(shape=(None, None))], arg7: int, arg8: bool, /) -> numpy.ndarray: ...

def lambert_izzo_multirev(arg0: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], arg2: float, arg3: float, arg4: bool, arg5: int, arg6: bool, /) -> "std::array<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 2ul>": ...

def modified_dynamics(arg: float, /) -> _tychopy.vector_functions.VectorFunction: ...

def cartesian_dynamics(arg: float, /) -> _tychopy.vector_functions.VectorFunction: ...

def crtbp_dynamics(arg: float, /) -> _tychopy.vector_functions.VectorFunction: ...

def j2_cartesian(arg0: float, arg1: float, arg2: float, /) -> _tychopy.vector_functions.VectorFunction: ...

def non_ideal_solar_sail(arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, /) -> _tychopy.vector_functions.VectorFunction: ...
