from typing import overload


def get_core_count() -> int: ...

def set_num_threads(n: int) -> None: ...

def get_num_threads() -> int: ...

class BumpAllocator:
    @overload
    @staticmethod
    def resize(arg: int, /) -> None: ...

    @overload
    @staticmethod
    def resize(arg0: int, arg1: int, /) -> None: ...

    @staticmethod
    def size_scalar() -> int: ...

    @staticmethod
    def size_super_scalar() -> int: ...
